/* =========================================================================
   flashcard-data.js — Sistemi e Reti · 17 Argomenti
   ========================================================================= */

window.flashcardData = {

  /* ── ARG 1: TCP/IP e Indirizzi IP ── */
  "tcpip": [
    { fronte: "Cos'è un indirizzo IP?",
      retro: "Identificatore numerico univoco a 32 bit (IPv4) assegnato a ogni interfaccia di rete. Scritto in notazione decimale puntata (es. 192.168.1.1). Permette di identificare host e reti su Internet." },
    { fronte: "Cos'è una subnet mask?",
      retro: "Maschera a 32 bit che separa la parte di rete dalla parte host di un indirizzo IP. Bit a 1 = parte rete, bit a 0 = parte host. Es. 255.255.255.0 (= /24): prime 3 ottetti = rete." },
    { fronte: "Differenza TCP vs UDP",
      retro: "TCP: orientato alla connessione, affidabile (conferma ricezione), ordinato, controllo flusso — più lento. UDP: senza connessione, non affidabile, veloce e leggero. TCP per HTTP/FTP/SSH; UDP per DNS/streaming/giochi." },
    { fronte: "Cos'è una porta di rete?",
      retro: "Numero 16-bit (0-65535) che identifica uno specifico processo/servizio sull'host. Well-known: 0-1023; Registered: 1024-49151; Dynamic: 49152-65535. Permette multiplexing delle connessioni su un singolo IP." },
    { fronte: "Classi IP: A, B, C",
      retro: "A: 1-126.x.x.x, /8, ~16M host. B: 128-191.x.x.x, /16, ~65K host. C: 192-223.x.x.x, /24, 254 host. D: multicast. E: sperimentale." },
    { fronte: "Indirizzi IP privati (RFC 1918)",
      retro: "Classe A: 10.0.0.0/8. Classe B: 172.16.0.0–172.31.255.255 (/12). Classe C: 192.168.0.0/16. Non instradabili su Internet — usati nelle LAN private con NAT." },
    { fronte: "Cos'è il loopback?",
      retro: "127.0.0.1 (o qualsiasi indirizzo 127.x.x.x): pacchetti inviati a questo indirizzo tornano allo stesso host senza passare per la rete fisica. Usato per test locali e comunicazione tra processi sulla stessa macchina." },
    { fronte: "CIDR (Classless Inter-Domain Routing)",
      retro: "Notazione /n dove n = numero di bit della parte rete. Supera le classi fisse IP, permettendo blocchi di qualsiasi dimensione. Es. /26 = 64 indirizzi (62 host), /30 = 4 indirizzi (2 host)." },
    { fronte: "IPv6 vs IPv4 — perché il passaggio?",
      retro: "IPv4: 32 bit = ~4,3 miliardi di indirizzi, ormai esauriti. IPv6: 128 bit = 3,4×10^38 indirizzi. Formato: 8 gruppi da 4 hex separati da ':'. Anche: header semplificato, autoconfigurazione (SLAAC), sicurezza integrata (IPsec nativo)." },
    { fronte: "Well-known ports principali",
      retro: "HTTP=80, HTTPS=443, FTP=21, SSH=22, Telnet=23, SMTP=25, DNS=53, DHCP=67(server)/68(client), POP3=110, IMAP=143." },
    { fronte: "Indirizzo broadcast",
      retro: "Indirizzo con tutti i bit host a 1. Usato per inviare pacchetti a tutti gli host della sottorete. Es. /24 → ultimo ottetto = 255 (es. 192.168.1.255). I router non inoltrano i broadcast tra reti." },
    { fronte: "I 4 livelli del modello TCP/IP",
      retro: "1. Accesso alla rete (Link) — es. Ethernet, Wi-Fi. 2. Internet — IP, ICMP, ARP. 3. Trasporto — TCP, UDP. 4. Applicazione — HTTP, FTP, DNS, SMTP. Corrispondenza con OSI: livelli 1-7." }
  ],

  /* ── ARG 2: Subnetting, VLSM e CIDR ── */
  "subnetting": [
    { fronte: "Cos'è il subnetting?",
      retro: "Tecnica per dividere una rete IP in sottoreti più piccole, usando una subnet mask più lunga della classe naturale. Permette un uso più efficiente degli indirizzi e la separazione logica di reti diverse." },
    { fronte: "Formula per il numero di host",
      retro: "Host disponibili = 2^n - 2, dove n = numero di bit host. Si sottraggono 2 per l'indirizzo di rete (tutti i bit host = 0) e l'indirizzo broadcast (tutti i bit host = 1). Es. /26 → n=6 → 2^6-2 = 62 host." },
    { fronte: "Cos'è VLSM?",
      retro: "Variable Length Subnet Mask: uso di maschere di lunghezza diversa per sottoreti diverse all'interno dello stesso spazio di indirizzamento. Ottimizza l'uso degli indirizzi: reti piccole usano /30 (2 host), reti grandi /24 (254 host)." },
    { fronte: "Cos'è CIDR?",
      retro: "Classless Inter-Domain Routing: sistema di notazione /n che supera le classi fisse (A/B/C). Permette blocchi di qualsiasi dimensione. Usato per summarizzazione delle rotte (route aggregation) su Internet." },
    { fronte: "Wildcard mask",
      retro: "Complemento della subnet mask: 255.255.255.255 - subnet mask. Bit a 0 = controlla (fisso), bit a 1 = ignora. Es. /24 → wildcard 0.0.0.255. Usata nelle ACL Cisco e in OSPF per specificare range di reti." },
    { fronte: "Come calcolare il broadcast",
      retro: "Prendi l'indirizzo di rete e metti tutti i bit host a 1. Oppure: indirizzo di rete + (2^n - 1) dove n = bit host. Es. rete 192.168.1.0/25 → broadcast = 192.168.1.127 (bit host = 7, 2^7-1 = 127)." },
    { fronte: "Differenza subnet mask e wildcard",
      retro: "Subnet mask: 1=rete, 0=host. Usata per identificare la rete. Wildcard: 0=controlla, 1=ignora. Usata nelle ACL per specificare range. Sono complementari: SM + WM = 255.255.255.255." },
    { fronte: "VLSM vs subnetting classico",
      retro: "Subnetting classico: tutte le sottoreti con la stessa maschera (spreco se hanno dimensioni diverse). VLSM: maschere diverse per ogni sottorete → dimensionamento preciso. VLSM richiede protocolli classless (RIPv2, OSPF)." }
  ],

  /* ── ARG 3: NAT, PAT e ICMP ── */
  "nat-icmp": [
    { fronte: "NAT statico vs NAT dinamico",
      retro: "NAT statico: mappatura 1:1 fissa (un IP privato ↔ un IP pubblico). Usato per server interni accessibili dall'esterno. NAT dinamico: pool di IP pubblici assegnati dinamicamente alle connessioni. Più efficiente del statico." },
    { fronte: "Cos'è PAT (NAT Overload)?",
      retro: "Port Address Translation: molti IP privati condividono un singolo IP pubblico, differenziati dalla porta. Es. 192.168.1.5:1234 ↔ 80.1.1.1:50001; 192.168.1.6:4321 ↔ 80.1.1.1:50002. Usato da tutti i router domestici." },
    { fronte: "Tabella NAT",
      retro: "Database che il router NAT mantiene per tracciare le sessioni attive: IP privato + porta privata ↔ IP pubblico + porta pubblica + protocollo. Usata per demultiplexare le risposte verso il client corretto." },
    { fronte: "Vantaggi del NAT",
      retro: "1. Risparmio indirizzi IPv4 (molti host privati → pochi IP pubblici). 2. Sicurezza: IP interni nascosti dall'esterno. 3. Indipendenza dall'ISP: si può cambiare provider senza rinumerare la LAN." },
    { fronte: "Svantaggi del NAT",
      retro: "1. Rompe il modello end-to-end di Internet. 2. Problemi con protocolli che incorporano IP nel payload (SIP, FTP attivo). 3. Difficile ospitare server interni (serve port forwarding). 4. Introduce latenza." },
    { fronte: "Cos'è ICMP?",
      retro: "Internet Control Message Protocol: protocollo di controllo e diagnostica a livello Rete. Non trasporta dati utente ma messaggi di controllo (errori, echo, redirect). Usato da ping e traceroute." },
    { fronte: "Ping e ICMP Echo",
      retro: "ping invia messaggi ICMP Echo Request e attende ICMP Echo Reply. Verifica raggiungibilità dell'host e misura RTT (Round-Trip Time). Output: !!!!!= successo; .....= timeout/irraggiungibile." },
    { fronte: "TTL (Time To Live)",
      retro: "Campo dell'header IP decrementato di 1 da ogni router. Quando arriva a 0, il pacchetto viene scartato e il router invia ICMP Time Exceeded all'origine. Previene loop infiniti. Traceroute sfrutta questo meccanismo." }
  ],

  /* ── ARG 4: Routing: Fondamenti e Algoritmi ── */
  "routing": [
    { fronte: "Tabella di routing",
      retro: "Struttura dati in ogni router con: Destinazione (rete o host), Subnet Mask, Next-Hop (IP prossimo router), Interfaccia di uscita, Metrica (costo del percorso). Il router consulta la tabella per ogni pacchetto ricevuto." },
    { fronte: "Next-hop routing",
      retro: "Ogni router non conosce l'intero percorso verso la destinazione, ma solo il 'prossimo salto'. Instrada il pacchetto al router vicino più appropriato, che a sua volta farà lo stesso. Approccio scalabile e distribuito." },
    { fronte: "Routing statico vs dinamico",
      retro: "Statico: rotte configurate manualmente dall'amministratore. Pro: semplice, zero overhead, prevedibile. Contro: non scala, non si adatta ai guasti. Dinamico: i router si scambiano informazioni e aggiornano automaticamente. Pro: adattivo, scalabile. Contro: overhead, complessità." },
    { fronte: "Algoritmo Bellman-Ford",
      retro: "Distance Vector: ogni nodo conosce solo i vicini diretti. Scambia vettori di distanza con i vicini ogni intervallo. Aggiorna se trova percorso più breve. Accetta pesi negativi. Complessità O(V×E). Usato da RIP. Problema: Count-to-Infinity." },
    { fronte: "Algoritmo Dijkstra",
      retro: "Link-State: ogni nodo ha la mappa completa della rete. Calcola tutti i percorsi minimi dalla sorgente espandendo iterativamente il nodo con distanza minima. Solo pesi positivi. Complessità O(E log V) con heap. Usato da OSPF." },
    { fronte: "Distance Vector vs Link-State",
      retro: "Distance Vector (es. RIP): scambia solo vettori di distanza con vicini → convergenza lenta. Link-State (es. OSPF): ogni router inonda la rete con info sullo stato dei propri link → ogni router ha mappa completa → convergenza rapida." },
    { fronte: "AS (Autonomous System)",
      retro: "Insieme di reti IP sotto il controllo di una singola organizzazione con una politica di routing unificata. Identificato da ASN (Autonomous System Number). Es. ASN di Google = 15169. Gli ISP hanno i propri AS." },
    { fronte: "IGP vs EGP",
      retro: "IGP (Interior Gateway Protocol): routing INTERNO a un AS — ottimizza il percorso tecnico. Es. RIP, OSPF, EIGRP. EGP (Exterior Gateway Protocol): routing TRA AS diversi — considera policy oltre alla metrica. Es. BGP." },
    { fronte: "BGP — cenni",
      retro: "Border Gateway Protocol: il protocollo di routing di Internet. EGP di tipo Path Vector: scambia l'intera lista di AS nel percorso. Decisioni basate su policy (non solo metrica). Usato tra ISP per instradare il traffico globale." },
    { fronte: "Metrica di routing",
      retro: "Valore usato per scegliere il percorso migliore tra più alternative. RIP: hop count (numero di router attraversati). OSPF: costo (inversamente proporzionale alla banda). EIGRP: composito (banda, latenza, affidabilità). BGP: policy." }
  ],

  /* ── ARG 5: RIP ── */
  "rip": [
    { fronte: "Metrica RIP",
      retro: "Hop count: numero di router (salti) attraversati per raggiungere la destinazione. Valore minimo 1 (rete direttamente connessa). Valore massimo 15. Valore 16 = rete irraggiungibile (infinito)." },
    { fronte: "Hop count massimo RIP",
      retro: "15 hop è il massimo raggiungibile. Al 16° salto la rete è considerata irraggiungibile. Questo limita RIP a reti con diametro massimo di 15 router — adatto solo a reti piccole/medie." },
    { fronte: "Count-to-Infinity",
      retro: "Problema RIP: quando un link cade, i router continuano ad annunciare la rotta con metrica crescente (1→2→3…→16) finché non dichiarano la rete irraggiungibile. Causa convergenza lenta e traffico inutile." },
    { fronte: "Split Horizon",
      retro: "Soluzione al Count-to-Infinity: un router non ri-annuncia una rotta verso il router da cui l'ha appresa. Se R1 ha imparato la rete X da R2, R1 non annuncia X a R2. Previene il loop nel caso semplice." },
    { fronte: "Poisoned Reverse",
      retro: "Variante di Split Horizon: invece di omettere la rotta, la ri-annuncia con metrica 16 (irraggiungibile) verso il router da cui è stata appresa. Più esplicito e veloce nella convergenza, ma genera più traffico." },
    { fronte: "Triggered Update",
      retro: "Aggiornamento immediato al cambiamento di topologia, senza aspettare i 30 secondi del timer periodico. Accelera notevolmente la convergenza dopo un guasto." },
    { fronte: "RIPv1 vs RIPv2",
      retro: "RIPv1: classful, broadcast (255.255.255.255), no VLSM, no autenticazione. RIPv2: classless, multicast (224.0.0.9), supporta VLSM/CIDR, autenticazione MD5 opzionale." },
    { fronte: "Multicast 224.0.0.9",
      retro: "Indirizzo multicast usato da RIPv2 per inviare aggiornamenti. Solo i router che eseguono RIPv2 ricevono i messaggi. RIPv1 usava il broadcast 255.255.255.255 che raggiungeva tutti gli host." },
    { fronte: "Timer RIP",
      retro: "Update Timer: 30s (aggiornamenti periodici). Invalid Timer: 180s (rotta invalida se nessun update). Holddown Timer: 180s (attesa prima di accettare nuove info sulla rotta invalida). Flush Timer: 240s (rimozione definitiva)." },
    { fronte: "no auto-summary in RIPv2",
      retro: "Disabilita la summarizzazione automatica alle classi di default. Necessario per supportare VLSM/CIDR correttamente. Senza questo comando, RIPv2 tronca le subnet alla classe naturale dell'indirizzo." }
  ],

  /* ── ARG 6: OSPF e BGP ── */
  "ospf-bgp": [
    { fronte: "OSPF vs RIP",
      retro: "OSPF: Link-State, Dijkstra, costo (banda), aggiornamenti solo al cambio, rapida convergenza, scalabile, supporta VLSM/CIDR, gerarchico (aree). RIP: Distance Vector, Bellman-Ford, hop count, aggiornamenti ogni 30s, convergenza lenta, max 15 hop." },
    { fronte: "LSA (Link State Advertisement)",
      retro: "Pacchetto inviato da ogni router OSPF a tutti gli altri con le informazioni sullo stato dei propri link (vicini, costo delle interfacce). Costruisce il LSDB su tutti i router." },
    { fronte: "LSDB (Link State Database)",
      retro: "Database costruito da ogni router OSPF raccogliendo tutti i LSA. Rappresenta la mappa completa della topologia di rete. Tutti i router OSPF nella stessa area hanno LSDB identico." },
    { fronte: "Costo OSPF",
      retro: "Metrica di OSPF = banda di riferimento / banda interfaccia. Default: 100 Mbps / banda. FastEthernet (100Mbps) = 1, Ethernet (10Mbps) = 10, Serial (1.544Mbps) ≈ 64. Il percorso con costo totale minore è il migliore." },
    { fronte: "Area 0 in OSPF",
      retro: "L'Area 0 (backbone) è il nucleo di OSPF. Tutte le altre aree OSPF devono connettersi all'Area 0. Struttura gerarchica: Area 0 + aree satellite → riduce dimensione LSDB e traffico di aggiornamento." },
    { fronte: "BGP (Border Gateway Protocol)",
      retro: "Protocollo EGP Path Vector usato tra AS diversi su Internet. Scambia interi percorsi (lista AS traversati). Decisioni basate su policy (non solo metrica tecnica). Ogni ISP usa BGP per scambiare tabelle di routing globali." },
    { fronte: "Path Vector",
      retro: "Meccanismo di BGP: ogni annuncio contiene la lista completa degli AS attraversati (AS_PATH). Permette di rilevare e prevenire loop (se un AS vede il proprio ASN nel path, scarta l'annuncio). Permette implementare policy di routing." },
    { fronte: "IGP vs EGP",
      retro: "IGP: routing interno a un AS (RIP, OSPF, EIGRP) — ottimizza il percorso tecnico. EGP: routing tra AS diversi (BGP) — considera accordi commerciali, policy aziendali, geopolitica oltre alla metrica. BGP è l'EGP di Internet." }
  ],

  /* ── ARG 7: Crittografia Principi e Simmetrica ── */
  "crittografia": [
    { fronte: "Crittografia simmetrica vs asimmetrica",
      retro: "Simmetrica: stessa chiave per cifrare e decifrare. Veloce, efficiente per grandi dati. Problema: distribuzione sicura della chiave. Es. AES. Asimmetrica: coppia chiave pubblica/privata. Lenta, ma risolve la distribuzione. Es. RSA." },
    { fronte: "DES (Data Encryption Standard)",
      retro: "Chiave 56 bit, blocchi 64 bit. OBSOLETO: vulnerabile a brute force (violato nel 1999 in <24h). Non usare per applicazioni di sicurezza. Sostituito da 3DES e poi da AES." },
    { fronte: "AES (Advanced Encryption Standard)",
      retro: "Standard attuale per crittografia simmetrica (dal 2001). Chiavi: 128, 192 o 256 bit. Blocchi da 128 bit. Molto sicuro ed efficiente. Usato in WPA2, TLS, IPsec, FileVault, BitLocker." },
    { fronte: "RSA",
      retro: "Algoritmo asimmetrico più diffuso. Basato sulla difficoltà di fattorizzare grandi numeri. Chiavi: 2048 o 4096 bit. Lento (1000x più di AES). Usato per scambio chiavi, firma digitale e certificati. Non per cifrare grandi dati." },
    { fronte: "Chiave pubblica e chiave privata",
      retro: "Due chiavi matematicamente correlate: pubblica (distribuita liberamente) e privata (segreta). Ciò che viene cifrato con la pubblica si decifra solo con la privata e viceversa. Mai trasmettere la chiave privata." },
    { fronte: "Sistema ibrido di crittografia",
      retro: "Fase 1 (asimmetrica): scambio sicuro della chiave di sessione usando RSA/DH. Fase 2 (simmetrica): cifratura dei dati con la chiave di sessione (AES). Usato in SSL/TLS, IPsec. Combina sicurezza della asimmetrica con velocità della simmetrica." },
    { fronte: "Problema della distribuzione delle chiavi",
      retro: "Con crittografia simmetrica: come comunicare la chiave segreta a un'altra parte in modo sicuro senza che un intercettatore la catturi? Soluzione: crittografia asimmetrica (RSA) o Diffie-Hellman per lo scambio iniziale." },
    { fronte: "Plaintext e Ciphertext",
      retro: "Plaintext: dati originali in chiaro. Ciphertext: dati cifrati, incomprensibili senza la chiave. Processo: plaintext → [cifratura + chiave] → ciphertext → [decifratura + chiave] → plaintext." },
    { fronte: "3DES",
      retro: "Triple DES: applica DES tre volte (Cifratura-Decifratura-Cifratura) con 3 chiavi diverse. Chiave effettiva: 112 o 168 bit. Più sicuro di DES ma molto più lento di AES. Considerato legacy, deprecato." },
    { fronte: "Perché DES è obsoleto",
      retro: "Chiave di soli 56 bit → spazio delle chiavi: 2^56 ≈ 72 trilioni. Nel 1998, il progetto EFF costruì 'Deep Crack' che violò DES in 56 ore per $250.000. Nel 1999, violato in 22 ore. Brute force moderno: secondi." }
  ],

  /* ── ARG 8: Diffie-Hellman, Hash, MAC, Firma Digitale ── */
  "diffie-hellman": [
    { fronte: "Diffie-Hellman",
      retro: "Algoritmo per lo scambio sicuro di chiavi su canale pubblico. Le due parti derivano la stessa chiave segreta senza trasmetterla mai. Basato sulla difficoltà del logaritmo discreto. Non è cifratura — è solo scambio di chiavi." },
    { fronte: "Hash crittografico",
      retro: "Funzione che trasforma input di qualsiasi dimensione in output di lunghezza fissa (digest). Proprietà: deterministica, a senso unico, effetto valanga, resistenza alle collisioni. Usato per integrità, password, firma digitale." },
    { fronte: "MD5 vs SHA-256",
      retro: "MD5: 128 bit — veloce ma vulnerabile a collisioni (deprecato per sicurezza). SHA-1: 160 bit — deprecato. SHA-256 (SHA-2): 256 bit — standard attuale sicuro. SHA-512 per applicazioni ad alta sicurezza." },
    { fronte: "MAC (Message Authentication Code)",
      retro: "Codice calcolato sul messaggio usando una chiave segreta condivisa. Garantisce: integrità (il messaggio non è stato alterato) e autenticazione (proviene da chi ha la chiave). A differenza dell'hash, richiede una chiave." },
    { fronte: "HMAC",
      retro: "Hash-based MAC: combina una chiave segreta con una funzione hash standard. HMAC-SHA256 = SHA-256 + chiave. Resistente agli attacchi extension length. Usato in SSL/TLS per ogni blocco dati e in IPsec." },
    { fronte: "Firma digitale — step by step",
      retro: "1. Mittente calcola hash(messaggio). 2. Cifra hash con chiave PRIVATA → firma. 3. Invia messaggio + firma. 4. Destinatario decifra firma con chiave PUBBLICA del mittente → hash originale. 5. Confronta con hash(messaggio ricevuto). Uguali = firma valida." },
    { fronte: "Non ripudio",
      retro: "Proprietà garantita dalla firma digitale: il mittente non può negare di aver firmato/inviato il messaggio. Solo chi possiede la chiave privata può creare una firma valida verificabile con la chiave pubblica." },
    { fronte: "MFA (Multi-Factor Authentication)",
      retro: "Autenticazione con 2+ fattori di categorie diverse: Knowledge (sai: password/PIN), Possession (hai: token/smartphone/smart card), Inherence (sei: biometria). Protezione aggiuntiva se la password è compromessa." },
    { fronte: "TOTP",
      retro: "Time-based One-Time Password (RFC 6238): codice OTP a 6 cifre derivato da chiave segreta + timestamp. Cambia ogni 30 secondi. Usato da Google Authenticator, Microsoft Authenticator. Protegge da replay attack." },
    { fronte: "U2F / FIDO2",
      retro: "Chiave hardware fisica (es. YubiKey) come secondo fattore. Il dispositivo firma una challenge del server con la propria chiave privata. Resistente al phishing (lega l'autenticazione al dominio specifico). Più sicuro di TOTP." },
    { fronte: "Autenticazione forte vs debole",
      retro: "Debole: singolo fattore (solo password). Forte (MFA): almeno 2 fattori di categorie diverse. Un attaccante deve compromettere più categorie. Esempio: password (knowledge) + smartphone (possession)." },
    { fronte: "Effetto valanga (Avalanche Effect)",
      retro: "Proprietà fondamentale delle funzioni hash: cambiare anche un solo bit dell'input produce un output completamente diverso (cambia ~50% dei bit dell'hash). Garantisce che hash simili non rivelino informazioni sull'input." }
  ],

  /* ── ARG 9: Certificati Digitali e PKI ── */
  "pki": [
    { fronte: "Certificato digitale",
      retro: "Documento elettronico che associa una chiave pubblica all'identità del proprietario. Firmato digitalmente da una CA. Contiene: identità titolare, chiave pubblica, periodo di validità, identità e firma della CA." },
    { fronte: "CA (Certification Authority)",
      retro: "Ente terzo di fiducia che emette, firma e revoca certificati digitali. Firma il certificato con la propria chiave privata. La sua firma garantisce l'autenticità dell'associazione chiave pubblica↔identità." },
    { fronte: "PKI (Public Key Infrastructure)",
      retro: "Infrastruttura completa per la gestione dei certificati: CA, Registration Authority, CRL, politiche di sicurezza, standard (X.509). Permette comunicazioni sicure su scala globale (es. HTTPS su Internet)." },
    { fronte: "Root CA",
      retro: "CA al vertice della gerarchia PKI. Il suo certificato è auto-firmato. Pre-installata nel trust store di browser e OS. Se una Root CA è compromessa, tutta la PKI da essa derivata è compromessa." },
    { fronte: "Come il browser verifica un certificato SSL",
      retro: "1. Data: controlla periodo di validità. 2. CA fidata: verifica che la CA sia nel trust store del browser. 3. Firma: decifra la firma della CA e confronta con hash del certificato. 4. Dominio: verifica CN/SAN corrispondente all'URL." },
    { fronte: "CRL (Certificate Revocation List)",
      retro: "Lista pubblicata dalla CA dei certificati revocati prima della scadenza (es. chiave privata compromessa). Il client la scarica periodicamente. Alternativa: OCSP (Online Certificate Status Protocol) — query in tempo reale." },
    { fronte: "X.509",
      retro: "Standard ITU-T per i certificati a chiave pubblica. Definisce la struttura del certificato: versione, numero seriale, algoritmo firma, identità emittente (CA), periodo validità, identità soggetto, chiave pubblica, firma CA." },
    { fronte: "DV vs OV vs EV",
      retro: "DV (Domain Validation): verifica solo il controllo del dominio. OV (Organization Validation): verifica l'identità dell'organizzazione. EV (Extended Validation): verifica approfondita, mostra nome azienda nel browser — usato da banche." }
  ],

  /* ── ARG 10: SSL/TLS ── */
  "ssl-tls": [
    { fronte: "SSL vs TLS",
      retro: "SSL (Secure Sockets Layer): versioni 2.0 e 3.0 — deprecate per vulnerabilità. TLS (Transport Layer Security): successore sicuro di SSL. Versioni: 1.0 (deprecata), 1.1 (deprecata), 1.2 (ancora in uso), 1.3 (standard attuale)." },
    { fronte: "HTTPS",
      retro: "HTTP over SSL/TLS. Porta 443 invece di 80. Garantisce confidenzialità (cifratura), autenticazione (certificati), integrità (MAC). Il lucchetto verde nel browser indica connessione HTTPS con certificato valido." },
    { fronte: "Cipher Suite",
      retro: "Insieme di algoritmi concordati in SSL/TLS: scambio chiavi (RSA, DHE, ECDHE) + cifratura simmetrica (AES-256-GCM, ChaCha20) + hash per MAC (SHA-256, SHA-384). Negoziata durante l'handshake." },
    { fronte: "SSL Handshake — passi",
      retro: "1.Client Hello (cipher suites + nonce C). 2.Server Hello (scelta cipher + nonce S). 3.Certificato. 4.Server Hello Done. 5.Verifica certificato. 6.Pre-master secret (cifrato con chiave pubblica server). 7.Master secret da entrambi. 8.4 chiavi derivate. 9.Finished." },
    { fronte: "Pre-master secret",
      retro: "Bytes casuali generati dal client, cifrati con la chiave pubblica del server (dal certificato) e inviati. Solo il server può decifrarli con la propria chiave privata. Base per il calcolo del master secret." },
    { fronte: "Master secret",
      retro: "Chiave segreta condivisa calcolata da entrambi: f(pre-master secret + nonce client + nonce server). Non viene mai trasmesso. Da esso si derivano le 4 chiavi di sessione." },
    { fronte: "Le 4 chiavi SSL/TLS",
      retro: "Dal master secret si derivano: 1. Chiave cifratura Client→Server. 2. Chiave cifratura Server→Client. 3. Chiave MAC Client→Server. 4. Chiave MAC Server→Client. Separazione per direzione aumenta la sicurezza." },
    { fronte: "SSL Record Layer",
      retro: "Livello inferiore SSL: riceve dati dall'applicazione → frammenta in blocchi → comprime (opzionale) → aggiunge MAC → cifra → aggiunge header SSL → invia via TCP." },
    { fronte: "MAC in SSL",
      retro: "Ogni blocco dati include un MAC calcolato con la chiave MAC di sessione. Il ricevente ricalcola il MAC: se non corrisponde, il dato è stato alterato (integrità violata) → connessione chiusa." },
    { fronte: "Sistema ibrido in SSL",
      retro: "SSL usa asimmetrica (RSA) solo per lo scambio del pre-master secret durante l'handshake. Poi usa simmetrica (AES) per cifrare tutti i dati della sessione. Combina sicurezza dello scambio chiavi con velocità della cifratura." },
    { fronte: "TLS 1.3",
      retro: "Standard attuale (2018). Handshake più veloce (1-RTT invece di 2-RTT di TLS 1.2). Rimosse cipher suite deboli (RSA key exchange, RC4, MD5). Perfect Forward Secrecy obbligatoria. Più sicuro e più veloce di TLS 1.2." },
    { fronte: "Nonce in SSL/TLS",
      retro: "Numero casuale usato una sola volta (Number used ONCE). Client e server inviano un nonce nel hello. Inclusi nel calcolo del master secret, garantiscono che ogni sessione abbia chiavi uniche e prevengono replay attack." }
  ],

  /* ── ARG 11: VPN ── */
  "vpn": [
    { fronte: "VPN (Virtual Private Network)",
      retro: "Crea un tunnel crittografato su reti pubbliche (Internet), permettendo comunicazioni private come se si fosse su una rete dedicata. Garantisce: riservatezza, integrità, autenticazione, accesso remoto sicuro." },
    { fronte: "Tunneling",
      retro: "Incapsulamento del pacchetto originale (con IP privato) in un nuovo pacchetto (con IP pubblico) che viaggia sulla rete pubblica. Il gateway VPN di destinazione rimuove l'incapsulamento e decifra." },
    { fronte: "Remote-Access VPN",
      retro: "Un singolo utente si connette alla rete aziendale da remoto (casa, hotel). Il client VPN sul dispositivo stabilisce il tunnel verso il concentratore VPN aziendale. Usato per telelavoro." },
    { fronte: "Site-to-Site VPN",
      retro: "Collega permanentemente due sedi aziendali distinte via Internet. I gateway VPN di entrambe le sedi stabiliscono il tunnel. Tutto il traffico inter-sede passa nel tunnel. Sostituisce le linee WAN dedicate (più economica)." },
    { fronte: "IPsec VPN",
      retro: "Protocollo di sicurezza a Layer 3. Trasparente alle applicazioni. Alta sicurezza. Standard per VPN site-to-site aziendali. Usa AH o ESP + IKE per negoziare le SA. Complesso da configurare." },
    { fronte: "SSL/TLS VPN",
      retro: "Opera a livello applicativo. Più facile da usare (funziona via browser HTTPS). Ideale per remote-access: non richiede client VPN complesso. Attraversa facilmente i firewall (usa porta 443). Meno trasparente di IPsec." },
    { fronte: "OpenVPN",
      retro: "VPN open source basata su SSL/TLS. Flessibile: supporta TCP e UDP, qualsiasi porta. Cross-platform. Usata per VPN personali e aziendali. Configurazione via file .ovpn." },
    { fronte: "WireGuard",
      retro: "Protocollo VPN moderno (2020), open source. Codice base minimo (~4000 righe). Prestazioni elevate. Crittografia moderna (ChaCha20, Curve25519). Semplice da configurare. Disponibile nativamente nel kernel Linux." },
    { fronte: "Autenticazione nella VPN",
      retro: "Chi può connettersi? Metodi: PSK (pre-shared key), certificati digitali (X.509), RADIUS/TACACS+ (username+password), MFA (password + token OTP). I certificati offrono la massima sicurezza scalabile." },
    { fronte: "Quando usare VPN",
      retro: "1. Telelavoro (accesso remoto alla rete aziendale). 2. Connettere più sedi aziendali (site-to-site). 3. Proteggere dati su Wi-Fi pubblico. 4. Aggirare censure geografiche. 5. Comunicazioni sicure con partner esterni." }
  ],

  /* ── ARG 12: IPsec ── */
  "ipsec": [
    { fronte: "IPsec — cos'è",
      retro: "Framework di protocolli a Layer 3 che protegge qualsiasi comunicazione IP in modo trasparente alle applicazioni. Garantisce: Riservatezza (cifratura), Integrità (hash), Autenticazione, Anti-Replay." },
    { fronte: "SA (Security Association)",
      retro: "Insieme di parametri e chiavi per proteggere il traffico in UNA direzione. Identificata da: SPI + IP destinazione + protocollo. Per comunicazione bidirezionale servono 2 SA. Memorizzata nel SAD." },
    { fronte: "IKE (Internet Key Exchange)",
      retro: "Protocollo per negoziare automaticamente le SA. Porta UDP 500 (4500 con NAT). Sostituisce la configurazione manuale delle SA. IKEv1 (legacy), IKEv2 (più efficiente, moderno)." },
    { fronte: "IKE Fase 1",
      retro: "Crea il tunnel ISAKMP sicuro per le negoziazioni. Negozia parametri (hash, DH, cifratura, lifetime) → scambio DH → autenticazione (PSK o certificato). Main Mode (6 msg, sicuro) o Aggressive Mode (3 msg, veloce)." },
    { fronte: "IKE Fase 2 (Quick Mode)",
      retro: "Dentro il tunnel di Fase 1: negozia le SA per il traffico dati. 3 messaggi. Parametri: protocollo (AH/ESP), modalità (trasporto/tunnel), algoritmi, lifetime, PFS (se richiesto)." },
    { fronte: "Main Mode vs Aggressive Mode",
      retro: "Main Mode: 6 messaggi, identità protetta (cifrata), più sicuro — usato per site-to-site con IP fisso. Aggressive Mode: 3 messaggi, identità in chiaro, più veloce — usato per remote-access con IP dinamico." },
    { fronte: "AH vs ESP",
      retro: "AH (IP 51): autenticazione (include header IP), NO cifratura, problemi con NAT. ESP (IP 50): autenticazione + cifratura (solo payload), compatibile con NAT (via NAT-T). ESP è lo standard nelle VPN moderne." },
    { fronte: "Modalità Trasporto vs Tunnel",
      retro: "Trasporto: protegge solo payload, header IP originale visibile, host-to-host. Tunnel: nuovo header IP aggiunto, IP originali nascosti, intera comunicazione protetta — VPN site-to-site tra gateway." },
    { fronte: "PFS (Perfect Forward Secrecy)",
      retro: "Esegue un nuovo scambio Diffie-Hellman in IKE Fase 2 per ogni SA, generando chiavi indipendenti dalla Fase 1. Se una chiave di sessione è compromessa, non espone né le sessioni passate né le future." },
    { fronte: "Anti-Replay",
      retro: "Protezione contro attacchi replay: IPsec numera ogni pacchetto con un sequence number. Il ricevente tiene una finestra dei sequence number accettati. Pacchetti duplicati o troppo vecchi vengono scartati." },
    { fronte: "Quick Mode",
      retro: "La fase di negoziazione delle SA per il traffico reale in IKE. 3 messaggi. Avviene dentro il tunnel sicuro creato da IKE Fase 1. Produce una o più coppie di SA (una per direzione) con le chiavi per ESP/AH." },
    { fronte: "SAD (Security Association Database)",
      retro: "Database dove IPsec memorizza tutte le SA attive: SPI, algoritmi, chiavi, lifetime rimanente. Il kernel consulta il SAD per ogni pacchetto da proteggere o da verificare." },
    { fronte: "NAT-T (NAT Traversal)",
      retro: "Soluzione per far funzionare IPsec/ESP attraverso dispositivi NAT. Incapsula ESP dentro UDP porta 4500. IKE usa UDP 500 normalmente, passa a 4500 in presenza di NAT. Supportato nativamente da IKEv2." },
    { fronte: "Diffie-Hellman in IPsec",
      retro: "Usato in IKE Fase 1 per generare il materiale crittografico senza trasmetterlo. Gruppo DH 1 (768 bit, debole), Gruppo 2 (1024 bit), Gruppo 14 (2048 bit, raccomandato), Gruppo 19/20 (ECDH, moderni)." }
  ],

  /* ── ARG 13: Firewall e Architetture ── */
  "firewall": [
    { fronte: "DMZ (Demilitarized Zone)",
      retro: "Zona di rete intermedia tra Internet e LAN interna. Ospita server pubblici (web, mail, DNS). La compromissione di un server DMZ non deve propagarsi alla LAN interna. Creata con due firewall o un firewall multi-interfaccia." },
    { fronte: "Default-Deny vs Default-Allow",
      retro: "Default-Deny: tutto vietato tranne il permesso esplicitamente — più sicuro, principio del minimo privilegio. Default-Allow: tutto permesso tranne il vietato — più comodo ma pericoloso (nuove minacce non sono bloccate)." },
    { fronte: "Packet Filter",
      retro: "Firewall L3: analizza header IP e TCP/UDP (indirizzi IP, porte, protocollo). Velocissimo e semplice. Stateless: non traccia connessioni. Bypassabile con IP spoofing e pacchetti frammentati." },
    { fronte: "SPI (Stateful Packet Inspection)",
      retro: "Firewall L3-L4: mantiene state table con connessioni attive (IP, porte, seq number, flag). Controlla che ogni pacchetto appartenga a una connessione legittima. Difficile iniettare pacchetti falsi." },
    { fronte: "Proxy / Application Gateway",
      retro: "Firewall L7: crea due connessioni separate (client→proxy, proxy→server). Analizza contenuto applicativo, comprende protocolli (HTTP, FTP). Massima sicurezza ma lento. Richiede un proxy per ogni protocollo." },
    { fronte: "NGFW (Next-Generation Firewall)",
      retro: "Combina: SPI + DPI (Deep Packet Inspection) + IDS/IPS integrato + App-ID (identifica applicazioni) + SSL inspection (decifra e analizza HTTPS) + policy per utente (integrazione AD). Costoso e complesso." },
    { fronte: "DPI (Deep Packet Inspection)",
      retro: "Analisi del contenuto del pacchetto fino al payload applicativo. Rileva malware, P2P, violazioni di policy nel traffico cifrato (SSL inspection). Alto overhead computazionale." },
    { fronte: "Bastion Host",
      retro: "Server esposto rinforzato: OS hardened (servizi minimi), MFA obbligatoria, logging completo di tutte le attività, aggiornamenti continuativi. Punto di contatto controllato con reti non fidate (es. jump host per SSH)." },
    { fronte: "Screened Subnet (DMZ con 2 FW)",
      retro: "Internet → FW esterno → DMZ → FW interno → LAN. Architettura più sicura: FW esterno protegge DMZ da Internet, FW interno protegge LAN dalla DMZ. Anche se la DMZ è compromessa, la LAN è protetta." },
    { fronte: "Limiti del firewall",
      retro: "Non filtra traffico che non lo attraversa. Non protegge da insider (attacchi interni). Non ispeziona traffico cifrato (senza SSL inspection). Configurazione errata = falso senso di sicurezza. Non sostituisce antivirus e IDS/IPS." },
    { fronte: "State Table (SPI)",
      retro: "Tabella delle connessioni attive tracciata dal firewall SPI. Per ogni connessione: IP/porta sorgente e destinazione, protocollo, stato TCP (SYN/ESTABLISHED/FIN), sequence number. Valida i pacchetti di risposta." },
    { fronte: "Circuit-Level Gateway",
      retro: "Firewall L5 (sessione): verifica l'handshake e lo stato delle connessioni TCP/UDP. Non ispeziona il payload. Nasconde la struttura della rete interna. Bassa latenza. Esempio: SOCKS proxy." }
  ],

  /* ── ARG 14: ACL ── */
  "acl": [
    { fronte: "ACL (Access Control List)",
      retro: "Lista di regole (ACE — Access Control Entry) applicata alle interfacce del router per controllare il traffico in ingresso (inbound) o uscita (outbound). Funzioni: sicurezza, QoS, ottimizzazione traffico." },
    { fronte: "ACE (Access Control Entry)",
      retro: "Singola regola in un'ACL: contiene condizione (IP, porta, protocollo) e azione (permit o deny). Le ACE vengono processate in ordine, top-down. Alla prima corrispondenza si applica l'azione e si ferma." },
    { fronte: "Deny implicito",
      retro: "Alla fine di ogni ACL Cisco c'è implicitamente 'deny any': tutto il traffico non esplicitamente permesso viene bloccato. Dimenticare un 'permit any' finale può bloccare traffico legittimo." },
    { fronte: "ACL Standard vs Estesa",
      retro: "Standard (1-99, 1300-1999): filtra solo IP sorgente — posizionare vicino alla DESTINAZIONE. Estesa (100-199, 2000-2699): filtra sorgente + destinazione + protocollo + porta — posizionare vicino alla SORGENTE." },
    { fronte: "Posizionamento ACL",
      retro: "Standard: vicino alla destinazione (filtra solo sorgente, non blocca altri traffici legittimi). Estesa: vicino alla sorgente (blocca il prima possibile, risparmia risorse di rete). Regola fondamentale del design ACL." },
    { fronte: "Wildcard Mask nelle ACL",
      retro: "Bit a 0 = controlla (il bit deve corrispondere), bit a 1 = ignora. 0.0.0.255 per /24 (ultimi 8 bit liberi). 'any' = 0.0.0.0 255.255.255.255. 'host 1.2.3.4' = 1.2.3.4 0.0.0.0." },
    { fronte: "Inbound vs Outbound ACL",
      retro: "Inbound: il pacchetto viene filtrato PRIMA del routing → più efficiente (pacchetti bloccati non consumano risorse di routing). Outbound: filtrato DOPO il routing → il router ha già scelto l'interfaccia di uscita." },
    { fronte: "Ordine delle regole ACL",
      retro: "Le regole più specifiche devono venire PRIMA di quelle generali. Se una regola generale è prima, cattura tutto e le regole specifiche successive non vengono mai eseguite. Critico per il corretto funzionamento delle ACL." },
    { fronte: "La keyword 'any' nelle ACL",
      retro: "Abbreviazione per 0.0.0.0 255.255.255.255 = qualsiasi indirizzo IP. Usato tipicamente nell'ultima regola come 'permit ip any any' o 'deny ip any any' (implicito)." },
    { fronte: "La keyword 'host' nelle ACL",
      retro: "Abbreviazione per [IP] 0.0.0.0 = esattamente quell'IP (wildcard tutti 0). 'access-list 10 deny host 192.168.1.5' blocca solo quell'IP specifico." },
    { fronte: "Sintassi ACL Standard Cisco",
      retro: "access-list [1-99] {permit|deny} {host IP | IP wildcard | any}\nEsempio: access-list 10 deny host 192.168.1.100\naccess-list 10 permit any" },
    { fronte: "show ip access-lists",
      retro: "Comando Cisco che mostra le ACL configurate con i contatori per ogni ACE (quanti pacchetti hanno corrisposto). Utile per verificare che le ACL funzionino come previsto e per il troubleshooting." }
  ],

  /* ── ARG 15: IDS, IPS e Sicurezza Perimetrale ── */
  "ids-ips": [
    { fronte: "IDS (Intrusion Detection System)",
      retro: "Sistema PASSIVO di rilevamento intrusioni. Analizza traffico o log, rileva comportamenti sospetti e genera allarmi. NON blocca il traffico. L'intervento umano è necessario. Nessun impatto sulle prestazioni di rete." },
    { fronte: "IPS (Intrusion Prevention System)",
      retro: "Sistema ATTIVO di prevenzione intrusioni. Posizionato inline nel percorso del traffico. Rileva E blocca automaticamente il traffico malevolo (drop pacchetti, TCP reset, blocco IP). Lieve impatto su prestazioni." },
    { fronte: "HIDS (Host-based IDS)",
      retro: "Installato su un singolo host. Analizza log di sistema, integrità file critici, processi, traffico locale già decifrato. Vede attività locali invisibili al NIDS. Scalabilità limitata (un agente per host)." },
    { fronte: "NIDS (Network-based IDS)",
      retro: "Analizza il traffico di rete in tempo reale. Posizionato via port mirroring (SPAN) o TAP. Visibilità sull'intera rete. Non vede il traffico cifrato. Non carica gli endpoint." },
    { fronte: "Anomaly Detection",
      retro: "Definisce una baseline del comportamento normale e rileva deviazioni. Pro: può rilevare attacchi zero-day non catalogati. Contro: molti falsi positivi (comportamenti legittimi inusuali segnalati)." },
    { fronte: "Misuse Detection (Signature-based)",
      retro: "Confronta traffico con database di firme di attacchi noti. Pro: preciso, basso tasso di falsi positivi. Contro: non rileva zero-day, richiede aggiornamento continuo del database. Come un antivirus per la rete." },
    { fronte: "Passivo vs Attivo (IDS vs IPS)",
      retro: "IDS: passivo (fuori dal percorso traffico, copia via SPAN), rileva e segnala. Falso positivo = allarme indesiderato ma traffico scorre. IPS: attivo (inline), blocca. Falso positivo = traffico legittimo bloccato." },
    { fronte: "AAA",
      retro: "Authentication: verifica identità ('chi sei?'). Authorization: definisce permessi ('cosa puoi fare?'). Accounting: registra attività ('cosa hai fatto?'). Framework per il controllo degli accessi, implementato con RADIUS/TACACS+." },
    { fronte: "NAS (Network Access Server)",
      retro: "Intermediario tra il client e il server AAA. Il client invia credenziali al NAS (es. AP Wi-Fi, switch 802.1X, concentratore VPN), che le inoltra al server RADIUS/TACACS+ per la verifica." },
    { fronte: "RADIUS",
      retro: "Remote Authentication Dial-In User Service. UDP porte 1812 (auth) e 1813 (accounting). Cifra solo la password (resto in chiaro). Standard aperto, usato per Wi-Fi enterprise (WPA2-Enterprise), VPN, 802.1X." },
    { fronte: "TACACS+",
      retro: "Protocollo AAA alternativo (proprietario Cisco). TCP porta 49. Cifra l'intero payload (più sicuro di RADIUS). Separa completamente le 3 funzioni AAA. Usato principalmente per accesso amministrativo ai dispositivi Cisco." },
    { fronte: "MFA — 3 categorie",
      retro: "Knowledge: qualcosa che SAI (password, PIN, risposta segreta). Possession: qualcosa che HAI (token hardware, smartphone, smart card). Inherence: qualcosa che SEI (biometria: impronta, volto, iride)." },
    { fronte: "TOTP vs SMS OTP",
      retro: "TOTP: codice generato localmente dall'app (Google Auth) senza connessione rete. Più sicuro. SMS OTP: codice inviato via SMS. Vulnerabile a SIM swapping (attaccante trasferisce il numero su una SIM diversa)." },
    { fronte: "U2F / FIDO2",
      retro: "Standard per chiavi hardware (es. YubiKey). Resistente al phishing: l'autenticazione è legata al dominio specifico (non può essere intercettata su un sito falso). Fattore di possesso più sicuro disponibile." }
  ],

  /* ── ARG 16: Cloud, Virtualizzazione, Active Directory ── */
  "cloud": [
    { fronte: "IaaS, PaaS, SaaS",
      retro: "IaaS: VM + storage + rete (es. AWS EC2, Azure VM). PaaS: piattaforma di sviluppo gestita (es. Heroku, Google App Engine). SaaS: applicazioni complete via browser (es. Office 365, Gmail, Salesforce)." },
    { fronte: "Hypervisor Type 1 vs Type 2",
      retro: "Type 1 (Bare Metal): direttamente sull'hardware, senza OS host. Massime prestazioni. Es. VMware ESXi, Hyper-V, Proxmox. Usato nei datacenter. Type 2 (Hosted): sopra un OS host (Windows/Linux). Es. VirtualBox, VMware Workstation. Per uso personale/testing." },
    { fronte: "RTO (Recovery Time Objective)",
      retro: "Tempo massimo tollerabile per ripristinare il sistema dopo un disastro. Es. RTO=4h: entro 4 ore dal guasto, il sistema deve essere operativo. Determina l'investimento necessario per ridondanza e disaster recovery." },
    { fronte: "RPO (Recovery Point Objective)",
      retro: "Quantità massima di dati persi accettabile, espressa in tempo. Es. RPO=1h: si può perdere al massimo 1 ora di dati → backup almeno ogni ora. Più basso il RPO, più frequenti e costosi i backup." },
    { fronte: "Regola 3-2-1 del backup",
      retro: "3 copie totali dei dati, su 2 supporti diversi (es. disco locale + NAS), con 1 copia fuori sede (cloud o sede secondaria). Protegge da: guasto hardware, disastri fisici (incendio/alluvione), ransomware." },
    { fronte: "Backup Full vs Incrementale vs Differenziale",
      retro: "Full: tutti i dati ogni volta — ripristino semplice, lento e pesante. Incrementale: solo modifiche dall'ultimo backup (qualsiasi tipo) — veloce, ripristino complesso (full+tutti inc). Differenziale: modifiche dall'ultimo full — compromesso." },
    { fronte: "Clustering HA",
      retro: "Alta Disponibilità: più nodi fisici che appaiono come un'unica unità logica. Se un nodo cade → failover automatico. Active-Passive: un attivo + uno standby. Active-Active: tutti attivi + load balancing." },
    { fronte: "Active Directory (AD)",
      retro: "Servizio Microsoft per gestione centralizzata di utenti, computer, policy. Components: Domain Controller (DC), Domain, OU, GPO, Forest. Protocolli: Kerberos (autenticazione), LDAP (query), NTLM (legacy)." },
    { fronte: "DC (Domain Controller)",
      retro: "Server che ospita il database Active Directory. Gestisce: autenticazione degli utenti (Kerberos/NTLM), autorizzazione, replica del database AD con altri DC. Ogni dominio deve avere almeno un DC." },
    { fronte: "GPO (Group Policy Object)",
      retro: "Regole applicate automaticamente ad utenti e computer del dominio AD. Es.: blocco USB, politiche password, screensaver, software da installare, configurazione firewall Windows, reindirizzamento cartelle." },
    { fronte: "SSO (Single Sign-On)",
      retro: "Un'unica autenticazione (login) per accedere a tutte le risorse autorizzate nella rete (email, fileserver, applicazioni). Implementato da Active Directory via Kerberos ticket. Utente non deve re-autenticarsi per ogni risorsa." },
    { fronte: "LDAP",
      retro: "Lightweight Directory Access Protocol: protocollo per interrogare directory di rete come Active Directory. Usato da applicazioni per verificare credenziali e recuperare informazioni utente. Porta 389 (389 LDAP, 636 LDAPS)." },
    { fronte: "Azure AD",
      retro: "Versione cloud di Active Directory. Gestisce identità per applicazioni cloud e smart working. Usa OAuth 2.0 e SAML invece di Kerberos. Non è una replica di AD on-premise — è un servizio cloud-native." },
    { fronte: "Clustering ≠ Backup",
      retro: "Un cluster distribuisce il servizio su più nodi, ma tutti accedono agli stessi dati. Un ransomware cifra i dati su tutti i nodi simultaneamente. Il backup è separato, non modificabile, e indispensabile anche con clustering." }
  ],

  /* ── ARG 17: Laboratorio Packet Tracer ── */
  "packet-tracer": [
    { fronte: "Modalità IOS Cisco",
      retro: "User EXEC (>) → enable → Privileged EXEC (#) → configure terminal → Global Config (config)# → interface fa0/0 → Interface Config (config-if)#. Per uscire: exit o Ctrl+Z per tornare direttamente al privileged." },
    { fronte: "Comandi show principali",
      retro: "show ip route: tabella routing. show ip protocols: protocolli attivi. show ip interfaces brief: riepilogo interfacce. show ip access-lists: ACL. show ip nat translations: tabella NAT. show interfaces: dettaglio interfacce." },
    { fronte: "Configurare un'interfaccia IOS",
      retro: "(config)# interface fastEthernet 0/0\n(config-if)# ip address 192.168.1.1 255.255.255.0\n(config-if)# no shutdown\n(config-if)# exit\nVerifica: show interfaces fa0/0 (deve essere 'up/up')" },
    { fronte: "Configurare RIP v2",
      retro: "(config)# router rip\n(config-router)# version 2\n(config-router)# network 192.168.1.0\n(config-router)# no auto-summary\nVerifica: show ip protocols — show ip rip database" },
    { fronte: "ACL su interfaccia",
      retro: "(config)# interface fa0/1\n(config-if)# ip access-group 10 out\nDirezione: 'in' = pacchetti in entrata, 'out' = in uscita.\nUna sola ACL per direzione per interfaccia." },
    { fronte: "NAT overload (PAT)",
      retro: "(config)# access-list 1 permit 192.168.1.0 0.0.0.255\n(config)# ip nat inside source list 1 interface fa0/0 overload\n(config-if)# ip nat inside (interfaccia LAN)\n(config-if)# ip nat outside (interfaccia WAN)" },
    { fronte: "ping in IOS",
      retro: "ping [IP] — verifica raggiungibilità. Output: ! = successo, . = timeout, U = unreachable. Ping esteso (# ping): personalizza sorgente, dimensione, ripetizioni. Usato per verificare connettività e rotte." },
    { fronte: "traceroute in IOS",
      retro: "traceroute [IP] — mostra hop per hop il percorso. Ogni riga: numero hop, IP router, RTT x3. * = timeout (pacchetto perso o router non risponde a ICMP). Utile per diagnosticare dove si rompe la connettività." }
  ]

}; // fine window.flashcardData
