/* =========================================================================
   quiz-data.js — Sistemi e Reti · 17 Argomenti
   Tipi: mc = scelta multipla, tf = vero/falso, open = domanda aperta
   ========================================================================= */

window.QUIZ_DATA = {

  /* ══════════════════════════════════════════════════════════════
     ARGOMENTO 1 — TCP/IP e Indirizzi IP
  ══════════════════════════════════════════════════════════════ */
  "tcpip": [
    { id:1, type:"mc", topic:"Modello TCP/IP",
      text:"Quanti livelli ha il modello TCP/IP?",
      options:["3","4","5","7"],
      correct:1,
      explanation:"Il modello TCP/IP ha 4 livelli: Accesso alla rete, Internet, Trasporto, Applicazione." },
    { id:2, type:"mc", topic:"Classi IP",
      text:"Un indirizzo IP che inizia con 192 appartiene alla classe:",
      options:["Classe A","Classe B","Classe C","Classe D"],
      correct:2,
      explanation:"Classe C: indirizzi da 192.0.0.0 a 223.255.255.255. Primo bit: 110." },
    { id:3, type:"tf", topic:"Indirizzi privati",
      text:"L'indirizzo 172.20.5.1 è un indirizzo IP privato.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. Il range privato di Classe B è 172.16.0.0–172.31.255.255 (RFC 1918). 172.20.5.1 rientra in questo range." },
    { id:4, type:"mc", topic:"Porte",
      text:"Su quale porta lavora HTTPS?",
      options:["80","21","443","53"],
      correct:2,
      explanation:"HTTPS usa la porta TCP 443. HTTP usa la porta 80." },
    { id:5, type:"mc", topic:"TCP vs UDP",
      text:"Quale protocollo del livello Trasporto garantisce la consegna affidabile dei dati?",
      options:["UDP","ICMP","TCP","IP"],
      correct:2,
      explanation:"TCP (Transmission Control Protocol) è orientato alla connessione e garantisce consegna, ordine e integrità. UDP è più veloce ma non affidabile." },
    { id:6, type:"mc", topic:"Loopback",
      text:"Quale indirizzo IP è riservato al loopback?",
      options:["0.0.0.0","255.255.255.0","192.168.1.1","127.0.0.1"],
      correct:3,
      explanation:"127.0.0.1 è l'indirizzo di loopback (localhost): i pacchetti inviati qui tornano allo stesso host, usato per test locali." },
    { id:7, type:"tf", topic:"IPv6",
      text:"IPv6 è stato introdotto principalmente per risolvere il problema dell'esaurimento degli indirizzi IPv4.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. IPv4 ha circa 4 miliardi di indirizzi, ormai insufficienti. IPv6 usa 128 bit, garantendo 3,4×10^38 indirizzi." },
    { id:8, type:"mc", topic:"Porte",
      text:"In quale range rientrano le porte 'well-known'?",
      options:["0–1023","1024–49151","49152–65535","0–65535"],
      correct:0,
      explanation:"Le porte well-known (0-1023) sono assegnate da IANA a servizi standard come HTTP(80), HTTPS(443), DNS(53), SSH(22)." },
    { id:9, type:"open", topic:"Classi IP",
      text:"Descrivi le tre principali classi di indirizzi IPv4 (A, B, C) specificando il range e il numero tipico di host per rete.",
      modelAnswer:"Classe A: 1.0.0.0–126.255.255.255, maschera /8 (255.0.0.0), 2^24-2 ≈ 16 milioni di host. Classe B: 128.0.0.0–191.255.255.255, maschera /16, 2^16-2 ≈ 65534 host. Classe C: 192.0.0.0–223.255.255.255, maschera /24, 2^8-2 = 254 host. Gli indirizzi privati (RFC 1918): A: 10.x.x.x; B: 172.16-31.x.x; C: 192.168.x.x.",
      keywords:["Classe A","Classe B","Classe C","/8","/16","/24","privati","RFC 1918"] },
    { id:10, type:"mc", topic:"Porte",
      text:"Su quale porta lavora SSH?",
      options:["21","22","23","25"],
      correct:1,
      explanation:"SSH (Secure Shell) usa la porta TCP 22. FTP=21, Telnet=23, SMTP=25." },
    { id:11, type:"mc", topic:"TCP vs UDP",
      text:"Quale protocollo viene usato tipicamente per il DNS?",
      options:["TCP porta 80","UDP porta 53","TCP porta 443","UDP porta 67"],
      correct:1,
      explanation:"Il DNS usa principalmente UDP porta 53 per le query (più veloce). Usa TCP porta 53 per trasferimenti di zona." },
    { id:12, type:"open", topic:"TCP vs UDP",
      text:"Spiega le differenze tra TCP e UDP e fornisci esempi d'uso per ciascuno.",
      modelAnswer:"TCP: orientato alla connessione (three-way handshake SYN-SYN/ACK-ACK), garantisce consegna ordinata e senza errori, controllo di flusso e congestione, più lento. Uso: HTTP, HTTPS, FTP, SSH, SMTP. UDP: senza connessione, non garantisce consegna/ordine, nessun controllo flusso, più veloce e leggero. Uso: DNS, DHCP, streaming video/audio, gaming online, VoIP.",
      keywords:["connessione","three-way handshake","consegna","affidabile","UDP","veloce","streaming","DNS"] }
  ],

  /* ══════════════════════════════════════════════════════════════
     ARGOMENTO 2 — Subnetting, VLSM e CIDR
  ══════════════════════════════════════════════════════════════ */
  "subnetting": [
    { id:1, type:"mc", topic:"Subnetting",
      text:"Data la rete 192.168.1.0/24, quanti host disponibili ha?",
      options:["254","256","255","252"],
      correct:0,
      explanation:"Con /24 ci sono 8 bit host: 2^8 - 2 = 254 host (si sottraggono indirizzo di rete e broadcast)." },
    { id:2, type:"mc", topic:"Broadcast",
      text:"Qual è il broadcast della rete 192.168.10.0/24?",
      options:["192.168.10.1","192.168.10.254","192.168.10.255","192.168.255.255"],
      correct:2,
      explanation:"Il broadcast è l'ultimo indirizzo della rete: tutti i bit host a 1. Per /24 → xxx.255." },
    { id:3, type:"open", topic:"Calcolo subnet",
      text:"Data la rete 172.16.0.0/25, calcola: indirizzo di rete, broadcast, primo e ultimo host, numero di host disponibili.",
      modelAnswer:"Maschera /25 = 255.255.255.128. Rete: 172.16.0.0. Broadcast: 172.16.0.127. Primo host: 172.16.0.1. Ultimo host: 172.16.0.126. Host disponibili: 2^7 - 2 = 126.",
      keywords:["255.255.255.128","172.16.0.0","172.16.0.127","126","primo host","ultimo host"] },
    { id:4, type:"mc", topic:"CIDR",
      text:"La notazione CIDR /26 corrisponde alla subnet mask:",
      options:["255.255.255.0","255.255.255.128","255.255.255.192","255.255.255.224"],
      correct:2,
      explanation:"/26 significa 26 bit a 1: 11111111.11111111.11111111.11000000 = 255.255.255.192." },
    { id:5, type:"tf", topic:"VLSM",
      text:"Con VLSM è possibile usare maschere di lunghezze diverse all'interno della stessa rete.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. VLSM (Variable Length Subnet Mask) permette di assegnare maschere diverse a sottoreti diverse, ottimizzando l'uso degli indirizzi." },
    { id:6, type:"mc", topic:"Formula host",
      text:"Con n=5 bit host, quanti host utilizzabili ha la sottorete?",
      options:["30","32","28","16"],
      correct:0,
      explanation:"Formula: 2^n - 2 = 2^5 - 2 = 32 - 2 = 30 host. Si sottraggono indirizzo di rete (tutti 0) e broadcast (tutti 1)." },
    { id:7, type:"mc", topic:"Wildcard",
      text:"La wildcard mask per la subnet mask 255.255.255.0 è:",
      options:["255.255.255.255","0.0.0.255","0.255.255.255","255.0.0.0"],
      correct:1,
      explanation:"Wildcard = 255.255.255.255 - subnet mask. 255.255.255.255 - 255.255.255.0 = 0.0.0.255." },
    { id:8, type:"open", topic:"VLSM",
      text:"Cosa significa VLSM e perché è preferibile al subnetting classico a lunghezza fissa?",
      modelAnswer:"VLSM (Variable Length Subnet Mask) consente di assegnare maschere di lunghezza diversa a sottoreti diverse all'interno dello stesso spazio di indirizzamento. A differenza del subnetting classico (tutte le sottoreti con la stessa maschera), VLSM permette di dimensionare ogni sottorete esattamente in base al numero di host necessari: reti con pochi host usano maschere più strette (/30 = 2 host), reti grandi usano /24 o superiore. Questo minimizza lo spreco di indirizzi IP.",
      keywords:["VLSM","maschere diverse","ottimizzazione","spreco","/30","dimensionare"] },
    { id:9, type:"mc", topic:"CIDR",
      text:"Cosa supera il CIDR rispetto alle classi IP tradizionali?",
      options:["Il limite di 256 reti","Le classi fisse A/B/C","Il numero massimo di host","Il protocollo IPv6"],
      correct:1,
      explanation:"CIDR (Classless Inter-Domain Routing) supera il sistema delle classi fisse, permettendo blocchi di indirizzi di qualsiasi dimensione." },
    { id:10, type:"mc", topic:"Subnetting",
      text:"Data la rete 10.0.0.0/8 suddivisa con maschera /12, quante sottoreti si ottengono?",
      options:["4","8","16","32"],
      correct:2,
      explanation:"Bit di subnet = 12-8 = 4 bit. 2^4 = 16 sottoreti." },
    { id:11, type:"tf", topic:"Wildcard",
      text:"La wildcard mask 0.0.0.255 corrisponde alla notazione /24.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. Wildcard 0.0.0.255 = subnet mask 255.255.255.0 = /24. I bit a 0 nella wildcard indicano bit controllati (fissi)." },
    { id:12, type:"open", topic:"Calcolo subnet",
      text:"Hai la rete 192.168.5.0/24. Devi creare 4 sottoreti con VLSM: Sede A 60 host, Sede B 30 host, Sede C 10 host, Link WAN 2 host. Indica le maschere necessarie.",
      modelAnswer:"Sede A: 60 host → 2^6=64-2=62, maschera /26 (255.255.255.192) — 192.168.5.0/26. Sede B: 30 host → 2^5=32-2=30, maschera /27 (255.255.255.224) — 192.168.5.64/27. Sede C: 10 host → 2^4=16-2=14, maschera /28 (255.255.255.240) — 192.168.5.96/28. Link WAN: 2 host → 2^2=4-2=2, maschera /30 (255.255.255.252) — 192.168.5.112/30.",
      keywords:["/26","/27","/28","/30","62 host","30 host","14 host","2 host","VLSM"] }
  ],

  /* ══════════════════════════════════════════════════════════════
     ARGOMENTO 3 — NAT, PAT e ICMP
  ══════════════════════════════════════════════════════════════ */
  "nat-icmp": [
    { id:1, type:"mc", topic:"NAT",
      text:"Qual è la principale differenza tra NAT statico e NAT dinamico?",
      options:[
        "NAT statico usa IPv6, NAT dinamico IPv4",
        "NAT statico mappa 1:1 fisso, NAT dinamico usa un pool assegnato dinamicamente",
        "NAT statico è più veloce di NAT dinamico",
        "NAT statico non richiede tabella NAT"
      ],
      correct:1,
      explanation:"NAT statico: mappatura fissa 1:1 (un IP privato↔un IP pubblico). NAT dinamico: pool di IP pubblici assegnati in modo dinamico alle sessioni." },
    { id:2, type:"tf", topic:"PAT",
      text:"PAT (Port Address Translation) permette a molti IP privati di condividere un singolo IP pubblico usando porte diverse.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. PAT/NAT Overload multiplica le connessioni aggiungendo numeri di porta univoci. È il tipo usato nei router domestici." },
    { id:3, type:"mc", topic:"ICMP",
      text:"Il comando 'ping' usa quale protocollo?",
      options:["TCP","UDP","ICMP","ARP"],
      correct:2,
      explanation:"ping usa i messaggi ICMP Echo Request e Echo Reply per verificare la raggiungibilità di un host e misurare il RTT." },
    { id:4, type:"mc", topic:"TTL",
      text:"Cosa succede quando il TTL di un pacchetto IP arriva a 0?",
      options:[
        "Il pacchetto viene rispedito all'origine",
        "Il pacchetto viene scartato e viene inviato un ICMP Time Exceeded",
        "Il pacchetto viene recapitato comunque a destinazione",
        "Il TTL viene incrementato automaticamente"
      ],
      correct:1,
      explanation:"Ogni router decrementa il TTL di 1. A 0 il pacchetto viene scartato e inviato un messaggio ICMP Time Exceeded all'origine. Usato da traceroute." },
    { id:5, type:"open", topic:"NAT",
      text:"Descrivi i vantaggi e gli svantaggi del NAT.",
      modelAnswer:"Vantaggi: 1) Risparmio di indirizzi IPv4 pubblici (molti host privati condividono pochi IP pubblici). 2) Sicurezza: gli IP interni sono nascosti dalla rete pubblica. 3) Flessibilità nella gestione dell'indirizzamento interno. Svantaggi: 1) Rompe il modello end-to-end di Internet (i nodi interni non sono direttamente raggiungibili). 2) Problemi con alcuni protocolli che incorporano indirizzi IP nel payload (SIP/VoIP, FTP). 3) Complicazioni per hosting di server interni (richiede port forwarding). 4) Introduce latenza per la traduzione.",
      keywords:["risparmio","IPv4","sicurezza","end-to-end","port forwarding","SIP","FTP"] },
    { id:6, type:"mc", topic:"Traceroute",
      text:"Quale meccanismo usa traceroute per ricostruire il percorso dei pacchetti?",
      options:[
        "Invia pacchetti con TTL crescente e raccoglie i messaggi ICMP Time Exceeded",
        "Usa ping su ogni router della rete",
        "Interroga il DNS per trovare i router",
        "Usa il protocollo SNMP per interrogare ogni dispositivo"
      ],
      correct:0,
      explanation:"traceroute invia pacchetti con TTL=1,2,3… Ogni router che raggiunge il limite scarta il pacchetto e invia un ICMP Time Exceeded, rivelando il proprio IP." },
    { id:7, type:"mc", topic:"ICMP",
      text:"Quale messaggio ICMP indica che la destinazione non è raggiungibile?",
      options:["ICMP Echo Request","ICMP Time Exceeded","ICMP Destination Unreachable","ICMP Redirect"],
      correct:2,
      explanation:"ICMP Destination Unreachable: inviato dal router o dall'host quando non riesce a consegnare il pacchetto a destinazione." },
    { id:8, type:"tf", topic:"PAT",
      text:"Il router domestico tipico usa NAT overload (PAT) per connettere tutti i dispositivi della rete locale a Internet con un solo IP pubblico.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. Ogni dispositivo della LAN ha un IP privato; il router usa PAT per tradurre tutte le connessioni verso l'unico IP pubblico del provider, usando porte diverse per distinguere le sessioni." },
    { id:9, type:"open", topic:"ICMP",
      text:"Cos'è ICMP e quali sono i suoi messaggi principali? Quale ruolo gioca nella diagnostica di rete?",
      modelAnswer:"ICMP (Internet Control Message Protocol) è un protocollo di controllo e diagnostica che lavora a livello Rete. Non trasporta dati utente ma messaggi di controllo. Messaggi principali: Echo Request/Reply (ping — verifica raggiungibilità), Destination Unreachable (host/rete non raggiungibile), Time Exceeded (TTL scaduto — usato da traceroute), Redirect (suggerisce un percorso migliore). Ruolo diagnostica: ping verifica se un host è raggiungibile e misura RTT; traceroute ricostruisce il percorso hop-per-hop.",
      keywords:["ICMP","Echo Request","Echo Reply","Destination Unreachable","Time Exceeded","ping","traceroute","TTL","diagnostica"] },
    { id:10, type:"mc", topic:"NAT",
      text:"Nella tabella NAT, quale informazione viene registrata per ogni sessione PAT?",
      options:[
        "Solo l'IP privato",
        "Solo la porta pubblica",
        "IP privato + porta privata ↔ IP pubblico + porta pubblica",
        "Il MAC address del client"
      ],
      correct:2,
      explanation:"La tabella NAT/PAT tiene traccia di: IP privato + porta privata (lato LAN) ↔ IP pubblico + porta pubblica (lato Internet), permettendo di smistare le risposte al client corretto." }
  ],

  /* ══════════════════════════════════════════════════════════════
     ARGOMENTO 4 — Routing: Fondamenti e Algoritmi
  ══════════════════════════════════════════════════════════════ */
  "routing": [
    { id:1, type:"mc", topic:"Routing statico",
      text:"Quale svantaggio principale ha il routing statico rispetto al routing dinamico?",
      options:[
        "È più lento nel calcolare i percorsi",
        "Non si adatta automaticamente ai guasti di rete",
        "Genera troppo overhead di rete",
        "Non supporta il protocollo IP"
      ],
      correct:1,
      explanation:"Il routing statico richiede configurazione manuale delle rotte. Non si adatta automaticamente ai guasti: se un link cade, il traffico non viene reindirizzato automaticamente." },
    { id:2, type:"mc", topic:"Tabella di routing",
      text:"Cosa indica il campo 'Next-Hop' in una tabella di routing?",
      options:[
        "L'indirizzo IP finale di destinazione",
        "L'interfaccia di uscita del router",
        "L'IP del prossimo router verso la destinazione",
        "La metrica del percorso"
      ],
      correct:2,
      explanation:"Next-hop: l'indirizzo IP del router successivo verso cui inoltrare il pacchetto. Il router corrente non conosce l'intero percorso, solo il 'prossimo salto'." },
    { id:3, type:"open", topic:"Bellman-Ford",
      text:"Descrivi l'algoritmo Bellman-Ford e il suo utilizzo nel routing.",
      modelAnswer:"Bellman-Ford è un algoritmo di percorso minimo di tipo Distance Vector. Ogni nodo conosce solo le distanze verso i vicini diretti. Scambia vettori di distanza con i vicini e aggiorna la tabella se trova un percorso più breve. Convergenza: dopo V-1 iterazioni (V = numero di nodi). Accetta pesi negativi. Complessità: O(V×E). Nel routing è usato da RIP: ogni router invia a vicini la propria tabella ogni 30s. Problema: Count-to-Infinity quando un link cade.",
      keywords:["Bellman-Ford","Distance Vector","vettori","vicini","convergenza","RIP","O(V×E)"] },
    { id:4, type:"mc", topic:"Dijkstra",
      text:"Quale protocollo di routing usa l'algoritmo di Dijkstra?",
      options:["RIP","BGP","OSPF","EIGRP"],
      correct:2,
      explanation:"OSPF (Open Shortest Path First) usa l'algoritmo di Dijkstra (Link-State). Ogni router ha la mappa completa della rete e calcola autonomamente il percorso più breve." },
    { id:5, type:"tf", topic:"AS",
      text:"BGP è un protocollo IGP usato all'interno di un singolo Autonomous System.",
      options:["Vero","Falso"],
      correct:1,
      explanation:"FALSO. BGP (Border Gateway Protocol) è un protocollo EGP (Exterior Gateway Protocol) usato per il routing TRA Autonomous System diversi. È il protocollo di routing di Internet." },
    { id:6, type:"mc", topic:"Algoritmi",
      text:"Quale algoritmo NON accetta pesi negativi sugli archi?",
      options:["Bellman-Ford","Floyd-Warshall","Dijkstra","Nessuno dei precedenti"],
      correct:2,
      explanation:"Dijkstra non funziona correttamente con pesi negativi. Bellman-Ford supporta pesi negativi (ma non cicli negativi)." },
    { id:7, type:"open", topic:"IGP vs EGP",
      text:"Spiega la differenza tra IGP ed EGP e fornisci esempi di protocolli per ciascuna categoria.",
      modelAnswer:"IGP (Interior Gateway Protocol): routing interno a un Autonomous System, ottimizza il percorso in base alla metrica tecnica. Esempi: RIP (Distance Vector, hop count), OSPF (Link-State, costo banda), EIGRP (Cisco, ibrido). EGP (Exterior Gateway Protocol): routing tra AS diversi, considera policy aziendali/politiche oltre alla metrica. Esempio: BGP (Path Vector). Gli ISP usano BGP per scambiare informazioni di routing a livello Internet.",
      keywords:["IGP","EGP","Autonomous System","RIP","OSPF","BGP","policy","Path Vector"] },
    { id:8, type:"mc", topic:"Routing dinamico",
      text:"Quale vantaggio principale ha il routing dinamico?",
      options:[
        "Zero overhead di rete",
        "Semplicità di configurazione",
        "Adattamento automatico ai cambiamenti di topologia",
        "Nessun ritardo di convergenza"
      ],
      correct:2,
      explanation:"Il routing dinamico si adatta automaticamente ai guasti e ai cambiamenti di topologia, senza intervento manuale dell'amministratore di rete." }
  ],

  /* ══════════════════════════════════════════════════════════════
     ARGOMENTO 5 — RIP
  ══════════════════════════════════════════════════════════════ */
  "rip": [
    { id:1, type:"mc", topic:"Metrica RIP",
      text:"Qual è la metrica utilizzata da RIP?",
      options:["Larghezza di banda","Hop count","Costo","Latenza"],
      correct:1,
      explanation:"RIP usa l'hop count come metrica: il numero di router attraversati. Il valore massimo è 15; 16 = rete irraggiungibile." },
    { id:2, type:"mc", topic:"Count-to-Infinity",
      text:"Cosa si intende per problema 'Count-to-Infinity' in RIP?",
      options:[
        "Il router conta all'infinito le rotte disponibili",
        "Quando un link cade, la metrica sale lentamente fino a 16 prima di dichiarare la rete irraggiungibile",
        "RIP non ha limite al numero di hop",
        "Il timer di aggiornamento non si ferma mai"
      ],
      correct:1,
      explanation:"Count-to-Infinity: quando un link cade, i router potrebbero continuare ad annunciare la rotta con metrica crescente (1→2→3…→16) prima di capire che è irraggiungibile." },
    { id:3, type:"mc", topic:"RIPv1 vs RIPv2",
      text:"Quale caratteristica distingue RIPv2 da RIPv1?",
      options:[
        "RIPv2 usa TCP invece di UDP",
        "RIPv2 supporta VLSM/CIDR e usa multicast 224.0.0.9",
        "RIPv2 ha una metrica basata sulla larghezza di banda",
        "RIPv2 non ha il problema Count-to-Infinity"
      ],
      correct:1,
      explanation:"RIPv2 è classless (supporta VLSM/CIDR), usa multicast 224.0.0.9 (invece di broadcast 255.255.255.255 di v1), supporta autenticazione MD5." },
    { id:4, type:"tf", topic:"Split Horizon",
      text:"Split Horizon previene il Count-to-Infinity non ri-pubblicando verso il router da cui si è appresa la rotta.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. Split Horizon: se un router ha appreso una rotta da un vicino X, non la ri-annuncia verso X. Questo previene il Count-to-Infinity nel caso semplice." },
    { id:5, type:"mc", topic:"Timer RIP",
      text:"Ogni quanto tempo RIP invia aggiornamenti periodici?",
      options:["10 secondi","30 secondi","60 secondi","90 secondi"],
      correct:1,
      explanation:"RIP invia aggiornamenti (RIP Update) ogni 30 secondi (Update Timer). Se non si ricevono aggiornamenti per 180s, la rotta è marcata invalida (Invalid Timer)." },
    { id:6, type:"open", topic:"Poisoned Reverse",
      text:"Spiega la differenza tra Split Horizon e Poisoned Reverse e come entrambe affrontano il Count-to-Infinity.",
      modelAnswer:"Split Horizon: un router non ri-pubblica una rotta verso il router da cui l'ha appresa. Se R1 ha appreso che la rete X è raggiungibile via R2, R1 non annuncia X a R2. Semplice e leggero. Poisoned Reverse: invece di omettere la rotta, R1 la ri-annuncia a R2 con metrica 16 (irraggiungibile), cosicché R2 capisce immediatamente che la rotta è inutile via R1. Più esplicito e veloce nella convergenza, ma genera più traffico. Entrambi risolvono il Count-to-Infinity nei casi a due nodi, ma non in topologie complesse con più router.",
      keywords:["Split Horizon","Poisoned Reverse","metrica 16","Count-to-Infinity","convergenza","non ri-pubblica"] },
    { id:7, type:"mc", topic:"Comandi Cisco",
      text:"Quale comando Cisco IOS mostra la tabella di routing completa?",
      options:["show ip protocols","show ip rip database","show ip route","debug ip rip"],
      correct:2,
      explanation:"'show ip route' mostra la tabella di routing completa del router, incluse rotte RIP (R), statiche (S), connected (C) e OSPF (O)." },
    { id:8, type:"mc", topic:"RIPv2",
      text:"Quale indirizzo multicast usa RIPv2 per inviare gli aggiornamenti?",
      options:["255.255.255.255","224.0.0.5","224.0.0.9","239.0.0.0"],
      correct:2,
      explanation:"RIPv2 usa il multicast 224.0.0.9 (al posto del broadcast di RIPv1). Questo riduce il carico sugli host che non eseguono RIP." },
    { id:9, type:"open", topic:"Timer RIP",
      text:"Elenca e descrivi i 4 timer di RIP.",
      modelAnswer:"1. Update Timer (30s): frequenza degli aggiornamenti periodici inviati ai vicini. 2. Invalid Timer (180s): se nessun aggiornamento per una rotta arriva in 180s, la rotta viene marcata invalida (metrica=16). 3. Holddown Timer (180s): dopo aver marcato una rotta invalida, si attende 180s prima di accettare nuove informazioni su quella rotta (previene instabilità). 4. Flush Timer (240s): trascorsi 240s dall'ultimo aggiornamento, la rotta viene rimossa definitivamente dalla tabella.",
      keywords:["Update Timer","Invalid Timer","Holddown Timer","Flush Timer","30s","180s","240s"] },
    { id:10, type:"tf", topic:"RIPv1",
      text:"RIPv1 è classless: include la subnet mask negli aggiornamenti.",
      options:["Vero","Falso"],
      correct:1,
      explanation:"FALSO. RIPv1 è classful: non include la subnet mask negli aggiornamenti. È quindi incompatibile con VLSM e CIDR. È RIPv2 ad essere classless." }
  ],

  /* ══════════════════════════════════════════════════════════════
     ARGOMENTO 6 — OSPF e BGP (cenni)
  ══════════════════════════════════════════════════════════════ */
  "ospf-bgp": [
    { id:1, type:"mc", topic:"OSPF",
      text:"OSPF è un protocollo di tipo:",
      options:["Distance Vector","Path Vector","Link-State","Hybrid"],
      correct:2,
      explanation:"OSPF (Open Shortest Path First) è Link-State: ogni router invia LSA (Link State Advertisement) a tutti gli altri, costruendo una mappa completa della rete e calcolando i percorsi con Dijkstra." },
    { id:2, type:"mc", topic:"OSPF",
      text:"Cosa è il LSDB in OSPF?",
      options:[
        "Link Subnet Database — lista delle sottoreti",
        "Link State Database — mappa completa della topologia di rete",
        "Local Security Database — tabella degli accessi",
        "Load Sharing Distribution Board"
      ],
      correct:1,
      explanation:"LSDB (Link State Database): il database che ogni router OSPF costruisce raccogliendo tutti i LSA. Contiene la topologia completa della rete." },
    { id:3, type:"mc", topic:"OSPF vs RIP",
      text:"Quale metrica usa OSPF?",
      options:["Hop count","Latenza","Costo (inversamente proporzionale alla banda)","RTT"],
      correct:2,
      explanation:"OSPF usa il costo come metrica: costo = larghezza di banda riferimento / larghezza di banda interfaccia. Interfacce più veloci hanno costo minore." },
    { id:4, type:"tf", topic:"BGP",
      text:"BGP è il protocollo di routing utilizzato tra i router degli Internet Service Provider (ISP) per instradare il traffico su Internet.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. BGP (Border Gateway Protocol) è l'EGP usato tra AS diversi. È la 'colla' di Internet: ogni router di frontiera degli ISP usa BGP per scambiarsi le tabelle di routing globali." },
    { id:5, type:"open", topic:"OSPF vs RIP",
      text:"Confronta OSPF e RIP rispetto a: tipo, algoritmo, metrica, scalabilità, velocità di convergenza.",
      modelAnswer:"RIP: Distance Vector, algoritmo Bellman-Ford, metrica hop count (max 15), adatto a piccole reti, convergenza lenta (30s per update). OSPF: Link-State, algoritmo Dijkstra, metrica costo (basato su banda), scalabile per reti grandi, convergenza rapida (aggiornamenti solo al cambio di topologia). OSPF è più complesso da configurare ma molto più efficiente e scalabile. Supporta nativamente VLSM/CIDR e struttura gerarchica con aree.",
      keywords:["RIP","OSPF","Bellman-Ford","Dijkstra","hop count","costo","convergenza","VLSM","aree"] },
    { id:6, type:"mc", topic:"BGP",
      text:"Quale meccanismo usa BGP per scambiare informazioni di routing?",
      options:["Vettori di distanza","Mappe di topologia completa","Path Vector (lista degli AS attraversati)","Tabelle ARP"],
      correct:2,
      explanation:"BGP usa il Path Vector: ogni annuncio contiene la lista completa degli AS attraversati per raggiungere la destinazione. Questo permette di evitare loop e implementare policy di routing." }
  ],

  /* ══════════════════════════════════════════════════════════════
     ARGOMENTO 7 — Crittografia: Principi e Crittografia Simmetrica
  ══════════════════════════════════════════════════════════════ */
  "crittografia": [
    { id:1, type:"mc", topic:"Crittografia simmetrica",
      text:"Quale caratteristica definisce la crittografia simmetrica?",
      options:[
        "Usa due chiavi diverse per cifrare e decifrare",
        "Usa la stessa chiave per cifrare e decifrare",
        "Non richiede chiavi",
        "Usa solo chiavi pubbliche"
      ],
      correct:1,
      explanation:"Crittografia simmetrica: stessa chiave segreta condivisa per cifrare e decifrare. Veloce ed efficiente, ma richiede uno scambio sicuro della chiave." },
    { id:2, type:"mc", topic:"AES",
      text:"Quale algoritmo è lo standard attuale per la crittografia simmetrica?",
      options:["DES","3DES","AES","RC4"],
      correct:2,
      explanation:"AES (Advanced Encryption Standard) è lo standard dal 2001. Supporta chiavi di 128, 192 o 256 bit. Molto sicuro ed efficiente hardware e software." },
    { id:3, type:"tf", topic:"DES",
      text:"DES è considerato sicuro e viene ancora usato come standard nelle applicazioni moderne.",
      options:["Vero","Falso"],
      correct:1,
      explanation:"FALSO. DES usa una chiave di soli 56 bit — vulnerabile ad attacchi brute force (violato in meno di 24h già nel 1999). È obsoleto e non deve essere usato per applicazioni di sicurezza." },
    { id:4, type:"mc", topic:"Crittografia asimmetrica",
      text:"Quale problema risolve la crittografia asimmetrica rispetto alla simmetrica?",
      options:[
        "La velocità di cifratura",
        "La dimensione dei file cifrati",
        "Il problema della distribuzione sicura della chiave",
        "La resistenza agli attacchi brute force"
      ],
      correct:2,
      explanation:"La crittografia asimmetrica usa una coppia chiave pubblica/privata: la chiave pubblica si distribuisce liberamente. Non serve uno scambio segreto iniziale della chiave." },
    { id:5, type:"open", topic:"Sistema ibrido",
      text:"Cos'è il sistema ibrido di crittografia e perché viene usato in protocolli come SSL/TLS?",
      modelAnswer:"Il sistema ibrido combina crittografia asimmetrica e simmetrica sfruttando i punti di forza di entrambe. Fase 1 (asimmetrica): si usa la crittografia a chiave pubblica/privata per scambiare in sicurezza una chiave simmetrica temporanea (session key). Fase 2 (simmetrica): la comunicazione effettiva usa la chiave simmetrica appena scambiata. Perché: la crittografia asimmetrica è lenta (1000x più lenta della simmetrica) — ideale solo per piccole quantità di dati come lo scambio di chiavi. La simmetrica è veloce per i dati. SSL/TLS usa questo schema nell'handshake.",
      keywords:["sistema ibrido","asimmetrica","simmetrica","session key","scambio chiavi","SSL/TLS","handshake","velocità"] },
    { id:6, type:"mc", topic:"RSA",
      text:"RSA è un algoritmo di crittografia asimmetrica basato su:",
      options:[
        "La difficoltà di calcolare logaritmi discreti",
        "La difficoltà di fattorizzare grandi numeri in fattori primi",
        "La difficoltà di risolvere problemi NP",
        "La difficoltà di invertire funzioni hash"
      ],
      correct:1,
      explanation:"RSA è basato sulla difficoltà computazionale di fattorizzare il prodotto di due grandi numeri primi. Chiavi tipiche: 2048 o 4096 bit." },
    { id:7, type:"mc", topic:"Obiettivi crittografia",
      text:"Quale proprietà garantisce che il mittente di un messaggio non possa in seguito negarne l'invio?",
      options:["Confidenzialità","Integrità","Autenticazione","Non ripudio"],
      correct:3,
      explanation:"Il non ripudio garantisce che il mittente non possa negare di aver inviato il messaggio. È garantito dalla firma digitale con chiave privata." },
    { id:8, type:"tf", topic:"3DES",
      text:"3DES applica l'algoritmo DES tre volte con chiavi diverse, aumentando la sicurezza rispetto al DES originale.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. 3DES (Triple DES) applica DES 3 volte: cifratura-decifratura-cifratura con 3 chiavi (EDE), ottenendo una chiave effettiva di 112-168 bit. È più sicuro di DES ma lento — oggi considerato legacy." }
  ],

  /* ══════════════════════════════════════════════════════════════
     ARGOMENTO 8 — Diffie-Hellman, Hash, MAC, Firma Digitale
  ══════════════════════════════════════════════════════════════ */
  "diffie-hellman": [
    { id:1, type:"mc", topic:"Diffie-Hellman",
      text:"Cosa permette l'algoritmo Diffie-Hellman?",
      options:[
        "Cifrare messaggi con chiave pubblica",
        "Scambiare in sicurezza una chiave segreta su un canale pubblico senza trasmetterla",
        "Generare firme digitali",
        "Verificare l'integrità dei dati"
      ],
      correct:1,
      explanation:"DH permette a due parti di derivare la stessa chiave segreta condivisa senza trasmetterla mai sul canale (potenzialmente pubblico). Basato sul problema del logaritmo discreto." },
    { id:2, type:"mc", topic:"Hash",
      text:"Quale proprietà fondamentale di una funzione hash la rende 'a senso unico'?",
      options:[
        "È deterministica",
        "Produce sempre output di dimensione fissa",
        "È computazionalmente irreversibile: dall'hash non si può risalire all'input",
        "Ha l'effetto valanga"
      ],
      correct:2,
      explanation:"La proprietà di one-way (a senso unico): dato l'hash H(x), è computazionalmente impossibile trovare x. Fondamentale per la sicurezza delle password e delle firme digitali." },
    { id:3, type:"mc", topic:"Hash",
      text:"Quale algoritmo hash è attualmente raccomandato per le applicazioni di sicurezza?",
      options:["MD5","SHA-1","SHA-256","CRC32"],
      correct:2,
      explanation:"SHA-256 (parte della famiglia SHA-2) è attualmente lo standard sicuro. MD5 e SHA-1 sono deprecati per uso crittografico (vulnerabili a collisioni)." },
    { id:4, type:"open", topic:"Firma Digitale",
      text:"Descrivi passo per passo come funziona la firma digitale, specificando quale chiave viene usata in ogni fase.",
      modelAnswer:"1. Il mittente calcola l'hash del messaggio (es. SHA-256). 2. Cifra l'hash con la propria chiave PRIVATA → ottiene la firma digitale. 3. Invia messaggio + firma al destinatario. 4. Il destinatario decifra la firma con la chiave PUBBLICA del mittente → ottiene l'hash originale. 5. Ricalcola indipendentemente l'hash del messaggio ricevuto. 6. Confronta i due hash: se coincidono → firma valida (autenticità + integrità + non ripudio). Solo chi ha la chiave privata può creare una firma valida.",
      keywords:["hash","chiave privata","chiave pubblica","firma","autenticità","integrità","non ripudio","confronto"] },
    { id:5, type:"mc", topic:"MAC",
      text:"Cosa garantisce un MAC (Message Authentication Code) rispetto a un semplice hash?",
      options:[
        "Garantisce solo la confidenzialità",
        "Garantisce integrità E autenticazione del mittente (grazie alla chiave segreta condivisa)",
        "Garantisce solo l'integrità, come l'hash",
        "Non richiede chiavi"
      ],
      correct:1,
      explanation:"Un MAC usa una chiave segreta condivisa: solo chi conosce la chiave può generare o verificare il MAC. Garantisce integrità (il messaggio non è stato alterato) E autenticazione (proviene da chi ha la chiave)." },
    { id:6, type:"tf", topic:"MFA",
      text:"L'autenticazione a due fattori (2FA) è considerata più sicura di una singola password perché combina due categorie di fattori diversi.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. MFA combina fattori di categorie diverse: Knowledge (password/PIN), Possession (token/smartphone), Inherence (biometria). Un attaccante dovrebbe compromettere più categorie simultaneamente." },
    { id:7, type:"mc", topic:"MFA",
      text:"Quale categoria di fattore di autenticazione appartiene un'impronta digitale?",
      options:["Knowledge (qualcosa che sai)","Possession (qualcosa che hai)","Inherence (qualcosa che sei)","Location (dove sei)"],
      correct:2,
      explanation:"Inherence (qualcosa che sei): biometria — impronta digitale, riconoscimento facciale, iride. Non si può dimenticare e difficile da rubare fisicamente." },
    { id:8, type:"mc", topic:"HMAC",
      text:"HMAC-SHA256 è:",
      options:[
        "Un algoritmo di cifratura simmetrica",
        "Un MAC basato sulla funzione hash SHA-256",
        "Un algoritmo di firma digitale",
        "Un protocollo di scambio chiavi"
      ],
      correct:1,
      explanation:"HMAC (Hash-based Message Authentication Code) combina una chiave segreta con la funzione hash. HMAC-SHA256 usa SHA-256 internamente. Usato in SSL/TLS e IPsec per garantire integrità e autenticazione dei blocchi dati." },
    { id:9, type:"open", topic:"Diffie-Hellman",
      text:"Perché Diffie-Hellman è fondamentale anche se non è un algoritmo di cifratura?",
      modelAnswer:"Diffie-Hellman risolve il problema della distribuzione delle chiavi: come due parti che non si sono mai incontrate possono accordarsi su una chiave segreta condivisa su un canale pubblico. Basato sulla difficoltà del logaritmo discreto: due parti scelgono parametri pubblici e valori segreti privati, calcolano valori intermedi che si scambiano pubblicamente, e derivano la stessa chiave combinando i propri segreti con il valore ricevuto. È fondamentale in IPsec (IKE), SSL/TLS handshake e molti altri protocolli di sicurezza. Senza DH, bisognerebbe scambiarsi le chiavi simmetriche su un canale sicuro già esistente — un problema circolare.",
      keywords:["Diffie-Hellman","logaritmo discreto","scambio chiavi","canale pubblico","IPsec","TLS","IKE","problema circolare"] }
  ],

  /* ══════════════════════════════════════════════════════════════
     ARGOMENTO 9 — Certificati Digitali e PKI
  ══════════════════════════════════════════════════════════════ */
  "pki": [
    { id:1, type:"mc", topic:"Certificato digitale",
      text:"Un certificato digitale X.509 contiene principalmente:",
      options:[
        "La chiave privata del titolare",
        "La chiave pubblica del titolare + identità + firma della CA",
        "Solo la firma digitale della CA",
        "Il codice sorgente dell'applicazione"
      ],
      correct:1,
      explanation:"Un certificato X.509 contiene: identità del titolare, chiave pubblica del titolare, periodo di validità, e la firma digitale della CA che lo ha emesso." },
    { id:2, type:"mc", topic:"CA",
      text:"Cosa fa una CA (Certification Authority)?",
      options:[
        "Cifra tutti i dati trasmessi in rete",
        "Emette, firma e può revocare certificati digitali",
        "Gestisce gli indirizzi IP della rete",
        "Esegue il protocollo Diffie-Hellman"
      ],
      correct:1,
      explanation:"La CA è un ente terzo di fiducia che emette certificati digitali (associando chiave pubblica a identità), li firma con la propria chiave privata e può revocarli se necessario." },
    { id:3, type:"tf", topic:"PKI",
      text:"La Root CA è auto-firmata: il suo certificato è firmato dalla CA stessa, non da un'altra CA.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. La Root CA è al vertice della gerarchia PKI: il suo certificato è auto-firmato. È pre-installata nel browser/OS come CA fidata. La sua sicurezza è fondamentale per l'intera PKI." },
    { id:4, type:"open", topic:"Verifica certificato",
      text:"Descrivi i passi che un browser compie per verificare un certificato SSL/TLS di un sito web.",
      modelAnswer:"1. Verifica data: controlla che la data corrente sia all'interno del periodo di validità (non before / not after). 2. Verifica CA: controlla che la CA firmataria sia nella lista delle CA fidate pre-installate nel browser/OS. 3. Verifica firma: decifra la firma digitale della CA con la chiave pubblica della CA e confronta con l'hash del certificato → verifica integrità e autenticità. 4. Verifica dominio: controlla che il Common Name (CN) o Subject Alternative Name (SAN) del certificato corrisponda al dominio nell'URL. Se tutti i controlli passano → connessione sicura (lucchetto verde).",
      keywords:["validità","CA fidata","firma","dominio","CN","SAN","browser","lucchetto"] },
    { id:5, type:"mc", topic:"CRL",
      text:"Cosa è un CRL (Certificate Revocation List)?",
      options:[
        "Una lista di CA fidate pre-installate nel browser",
        "Una lista di certificati revocati prima della loro scadenza",
        "Il protocollo per emettere nuovi certificati",
        "Un tipo di certificato per l'Extended Validation"
      ],
      correct:1,
      explanation:"CRL: lista di certificati revocati (es. perché la chiave privata è stata compromessa). I browser/client la consultano per sapere se un certificato è ancora valido. OCSP è un'alternativa online in tempo reale." },
    { id:6, type:"mc", topic:"Tipi di certificato",
      text:"Quale tipo di certificato SSL richiede la verifica dell'identità legale dell'organizzazione e mostra il nome dell'azienda nella barra del browser?",
      options:["DV (Domain Validation)","OV (Organization Validation)","EV (Extended Validation)","Tutti e tre"],
      correct:2,
      explanation:"EV (Extended Validation): richiede verifica approfondita dell'identità legale. Mostra il nome dell'organizzazione nella barra del browser (barra verde). Usato da banche e siti ad alto rischio." }
  ],

  /* ══════════════════════════════════════════════════════════════
     ARGOMENTO 10 — SSL/TLS
  ══════════════════════════════════════════════════════════════ */
  "ssl-tls": [
    { id:1, type:"mc", topic:"SSL/TLS",
      text:"HTTPS = HTTP + quale protocollo?",
      options:["IPsec","SSH","SSL/TLS","PGP"],
      correct:2,
      explanation:"HTTPS (HTTP Secure) è HTTP con la crittografia SSL/TLS. Usa la porta 443 invece della porta 80 di HTTP." },
    { id:2, type:"mc", topic:"Handshake",
      text:"Durante l'SSL Handshake, il pre-master secret viene cifrato con:",
      options:[
        "La chiave privata del client",
        "La chiave pubblica del server (dal certificato)",
        "La chiave simmetrica di sessione",
        "La chiave privata della CA"
      ],
      correct:1,
      explanation:"Il client genera il pre-master secret e lo cifra con la chiave pubblica del server (estratta dal certificato). Solo il server può decifrarlo con la sua chiave privata." },
    { id:3, type:"mc", topic:"Le 4 chiavi",
      text:"Dal master secret in SSL/TLS vengono derivate quante chiavi di sessione?",
      options:["1","2","3","4"],
      correct:3,
      explanation:"Dal master secret si derivano 4 chiavi: chiave di cifratura client→server, chiave di cifratura server→client, chiave MAC client→server, chiave MAC server→client. La separazione per direzione aumenta la sicurezza." },
    { id:4, type:"open", topic:"Handshake",
      text:"Descrivi i passi principali dell'SSL/TLS Handshake.",
      modelAnswer:"1. CLIENT HELLO: client invia cipher suite supportate + nonce client (byte casuali). 2. SERVER HELLO: server sceglie la cipher suite + invia nonce server. 3. CERTIFICATO: server invia il proprio certificato digitale. 4. SERVER HELLO DONE: server segnala fine proposte. 5. VERIFICA CERTIFICATO: il client verifica validità, CA fidata, firma, corrispondenza dominio. 6. PRE-MASTER SECRET: client genera bytes casuali, li cifra con chiave pubblica del server, li invia. 7. ENTRAMBI calcolano il master secret = f(pre-master secret + nonce client + nonce server). 8. 4 CHIAVI derivate dal master secret. 9. CHANGE CIPHER SPEC + FINISHED: entrambi comunicano che passano alla comunicazione cifrata.",
      keywords:["CLIENT HELLO","SERVER HELLO","certificato","pre-master secret","master secret","4 chiavi","nonce","cipher suite"] },
    { id:5, type:"tf", topic:"SSL/TLS",
      text:"TLS 1.3 è la versione attuale e più sicura del protocollo, mentre SSL è stato deprecato dal 2015.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. SSL (2.0, 3.0) e TLS 1.0/1.1 sono deprecati per vulnerabilità note. TLS 1.2 è ancora usato, TLS 1.3 è lo standard attuale con handshake più veloce e cipher suite più sicure." },
    { id:6, type:"mc", topic:"Cipher Suite",
      text:"Una cipher suite in SSL/TLS specifica:",
      options:[
        "Solo l'algoritmo di cifratura simmetrica",
        "L'insieme completo di algoritmi: scambio chiavi + cifratura + hash per MAC",
        "Solo il certificato da usare",
        "La porta TCP su cui opera"
      ],
      correct:1,
      explanation:"La cipher suite definisce l'insieme degli algoritmi concordati tra client e server: algoritmo di scambio chiavi (es. RSA, DH), cifratura simmetrica (es. AES-256-GCM), hash per MAC (es. SHA-256)." },
    { id:7, type:"mc", topic:"SSL Record",
      text:"Cosa fa il protocollo SSL Record Layer?",
      options:[
        "Gestisce l'handshake e la negoziazione",
        "Frammenta i dati, li cifra, aggiunge MAC e li trasmette",
        "Verifica i certificati digitali",
        "Gestisce le connessioni TCP"
      ],
      correct:1,
      explanation:"SSL Record Layer (livello inferiore): riceve i dati dall'applicazione, li frammenta in blocchi, comprime (opzionale), aggiunge MAC per l'integrità, cifra, aggiunge header SSL e invia via TCP." },
    { id:8, type:"open", topic:"Le 4 chiavi",
      text:"Perché SSL/TLS usa 4 chiavi diverse invece di una sola chiave simmetrica?",
      modelAnswer:"L'uso di 4 chiavi separate aumenta la sicurezza: 1) Chiavi di cifratura separate per ogni direzione (C→S e S→C): se un attaccante riesce a trovare una chiave di cifratura, non può decifrare il traffico nell'altra direzione. 2) Chiavi MAC separate per ogni direzione: protezione dell'integrità indipendente per ogni direzione. 3) Separazione tra cifratura e autenticazione: le due funzioni usano chiavi diverse, così una compromissione dell'integrità non compromette la confidenzialità. 4) Riduzione dell'esposizione: ogni chiave è usata per meno dati, aumentando la resistenza agli attacchi.",
      keywords:["4 chiavi","direzione","cifratura","MAC","separazione","sicurezza","compromissione","integrità","confidenzialità"] },
    { id:9, type:"mc", topic:"Sistema ibrido",
      text:"Come si chiama il modo in cui SSL/TLS usa la crittografia asimmetrica solo per lo scambio delle chiavi e quella simmetrica per i dati?",
      options:["Crittografia pubblica","Crittografia ibrida","Crittografia a strati","Crittografia duplice"],
      correct:1,
      explanation:"SSL/TLS usa un sistema ibrido: la crittografia asimmetrica (lenta) serve solo per scambiare in sicurezza la chiave di sessione durante l'handshake; la crittografia simmetrica (veloce) cifra poi tutto il traffico dati." },
    { id:10, type:"tf", topic:"Handshake",
      text:"Il master secret viene trasmesso direttamente dal client al server durante l'handshake SSL.",
      options:["Vero","Falso"],
      correct:1,
      explanation:"FALSO. Il master secret NON viene trasmesso. Viene calcolato in modo indipendente sia dal client che dal server a partire dal pre-master secret e dai due nonce (client e server). Solo il pre-master secret viene trasmesso (cifrato)." }
  ],

  /* ══════════════════════════════════════════════════════════════
     ARGOMENTO 11 — VPN
  ══════════════════════════════════════════════════════════════ */
  "vpn": [
    { id:1, type:"mc", topic:"VPN",
      text:"Cosa crea una VPN per garantire la sicurezza delle comunicazioni su Internet?",
      options:["Una linea dedicata fisica","Un tunnel crittografato virtuale","Una connessione MPLS","Un protocollo di routing sicuro"],
      correct:1,
      explanation:"Una VPN crea un tunnel crittografato (virtuale) su reti pubbliche (Internet), permettendo comunicazioni private come se si fosse su una rete dedicata." },
    { id:2, type:"mc", topic:"Tipologie VPN",
      text:"Quale tipo di VPN è usata per collegare permanentemente due sedi aziendali distinte?",
      options:["Remote-Access VPN","Site-to-Site VPN","SSL VPN","L2TP"],
      correct:1,
      explanation:"Site-to-Site VPN: collega permanentemente due sedi (reti LAN) attraverso Internet, sostituendo le costose linee dedicate. Usata tipicamente con IPsec." },
    { id:3, type:"mc", topic:"Protocolli VPN",
      text:"Quale protocollo VPN opera a livello di rete (Layer 3) ed è particolarmente usato per VPN aziendali site-to-site?",
      options:["SSL/TLS","OpenVPN","IPsec","PPTP"],
      correct:2,
      explanation:"IPsec opera a Layer 3 (livello IP), è trasparente alle applicazioni e garantisce alta sicurezza. Standard per VPN site-to-site aziendali." },
    { id:4, type:"tf", topic:"VPN SSL",
      text:"Una VPN SSL/TLS è più adatta per il remote-access perché funziona via browser senza richiedere software client specifico.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. Le VPN SSL/TLS operano a livello applicativo e possono funzionare via browser HTTPS, rendendole ideali per remote-access da qualsiasi dispositivo senza installare client VPN dedicati." },
    { id:5, type:"open", topic:"Tunneling",
      text:"Spiega il concetto di tunneling in una VPN.",
      modelAnswer:"Il tunneling è il processo con cui i pacchetti dati vengono incapsulati all'interno di altri pacchetti prima di essere trasmessi sulla rete pubblica. Il pacchetto originale (con IP privato sorgente e destinazione) viene cifrato e inserito nel payload di un nuovo pacchetto con intestazioni IP pubbliche. I router della rete pubblica vedono solo il pacchetto esterno e lo instradano verso il gateway VPN di destinazione. Il gateway rimuove l'incapsulamento, decifra e consegna il pacchetto originale alla rete privata. Questo crea un 'tunnel' logico privato attraverso la rete pubblica.",
      keywords:["tunneling","incapsulamento","pacchetto","IP privato","IP pubblico","gateway","decifra","tunnel logico"] },
    { id:6, type:"mc", topic:"Protocolli VPN",
      text:"WireGuard è descritto come:",
      options:[
        "Un protocollo VPN vecchio e insicuro",
        "Un protocollo VPN moderno e leggero con alte prestazioni",
        "Un protocollo per sole VPN aziendali",
        "Un'implementazione proprietaria Cisco"
      ],
      correct:1,
      explanation:"WireGuard è un protocollo VPN moderno (2020), open source, con codice base molto snello (~4000 righe vs 400.000 di OpenVPN), alta performance e crittografia state-of-the-art. Usato su Linux e per VPN personali." },
    { id:7, type:"mc", topic:"Confronto VPN",
      text:"IPsec vs SSL VPN: quale è tipicamente più facile da implementare per utenti remoti?",
      options:["IPsec","SSL VPN","Sono equivalenti","Dipende dalla LAN"],
      correct:1,
      explanation:"SSL VPN: più semplice per utenti remoti perché usa HTTPS (porta 443), funziona via browser, non richiede configurazioni di rete complesse e attraversa facilmente i firewall." },
    { id:8, type:"tf", topic:"Sicurezza VPN",
      text:"Una VPN garantisce sempre anonimato completo su Internet.",
      options:["Vero","Falso"],
      correct:1,
      explanation:"FALSO. Una VPN garantisce crittografia del traffico e nasconde il vero IP dall'ISP locale, ma non garantisce anonimato assoluto: il provider VPN può vedere il traffico, i siti visitati possono identificare l'utente con altri metodi (cookies, fingerprinting)." }
  ],

  /* ══════════════════════════════════════════════════════════════
     ARGOMENTO 12 — IPsec
  ══════════════════════════════════════════════════════════════ */
  "ipsec": [
    { id:1, type:"mc", topic:"IPsec",
      text:"IPsec opera a quale livello del modello OSI?",
      options:["Livello 2 (Data Link)","Livello 3 (Rete)","Livello 4 (Trasporto)","Livello 7 (Applicazione)"],
      correct:1,
      explanation:"IPsec lavora a livello 3 (Rete/IP): protegge qualsiasi comunicazione IP in modo trasparente alle applicazioni. Non è necessario modificare le applicazioni." },
    { id:2, type:"mc", topic:"AH vs ESP",
      text:"Quale protocollo IPsec fornisce ANCHE cifratura oltre all'autenticazione?",
      options:["AH (Authentication Header)","ESP (Encapsulating Security Payload)","IKE","SA"],
      correct:1,
      explanation:"ESP (protocollo IP 50): fornisce cifratura del payload + autenticazione. AH (protocollo IP 51): solo autenticazione, nessuna cifratura." },
    { id:3, type:"mc", topic:"Modalità",
      text:"Quale modalità IPsec aggiunge un nuovo header IP (nascondendo gli IP originali) ed è usata per VPN site-to-site?",
      options:["Modalità Trasporto","Modalità Tunnel","Modalità Proxy","Modalità Bridge"],
      correct:1,
      explanation:"Modalità Tunnel: aggiunge un nuovo header IP esterno e cifra/autentica l'intero pacchetto originale (header+payload). Gli IP originali sono nascosti. Usata per VPN site-to-site tra gateway." },
    { id:4, type:"open", topic:"IKE",
      text:"Descrivi le due fasi di IKE (Internet Key Exchange) in IPsec.",
      modelAnswer:"IKE Fase 1: Crea un canale di gestione sicuro (ISAKMP SA) per le negoziazioni. Negozia parametri (hash, DH group, cifratura, lifetime), esegue scambio Diffie-Hellman per le chiavi, autentica con PSK o certificati RSA. Due modalità: Main Mode (6 messaggi, sicuro, protegge identità) e Aggressive Mode (3 messaggi, veloce ma identità in chiaro). IKE Fase 2 (Quick Mode, 3 messaggi): dentro il tunnel sicuro di Fase 1, negozia le SA per il traffico dati: protocollo (AH/ESP), modalità (trasporto/tunnel), algoritmi, lifetime, PFS. Produce le SA usate da IPsec per cifrare il traffico reale.",
      keywords:["IKE Fase 1","IKE Fase 2","ISAKMP SA","Main Mode","Aggressive Mode","Quick Mode","Diffie-Hellman","SA","PFS"] },
    { id:5, type:"mc", topic:"SA",
      text:"Quante SA (Security Association) sono necessarie per una comunicazione IPsec bidirezionale?",
      options:["1","2","3","4"],
      correct:1,
      explanation:"Una SA protegge il traffico in una sola direzione. Per comunicazione bidirezionale servono 2 SA: una per A→B e una per B→A." },
    { id:6, type:"tf", topic:"AH",
      text:"AH (Authentication Header) è compatibile con NAT.",
      options:["Vero","Falso"],
      correct:1,
      explanation:"FALSO. AH autentica anche l'header IP originale (inclusi gli indirizzi IP). NAT modifica gli indirizzi IP, invalidando l'autenticazione AH. ESP con NAT-T (UDP 4500) è la soluzione standard." },
    { id:7, type:"mc", topic:"PFS",
      text:"PFS (Perfect Forward Secrecy) in IPsec significa che:",
      options:[
        "Le SA non scadono mai",
        "Ogni sessione usa chiavi derivate in modo indipendente (nuovo DH), così una chiave compromessa non espone le sessioni passate",
        "Il traffico è protetto anche senza autenticazione",
        "IPsec funziona senza IKE"
      ],
      correct:1,
      explanation:"PFS: in IKE Fase 2 si esegue un nuovo scambio DH per ogni SA, così le chiavi di sessione sono indipendenti dalla Fase 1. Se una chiave viene compromessa, non espone né passate né future sessioni." },
    { id:8, type:"mc", topic:"IKE",
      text:"IKEv2 rispetto a IKEv1 è:",
      options:[
        "Più lento ma più sicuro",
        "Più efficiente (4 messaggi per la Fase 1), supporta NAT-T nativo, EAP e keepalive integrato",
        "Equivalente ma con diversa numerazione dei messaggi",
        "Deprecato e non più usato"
      ],
      correct:1,
      explanation:"IKEv2: 4 messaggi invece di 6 per la Fase 1, NAT Traversal nativo, supporto EAP per autenticazione avanzata, keepalive integrato per rilevare connessioni cadute. Più robusto e sicuro." },
    { id:9, type:"open", topic:"IPsec",
      text:"Confronta la modalità Trasporto e la modalità Tunnel di IPsec.",
      modelAnswer:"Modalità Trasporto: il header IP originale rimane visibile, IPsec protegge solo il payload. Gli IP sorgente e destinazione originali sono visibili. Uso tipico: comunicazione sicura host-to-host all'interno di una rete. Modalità Tunnel: l'intero pacchetto originale (header + payload) viene protetto e incapsulato in un nuovo pacchetto IP con nuovi indirizzi. Gli IP originali sono nascosti. Uso tipico: VPN site-to-site tra gateway di due sedi. La modalità tunnel offre maggiore privacy perché nasconde anche l'identità dei nodi finali.",
      keywords:["trasporto","tunnel","header IP","payload","host-to-host","site-to-site","privacy","gateway","nascosti"] },
    { id:10, type:"tf", topic:"ESP",
      text:"ESP con NAT-T usa la porta UDP 4500 per funzionare attraverso i dispositivi NAT.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. NAT-T (NAT Traversal) incapsula ESP dentro pacchetti UDP sulla porta 4500, permettendo a IPsec di funzionare attraverso i dispositivi NAT. IKE usa normalmente UDP 500." }
  ],

  /* ══════════════════════════════════════════════════════════════
     ARGOMENTO 13 — Firewall e Architetture di Rete
  ══════════════════════════════════════════════════════════════ */
  "firewall": [
    { id:1, type:"mc", topic:"DMZ",
      text:"Qual è lo scopo principale di una DMZ (Demilitarized Zone)?",
      options:[
        "Bloccare tutto il traffico da Internet",
        "Ospitare server pubblici accessibili da Internet, isolandoli dalla LAN interna",
        "Aumentare la velocità della rete interna",
        "Sostituire il firewall principale"
      ],
      correct:1,
      explanation:"La DMZ è una zona intermedia tra Internet e la LAN interna. Ospita server accessibili pubblicamente (web, mail, DNS) in modo che la loro eventuale compromissione non comprometta direttamente la LAN." },
    { id:2, type:"mc", topic:"Firewall",
      text:"Quale tipo di firewall analizza il traffico fino al livello applicativo (Layer 7)?",
      options:["Packet Filter","Stateful Packet Inspection (SPI)","Circuit-Level Gateway","Application Gateway / Proxy"],
      correct:3,
      explanation:"Un Application Gateway (Proxy) agisce a livello 7: esamina il contenuto applicativo del traffico, comprende i protocolli (HTTP, FTP) e può prendere decisioni basate sul contenuto. Più sicuro ma più lento." },
    { id:3, type:"mc", topic:"Default policy",
      text:"Quale approccio di sicurezza è più sicuro per una policy firewall?",
      options:[
        "Default-Allow: tutto permesso tranne il vietato",
        "Default-Deny: tutto vietato tranne il permesso esplicitamente",
        "Sono equivalenti",
        "Dipende dalla topologia di rete"
      ],
      correct:1,
      explanation:"Default-Deny (principio del minimo privilegio): tutto il traffico è bloccato per default, si apre solo ciò che è esplicitamente necessario. Più sicuro: si riduce la superficie di attacco." },
    { id:4, type:"open", topic:"Tipologie firewall",
      text:"Confronta Packet Filter, SPI (Stateful Packet Inspection) e Proxy/Application Gateway.",
      modelAnswer:"Packet Filter (L3): analizza header IP e TCP/UDP (IP sorgente/destinazione, porte, protocollo). Velocissimo, semplice, ma senza stato — non riconosce se un pacchetto è parte di una connessione legittima. Bypassabile con IP spoofing. SPI (L3-L4): mantiene una state table con le connessioni attive. Controlla che ogni pacchetto sia parte di una connessione stabilita. Molto più sicuro del packet filter, difficile iniettare pacchetti falsi. Application Gateway/Proxy (L7): crea due connessioni separate (client→proxy, proxy→server). Analizza il contenuto applicativo, comprende i protocolli, può filtrare per contenuto. Massima sicurezza ma più lento, richiede un proxy per ogni protocollo.",
      keywords:["Packet Filter","SPI","state table","Proxy","L3","L4","L7","connessioni","contenuto"] },
    { id:5, type:"mc", topic:"NGFW",
      text:"Quale tecnologia AGGIUNTIVA caratterizza un NGFW (Next-Generation Firewall) rispetto a un firewall SPI tradizionale?",
      options:[
        "Solo la velocità maggiore",
        "DPI + IDS/IPS + App-ID + SSL inspection + policy per utente",
        "Solo il supporto IPv6",
        "La capacità di fare routing"
      ],
      correct:1,
      explanation:"NGFW integra SPI + Deep Packet Inspection (analisi contenuto) + IDS/IPS (rilevamento/prevenzione intrusioni) + identificazione applicazioni (App-ID) + SSL inspection + policy basate sull'utente (integrazione AD)." },
    { id:6, type:"tf", topic:"Limiti firewall",
      text:"Un firewall protegge anche dagli attacchi provenienti dall'interno della rete aziendale.",
      options:["Vero","Falso"],
      correct:1,
      explanation:"FALSO. Uno dei limiti principali del firewall perimetrale è che non filtra il traffico interno alla rete. Non protegge da insider threat, dipendenti malintenzionati o malware già all'interno della LAN." },
    { id:7, type:"mc", topic:"Architetture",
      text:"Quale architettura è considerata la più sicura per proteggere una rete con server pubblici?",
      options:[
        "Single-Homed Bastion Host",
        "Dual-Homed Bastion Host",
        "Screened Subnet con due firewall (DMZ)",
        "Solo NAT senza firewall"
      ],
      correct:2,
      explanation:"Screened Subnet (DMZ): Internet → Firewall esterno → DMZ (server pubblici) → Firewall interno → LAN. Due livelli di protezione: anche se la DMZ è compromessa, il firewall interno protegge la LAN." },
    { id:8, type:"open", topic:"Firewall",
      text:"Quali sono i principali limiti di un firewall? Come si può completare la difesa?",
      modelAnswer:"Limiti del firewall: 1) Non filtra traffico che non lo attraversa (attacchi interni). 2) Non protegge da minacce interne (insider). 3) Non ispeziona traffico cifrato senza SSL inspection. 4) Configurazione errata crea falso senso di sicurezza. 5) Non rileva malware nel traffico legittimo. 6) Non protegge da attacchi a livello applicativo senza DPI. Come completare la difesa: IDS/IPS (rilevamento intrusioni), antivirus/EDR sugli endpoint, segmentazione della rete (VLAN), VPN per accesso remoto, autenticazione forte (MFA), WAF (Web Application Firewall), aggiornamenti regolari, formazione utenti.",
      keywords:["limiti","traffico cifrato","interni","configurazione","IDS/IPS","antivirus","MFA","WAF","segmentazione","VLAN"] },
    { id:9, type:"mc", topic:"Bastion Host",
      text:"Un Bastion Host è:",
      options:[
        "Un router con funzioni di firewall",
        "Un server rinforzato posizionato in zona esposta, con OS hardened e servizi minimi",
        "Un firewall di tipo applicativo",
        "Il router del provider Internet"
      ],
      correct:1,
      explanation:"Bastion Host: server esposto alle reti non fidate, rinforzato (OS hardened, servizi minimi necessari, MFA obbligatoria, logging completo). Punto di contatto controllato tra reti di diversa affidabilità." },
    { id:10, type:"tf", topic:"SPI",
      text:"Un firewall SPI (Stateful Packet Inspection) traccia lo stato delle connessioni TCP per rilevare pacchetti inattesi.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. SPI mantiene una state table con le connessioni attive: sequence number TCP, flag (SYN/ACK/FIN), IP e porte. Un pacchetto che non corrisponde a nessuna connessione aperta viene bloccato." }
  ],

  /* ══════════════════════════════════════════════════════════════
     ARGOMENTO 14 — ACL (Access Control List)
  ══════════════════════════════════════════════════════════════ */
  "acl": [
    { id:1, type:"mc", topic:"ACL",
      text:"Come viene processata una ACL Cisco IOS quando arriva un pacchetto?",
      options:[
        "Vengono controllate tutte le regole e vince quella con priorità maggiore",
        "Lettura top-down: si applica la prima regola che corrisponde e si ferma",
        "Vengono controllate le regole in ordine inverso",
        "Si applica sempre l'ultima regola della lista"
      ],
      correct:1,
      explanation:"Le ACL Cisco vengono processate top-down: la prima regola che corrisponde al pacchetto viene applicata (permit o deny) e il processing si ferma. Se nessuna regola corrisponde → deny implicito." },
    { id:2, type:"tf", topic:"Deny implicito",
      text:"Alla fine di ogni ACL Cisco c'è un 'deny any' implicito che blocca tutto il traffico non esplicitamente permesso.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. Il deny implicito è fondamentale: se un pacchetto non corrisponde ad alcuna regola ACE, viene bloccato automaticamente. Bisogna sempre aggiungere un 'permit any' esplicito se si vuole permettere tutto il resto." },
    { id:3, type:"mc", topic:"ACL Standard vs Estesa",
      text:"Dove si posiziona una ACL Standard Cisco IOS?",
      options:[
        "Vicino alla sorgente, per bloccare il traffico il prima possibile",
        "Vicino alla destinazione, perché filtra solo l'IP sorgente",
        "Su entrambe le interfacce coinvolte",
        "Solo sull'interfaccia loopback"
      ],
      correct:1,
      explanation:"ACL Standard filtra solo l'IP sorgente. Posizionata vicino alla sorgente bloccherebbe anche traffico legittimo verso altre reti. Va posizionata vicino alla destinazione per bloccare solo il traffico verso quella specifica rete." },
    { id:4, type:"mc", topic:"ACL Estesa",
      text:"Un'ACL Estesa può filtrare su:",
      options:[
        "Solo IP sorgente",
        "Solo IP destinazione",
        "IP sorgente + IP destinazione + protocollo + porta",
        "Solo numero di porta"
      ],
      correct:2,
      explanation:"ACL Estesa (100-199, 2000-2699): filtra su IP sorgente, IP destinazione, protocollo (TCP/UDP/ICMP) e porta. Molto più granulare dell'ACL Standard." },
    { id:5, type:"open", topic:"Wildcard Mask",
      text:"Spiega la Wildcard Mask, come si calcola e i due casi speciali 'any' e 'host'.",
      modelAnswer:"La Wildcard Mask è una maschera a 32 bit dove: 0 = controlla il bit corrispondente (fisso), 1 = ignora il bit (qualsiasi valore). Calcolo: 255.255.255.255 - subnet mask. Esempio: /24 → 255.255.255.0 → wildcard = 0.0.0.255. Casi speciali: 'any' = 0.0.0.0 255.255.255.255 = qualsiasi indirizzo IP (tutti i bit ignorati). 'host X.X.X.X' = X.X.X.X 0.0.0.0 = esattamente quell'IP (tutti i bit controllati). Usata anche in OSPF per specificare quali reti annunciare e nelle ACL Cisco.",
      keywords:["wildcard","0=controlla","1=ignora","any","host","0.0.0.255","calcolo","subnet mask","OSPF"] },
    { id:6, type:"mc", topic:"Sintassi ACL",
      text:"Quale comando Cisco vieta tutto il traffico Telnet (porta 23) proveniente dalla rete 192.168.1.0/24?",
      options:[
        "access-list 10 deny 192.168.1.0",
        "access-list 110 deny tcp 192.168.1.0 0.0.0.255 any eq 23",
        "access-list 110 deny udp any any eq 23",
        "ip access-group 10 in"
      ],
      correct:1,
      explanation:"ACL Estesa (110), protocollo TCP, sorgente 192.168.1.0/24 (wildcard 0.0.0.255), destinazione any, porta destinazione 23 (Telnet). Sintassi corretta per bloccare Telnet da quella subnet." },
    { id:7, type:"mc", topic:"Inbound vs Outbound",
      text:"Quale direzione ACL è più efficiente dal punto di vista delle risorse del router?",
      options:[
        "Outbound, perché controlla dopo il routing",
        "Inbound, perché il pacchetto viene controllato prima che avvenga il routing",
        "Sono equivalenti",
        "Dipende dal tipo di traffico"
      ],
      correct:1,
      explanation:"Inbound è più efficiente: il pacchetto viene filtrato prima del processo di routing. Se viene bloccato, il router non spreca risorse per effettuare il lookup della route table." },
    { id:8, type:"open", topic:"ACL",
      text:"Dato lo scenario: bloccare tutto il traffico HTTP dalla rete 10.0.0.0/8 verso il server 172.16.1.10, permettendo tutto il resto. Scrivi l'ACL Estesa Cisco.",
      modelAnswer:"access-list 110 deny tcp 10.0.0.0 0.255.255.255 host 172.16.1.10 eq 80\naccess-list 110 permit ip any any\n\nSpiegazione: 1) L'ACL Estesa 110 blocca TCP dalla rete 10.x.x.x (wildcard 0.255.255.255) verso l'host 172.16.1.10 sulla porta 80 (HTTP). 2) Il secondo ACE permette tutto il resto. 3) L'ACL va applicata vicino alla sorgente (su interfaccia verso 10.0.0.0): ip access-group 110 in.",
      keywords:["access-list 110","deny tcp","10.0.0.0","0.255.255.255","host","eq 80","permit ip any any","ip access-group"] },
    { id:9, type:"mc", topic:"Comandi verifica",
      text:"Quale comando Cisco mostra le ACL con i contatori dei match (numero di pacchetti che hanno corrisposto)?",
      options:["show ip route","show running-config","show ip access-lists","debug ip packet"],
      correct:2,
      explanation:"'show ip access-lists' mostra le ACL con i contatori per ogni ACE: quanti pacchetti hanno corrisposto a ogni regola. Utile per verificare se le ACL funzionano come atteso." },
    { id:10, type:"tf", topic:"ACL",
      text:"Le ACL nominative (named ACL) Cisco funzionano esattamente come le ACL numeriche ma permettono di usare un nome stringa invece di un numero.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. Le ACL nominative usano un nome al posto del numero, rendendo più comprensibile la configurazione. Aggiungono anche la possibilità di eliminare singoli ACE (nelle ACL numeriche si deve riscrivere l'intera lista)." }
  ],

  /* ══════════════════════════════════════════════════════════════
     ARGOMENTO 15 — IDS, IPS e Sicurezza Perimetrale
  ══════════════════════════════════════════════════════════════ */
  "ids-ips": [
    { id:1, type:"mc", topic:"IDS vs IPS",
      text:"Quale è la differenza fondamentale tra IDS e IPS?",
      options:[
        "IDS lavora a livello hardware, IPS a livello software",
        "IDS rileva e segnala (passivo), IPS rileva E blocca attivamente",
        "IDS è per reti wireless, IPS per reti cablate",
        "Non ci sono differenze significative"
      ],
      correct:1,
      explanation:"IDS (Intrusion Detection System): passivo, rileva e genera allarmi ma non blocca il traffico. IPS (Intrusion Prevention System): attivo, posizionato inline, blocca automaticamente il traffico malevolo." },
    { id:2, type:"mc", topic:"NIDS",
      text:"Come viene tipicamente collegato un NIDS alla rete per analizzare il traffico?",
      options:[
        "Inline nel percorso del traffico come un IPS",
        "Via port mirroring (SPAN) o TAP ottico",
        "Installato come agent su ogni host",
        "Connesso al server DNS"
      ],
      correct:1,
      explanation:"Un NIDS è passivo: riceve una copia del traffico tramite port mirroring (porta SPAN dello switch) o TAP hardware, senza essere nel percorso diretto del traffico." },
    { id:3, type:"mc", topic:"Rilevamento",
      text:"Quale tecnica di rilevamento IDS/IPS è in grado di rilevare attacchi 'zero-day' ma genera più falsi positivi?",
      options:[
        "Misuse Detection (signature-based)",
        "Anomaly Detection (rilevamento anomalie rispetto alla baseline)",
        "Stateful Inspection",
        "Deep Packet Inspection"
      ],
      correct:1,
      explanation:"Anomaly Detection: definisce una baseline del comportamento normale e rileva deviazioni. Può rilevare attacchi nuovi (zero-day) non ancora catalogati, ma genera più falsi positivi perché comportamenti legittimi inusuali vengono segnalati." },
    { id:4, type:"open", topic:"RADIUS",
      text:"Descrivi il protocollo RADIUS e il flusso di autenticazione AAA.",
      modelAnswer:"RADIUS (Remote Authentication Dial-In User Service): protocollo AAA su UDP, porte 1812 (autenticazione) e 1813 (accounting). Cifra solo la password (il resto è in chiaro). Flusso: 1. Client (utente) invia credenziali al NAS (Network Access Server, es. AP Wi-Fi, switch 802.1X). 2. Il NAS invia Access-Request al server RADIUS. 3. Il server RADIUS verifica le credenziali (database locale, LDAP, AD). 4. RADIUS risponde con Access-Accept (+ attributi: VLAN, policy) o Access-Reject. 5. Il NAS concede o nega l'accesso al client. RADIUS è standard aperto, usato per Wi-Fi enterprise (WPA2-Enterprise), VPN e accesso remoto.",
      keywords:["RADIUS","UDP","1812","1813","NAS","Access-Request","Access-Accept","Access-Reject","autenticazione","AAA"] },
    { id:5, type:"mc", topic:"TACACS+",
      text:"Quale differenza principale ha TACACS+ rispetto a RADIUS?",
      options:[
        "TACACS+ usa UDP, RADIUS usa TCP",
        "TACACS+ cifra l'intero payload, RADIUS solo la password",
        "TACACS+ è uno standard aperto, RADIUS è proprietario Cisco",
        "Non ci sono differenze significative"
      ],
      correct:1,
      explanation:"TACACS+: TCP porta 49, cifra l'intero payload (più sicuro), separa completamente le 3 funzioni AAA. RADIUS: UDP, cifra solo la password. TACACS+ è proprietario Cisco, usato per accesso amministrativo ai dispositivi Cisco." },
    { id:6, type:"tf", topic:"MFA",
      text:"TOTP (Time-based One-Time Password) genera un codice OTP che rimane valido per 30 secondi, poi viene rigenerato.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. TOTP (RFC 6238): codice a 6 cifre derivato da chiave segreta + timestamp attuale (a step di 30 secondi). Usato da Google Authenticator, Microsoft Authenticator ecc." },
    { id:7, type:"mc", topic:"IPS",
      text:"Un IPS inline può eseguire quali azioni automatiche quando rileva un attacco?",
      options:[
        "Solo registrare un log",
        "Solo inviare un'email all'amministratore",
        "Drop pacchetti, TCP reset, blocco IP sorgente, avviso admin",
        "Solo rallentare il traffico"
      ],
      correct:2,
      explanation:"Un IPS inline può: scartare (drop) i pacchetti malevoli, inviare TCP reset per chiudere la connessione, bloccare l'IP sorgente (temporaneamente o definitivamente), inviare alert/avvisi all'amministratore, modificare i pacchetti." },
    { id:8, type:"mc", topic:"HIDS",
      text:"Quale vantaggio ha un HIDS (Host-based IDS) rispetto a un NIDS?",
      options:[
        "Visibilità sull'intera rete",
        "Analizza il traffico già decifrato e le attività locali (log, processi, file)",
        "Non richiede agenti software",
        "Scala meglio su reti grandi"
      ],
      correct:1,
      explanation:"HIDS: installato sull'host, analizza log di sistema, integrità dei file critici, processi in esecuzione e traffico già decifrato. Vede cosa accade all'interno del sistema, non solo il traffico di rete." },
    { id:9, type:"open", topic:"AAA",
      text:"Spiega il modello AAA (Authentication, Authorization, Accounting) con esempi pratici.",
      modelAnswer:"Authentication (Autenticazione): verifica l'identità dell'utente. 'Chi sei?' — esempio: inserire username e password per accedere alla VPN. Authorization (Autorizzazione): definisce cosa l'utente autenticato può fare. 'Cosa puoi fare?' — esempio: l'utente può accedere ai server web ma non al server del database. Accounting (Contabilità): registra le attività dell'utente. 'Cosa hai fatto?' — esempio: login alle 9:15, logout alle 17:30, file scaricati, comandi eseguiti. Implementato tipicamente con RADIUS o TACACS+. Importanti per compliance, audit e rilevamento anomalie.",
      keywords:["Authentication","Authorization","Accounting","identità","permessi","log","RADIUS","TACACS+","audit","compliance"] },
    { id:10, type:"tf", topic:"IDS",
      text:"Un IDS basato su signature (misuse detection) può rilevare efficacemente attacchi zero-day non ancora nel database delle firme.",
      options:["Vero","Falso"],
      correct:1,
      explanation:"FALSO. Gli IDS signature-based confrontano il traffico con un database di firme di attacchi noti. Non possono rilevare attacchi zero-day (sconosciuti) finché non viene creata e distribuita la firma corrispondente." }
  ],

  /* ══════════════════════════════════════════════════════════════
     ARGOMENTO 16 — Infrastruttura IT: Cloud, Virtualizzazione, AD
  ══════════════════════════════════════════════════════════════ */
  "cloud": [
    { id:1, type:"mc", topic:"Cloud",
      text:"Quale modello di servizio cloud fornisce solo l'infrastruttura virtuale (VM, storage, rete)?",
      options:["SaaS","PaaS","IaaS","FaaS"],
      correct:2,
      explanation:"IaaS (Infrastructure as a Service): fornisce risorse virtuali di base (VM, storage, rete) — es. AWS EC2, Azure VM. Il cliente gestisce il SO e le applicazioni." },
    { id:2, type:"mc", topic:"Hypervisor",
      text:"Quale tipo di hypervisor funziona direttamente sull'hardware fisico, senza un OS host sottostante?",
      options:["Type 2 (Hosted)","Type 1 (Bare Metal)","Type 3 (Container)","VMM (Virtual Machine Monitor)"],
      correct:1,
      explanation:"Hypervisor Type 1 (Bare Metal): direttamente sull'hardware — es. VMware ESXi, Microsoft Hyper-V, Proxmox. Prestazioni ottimali, usato nei datacenter." },
    { id:3, type:"mc", topic:"Backup",
      text:"La regola 3-2-1 del backup prevede:",
      options:[
        "3 backup full, 2 incrementali, 1 differenziale",
        "3 copie dei dati, su 2 supporti diversi, con 1 copia fuori sede",
        "Backup ogni 3 ore, 2 ore, 1 ora",
        "3 server, 2 RAID, 1 cloud"
      ],
      correct:1,
      explanation:"Regola 3-2-1: almeno 3 copie dei dati, su 2 tipi di supporto diversi (es. disco + nastro), con almeno 1 copia in una location fisica diversa (fuori sede o cloud). Protegge da guasti hardware, disastri fisici e ransomware." },
    { id:4, type:"open", topic:"Active Directory",
      text:"Cos'è Active Directory e quali sono i suoi componenti principali?",
      modelAnswer:"Active Directory (AD) è il servizio Microsoft per la gestione centralizzata di utenti, computer, gruppi e policy di sicurezza in un'organizzazione. Componenti principali: Domain Controller (DC): server che ospita il database AD, gestisce autenticazione (Kerberos/NTLM) e replica. Domain: raggruppamento logico di risorse con una sola policy di sicurezza. OU (Organizational Unit): contenitore per organizzare utenti e computer (es. per reparto o sede). GPO (Group Policy Object): regole applicate automaticamente a utenti/computer (blocco USB, screensaver, Windows Update). Forest/Tree: struttura gerarchica di più domini. SSO (Single Sign-On): un'unica autenticazione per accedere a tutte le risorse autorizzate.",
      keywords:["Active Directory","Domain Controller","Domain","OU","GPO","SSO","Kerberos","Forest","autenticazione"] },
    { id:5, type:"mc", topic:"Clustering",
      text:"In un cluster Active-Passive, cosa succede quando il nodo primario va offline?",
      options:[
        "Il servizio si interrompe definitivamente",
        "Il nodo secondario (standby) prende automaticamente il controllo (failover)",
        "Tutti i nodi diventano primari",
        "Il sistema passa in modalità solo lettura"
      ],
      correct:1,
      explanation:"Active-Passive: un nodo è attivo, uno è standby. Se il primario cade, il nodo standby rileva il guasto e prende automaticamente il controllo (failover), minimizzando il downtime." },
    { id:6, type:"tf", topic:"Backup",
      text:"Il backup incrementale include solo le modifiche apportate dall'ultimo backup (full O incrementale), rendendolo veloce ma il ripristino più complesso.",
      options:["Vero","Falso"],
      correct:0,
      explanation:"VERO. Backup incrementale: veloce (pochi dati da salvare), ma per il ripristino servono l'ultimo full + TUTTI gli incrementali in sequenza. Se uno è corrotto, il ripristino potrebbe fallire." },
    { id:7, type:"mc", topic:"RTO/RPO",
      text:"RPO (Recovery Point Objective) definisce:",
      options:[
        "Il tempo massimo per ripristinare il sistema",
        "La quantità massima di dati persi accettabile (in tempo)",
        "Il numero massimo di backup da conservare",
        "Il costo del ripristino"
      ],
      correct:1,
      explanation:"RPO: Recovery Point Objective — quanti dati persi sono accettabili, espresso come intervallo temporale. Es. RPO=1h significa che si può perdere al massimo 1 ora di dati → backup ogni ora. RTO è il tempo per ripristinare." },
    { id:8, type:"mc", topic:"Cloud",
      text:"Qual è la differenza principale tra IaaS e PaaS?",
      options:[
        "IaaS fornisce applicazioni complete, PaaS solo storage",
        "IaaS fornisce infrastruttura virtuale (VM/rete), PaaS fornisce una piattaforma di sviluppo già gestita",
        "IaaS è più costoso di PaaS in tutti i casi",
        "Sono la stessa cosa con nome diverso"
      ],
      correct:1,
      explanation:"IaaS: VM, storage, rete — il cliente gestisce SO e applicazioni. PaaS: piattaforma di sviluppo gestita (runtime, middleware, database) — il cliente gestisce solo le applicazioni. Es. IaaS: AWS EC2; PaaS: Google App Engine, Heroku." },
    { id:9, type:"open", topic:"Virtualizzazione",
      text:"Quali sono i vantaggi della virtualizzazione dei server rispetto all'uso di server fisici dedicati?",
      modelAnswer:"1. Consolidamento: più VM su un solo hardware fisico, riducendo il numero di server necessari. 2. Risparmio energetico: meno hardware → meno consumo elettrico e raffreddamento. 3. Isolamento: ogni VM è isolata dalle altre — un crash non impatta le altre. 4. Snapshot: possibilità di salvare e ripristinare lo stato di una VM in pochi secondi. 5. Live Migration: spostare VM tra host senza interruzione del servizio. 6. Provisioning rapido: creare nuovi server in minuti. 7. Alta disponibilità: in caso di guasto hardware, le VM si riavviano automaticamente su altri host.",
      keywords:["consolidamento","isolamento","snapshot","live migration","provisioning","alta disponibilità","risparmio","VM"] },
    { id:10, type:"tf", topic:"Clustering",
      text:"Un cluster ad alta disponibilità sostituisce completamente la necessità di backup: se un nodo cade, i dati sono al sicuro sugli altri nodi.",
      options:["Vero","Falso"],
      correct:1,
      explanation:"FALSO. Clustering ≠ backup! Un cluster distribuisce il servizio su più nodi, ma tutti i nodi accedono agli stessi dati. Un ransomware che cifra i dati li cifra su tutti i nodi simultaneamente. Il backup è separato e indispensabile." }
  ],

  /* ══════════════════════════════════════════════════════════════
     ARGOMENTO 17 — Laboratorio Packet Tracer (Cisco)
  ══════════════════════════════════════════════════════════════ */
  "packet-tracer": [
    { id:1, type:"mc", topic:"Modalità IOS",
      text:"In quale modalità Cisco IOS si può configurare un indirizzo IP su un'interfaccia?",
      options:[
        "User EXEC (>)",
        "Privileged EXEC (#)",
        "Interface Configuration (config-if)#",
        "Global Configuration (config)#"
      ],
      correct:2,
      explanation:"Per configurare un'interfaccia: configure terminal → interface fa0/0 → ip address x.x.x.x mask → no shutdown. Si deve essere in modalità Interface Configuration." },
    { id:2, type:"mc", topic:"Comandi show",
      text:"Quale comando Cisco mostra le traduzioni NAT attive?",
      options:["show ip route","show ip nat translations","show ip access-lists","show interfaces"],
      correct:1,
      explanation:"'show ip nat translations' mostra la tabella NAT attiva con le mappature IP privato:porta ↔ IP pubblico:porta delle sessioni correnti." },
    { id:3, type:"mc", topic:"RIPv2",
      text:"Quale comando impedisce a RIPv2 di eseguire l'auto-summarization delle rotte?",
      options:["no ip routing","no rip","no auto-summary","no version 2"],
      correct:2,
      explanation:"'no auto-summary' disabilita la summarizzazione automatica delle rotte alle classi di default. Fondamentale con VLSM/CIDR per evitare perdita di rotte specifiche." },
    { id:4, type:"open", topic:"Routing statico",
      text:"Scrivi i comandi Cisco IOS per configurare una rotta statica verso la rete 10.0.0.0/8 tramite il next-hop 192.168.1.254.",
      modelAnswer:"R1(config)# ip route 10.0.0.0 255.0.0.0 192.168.1.254\n\nSpiegazione: 'ip route [rete destinazione] [subnet mask] [next-hop o interfaccia]'. La rete 10.0.0.0 con maschera 255.0.0.0 (/8) viene raggiunta tramite il router 192.168.1.254. Per verificare: show ip route. Si può aggiungere una distanza amministrativa come quarto parametro per le floating static routes.",
      keywords:["ip route","10.0.0.0","255.0.0.0","192.168.1.254","next-hop","show ip route"] },
    { id:5, type:"mc", topic:"Interfacce",
      text:"Cosa fa il comando 'no shutdown' su un'interfaccia Cisco?",
      options:[
        "Disabilita l'interfaccia",
        "Abilita l'interfaccia (la porta è disabilitata per default sui router Cisco)",
        "Rimuove la configurazione IP",
        "Riavvia il router"
      ],
      correct:1,
      explanation:"Le interfacce dei router Cisco sono disabilitate (shutdown) per default. Il comando 'no shutdown' le abilita. Su switch le porte sono attive per default." },
    { id:6, type:"mc", topic:"Cavi",
      text:"In Packet Tracer, quale tipo di cavo si usa per collegare due PC direttamente (senza switch)?",
      options:["Straight-through (diritto)","Crossover","Serial DCE","Fiber"],
      correct:1,
      explanation:"Cavo crossover: per collegare dispositivi dello stesso tipo (PC-PC, switch-switch, router-router senza MDIX). Cavo straight-through: per dispositivi diversi (PC-switch, router-switch)." },
    { id:7, type:"open", topic:"Verifica",
      text:"Descrivi come verificare la connettività in Packet Tracer dopo aver configurato una rete.",
      modelAnswer:"1. ping: dal PC o dal router, eseguire 'ping [indirizzo IP]' per verificare la raggiungibilità. Un ping riuscito mostra '!!!!!', uno fallito '.....' 2. traceroute/tracert: verificare il percorso hop-per-hop. Da PC Windows: tracert. Da router Cisco: traceroute. 3. show ip route: verificare che le rotte siano presenti nella tabella di routing (C=connected, S=static, R=RIP). 4. show interfaces: verificare che le interfacce siano 'up/up'. 5. show ip protocols: verificare i protocolli di routing attivi. 6. show ip rip database (se RIP): verificare le rotte apprese.",
      keywords:["ping","traceroute","show ip route","show interfaces","show ip protocols","up/up","verifica"] },
    { id:8, type:"mc", topic:"Comandi show",
      text:"Nell'output di 'show ip route', cosa indica la lettera 'R' a inizio riga?",
      options:[
        "Una rotta statica configurata manualmente",
        "Una rotta appresa tramite RIP",
        "Una rete direttamente connessa",
        "Una rotta OSPF"
      ],
      correct:1,
      explanation:"Nelle tabelle di routing Cisco: C = Connected (direttamente connessa), S = Static (statica), R = RIP, O = OSPF, B = BGP, D = EIGRP, * = default route." }
  ]

}; // fine window.QUIZ_DATA
