/* =========================================================================
   flashcard-data.js — Banca flashcard per autore
   Minimo 20 carte per autore: date, poetica, opere, testi, figure, confronti.
   ========================================================================= */
window.flashcardData = {

  verga: [
    { fronte: "Anni di nascita e morte di Verga", retro: "1840 – 1922, Catania" },
    { fronte: "Cos'è la «svolta verista»?", retro: "Dal 1878 (Rosso Malpelo) abbandona il romanzo mondano e adotta l'impersonalità naturalista applicata al Sud rurale." },
    { fronte: "Cos'è l'impersonalità verghiana?", retro: "L'autore si eclissa: «la mano dell'artista deve restare invisibile». Non è metodo scientifico ma conseguenza del pessimismo." },
    { fronte: "Cos'è la regressione del narratore?", retro: "L'autore scende al livello culturale e linguistico dei personaggi, adottandone mentalità e logica." },
    { fronte: "Cos'è il Discorso Indiretto Libero (DIL)?", retro: "Pensieri e parole dei personaggi senza virgolette né verba dicendi: si fonde la voce del narratore con quella del personaggio." },
    { fronte: "Cos'è la «fiumana del progresso»?", retro: "Metafora (Prefazione ai Malavoglia): il progresso come forza cieca che travolge i deboli, i «vinti», senza beneficarli." },
    { fronte: "Cos'è l'«ideale dell'ostrica»?", retro: "Da Fantasticheria: per sopravvivere bisogna restare attaccati al proprio ambiente come l'ostrica allo scoglio; chi si stacca è divorato." },
    { fronte: "Chi è Rosso Malpelo?", retro: "Bambino dai capelli rossi che lavora in una cava di rena. Escluso per pregiudizio, non per colpa: muore nelle gallerie." },
    { fronte: "Cos'è «la roba» per Mazzarò?", retro: "L'unica forma di identità e riscatto: l'accumulo ossessivo di beni. Ma alla morte non si può portare nulla." },
    { fronte: "Che cos'è il Ciclo dei Vinti?", retro: "Progetto di 5 romanzi sulla scala sociale: realizzati solo I Malavoglia (1881) e Mastro-don Gesualdo (1889)." },
    { fronte: "Trama de I Malavoglia (1881)", retro: "La famiglia Toscano di Aci Trezza perde la casa del nespolo dopo il naufragio della Provvidenza. Chi resta (Alessi) si salva; chi parte ('Ntoni) si perde." },
    { fronte: "Il significato del titolo «Mastro-don Gesualdo»", retro: "Mastro (manovale) + Don (notabile): due identità incompatibili. Gesualdo vince economicamente ma muore solo." },
    { fronte: "Prima raccolta verista di Verga", retro: "Vita dei campi (1880): Rosso Malpelo, La lupa, Cavalleria rusticana, Fantasticheria." },
    { fronte: "Tema centrale di Novelle rusticane (1883)", retro: "La «roba»: l'ossessione per i beni materiali e l'interesse economico. Contiene La roba e Libertà." },
    { fronte: "Cos'è lo straniamento in Verga?", retro: "Fatti assurdi presentati come normali (e viceversa) dal narratore regredito: il lettore vede l'assurdità che i personaggi non vedono." },
    { fronte: "Differenza Verga vs Zola", retro: "Stessa impersonalità, ragioni opposte: Zola per metodo scientifico e fiducia nel progresso; Verga per pessimismo filosofico, senza riscatto." },
    { fronte: "Differenza Verga vs Manzoni", retro: "Stesso interesse per gli umili, ma Verga non ha narratore onnisciente né Provvidenza: solo distacco e pessimismo." },
    { fronte: "Da quale corrente nasce il Verismo?", retro: "Dal Naturalismo francese di Zola, ma con pessimismo più radicale e ambientazione nel Sud arcaico." },
    { fronte: "Cosa fa Verga dal 1893?", retro: "Torna a Catania e smette di scrivere: silenzio letterario quasi trentennale. Il ciclo resta incompiuto." },
    { fronte: "Il finale de I Malavoglia", retro: "'Ntoni torna di notte, ma la casa è «veleno»: «Ora che so ogni cosa devo andarmene». La conoscenza come condanna." }
  ],

  pascoli: [
    { fronte: "Anni di nascita e morte di Pascoli", retro: "1855 – 1912, San Mauro di Romagna" },
    { fronte: "Il trauma fondativo di Pascoli", retro: "L'assassinio del padre Ruggero il 10 agosto 1867, rimasto impunito: il «nido» spezzato." },
    { fronte: "Cos'è il «fanciullino»?", retro: "La voce interiore infantile che vede il mondo con meraviglia e crea poesia per intuizione. Saggio del 1897." },
    { fronte: "Cos'è il «nido»?", retro: "La casa e la famiglia come rifugio dal male esterno: luogo affettivo ma fragile, sempre minacciato." },
    { fronte: "Cos'è il fonosimbolismo?", retro: "Il suono delle parole vale quanto il significato: onomatopee, allitterazioni riproducono la natura («bubbolìo»)." },
    { fronte: "Prima e più celebre raccolta di Pascoli", retro: "Myricae (1891): le piccole cose, la natura, la morte, la memoria. Il titolo richiama le umili tamerici virgiliane." },
    { fronte: "Raccolta dedicata alla madre", retro: "Canti di Castelvecchio: il nido, le stagioni, la campagna, i suoni naturali." },
    { fronte: "Tema di X Agosto", retro: "Il lutto per il padre: parallelo rondine/padre uccisi mentre tornano al nido. «Disse: Perché?»" },
    { fronte: "Tema di Lavandare", retro: "L'abbandono: l'aratro senza buoi e il canto delle lavandaie. «Nessuno attende a casa.»" },
    { fronte: "Tema de L'assiuolo", retro: "Il verso «Chiù» dell'assiuolo come eco di morte; il fantasma della sorella che passa nell'alba." },
    { fronte: "Tema di Novembre", retro: "L'inganno delle apparenze: una scena apparentemente primaverile si rovescia nell'«estate fredda dei morti» (ossimoro)." },
    { fronte: "Tema de Il gelsomino notturno", retro: "La vita che nasce nel buio (la notte di nozze); il poeta escluso, che pensa ai suoi morti." },
    { fronte: "Cos'è il poemetto Italy?", retro: "Dai Poemetti: l'emigrazione, il ritorno dei figli con lingua ibrida italo-inglese, la morte della piccola Molly." },
    { fronte: "Cos'è La grande proletaria si è mossa?", retro: "Discorso del 1911 che giustifica la guerra di Libia: la fase civile e nazionalista di Pascoli." },
    { fronte: "Differenza Pascoli vs D'Annunzio", retro: "I due poli del Decadentismo italiano: il fanciullino (Pascoli) contro il vate-superuomo (D'Annunzio)." },
    { fronte: "Differenza Pascoli e Leopardi", retro: "Entrambi leggono dolore e natura, ma Leopardi tende alla natura matrigna; Pascoli alla natura simbolica e ai legami familiari." },
    { fronte: "A quale corrente è legato Pascoli?", retro: "Al Simbolismo/Decadentismo italiano, in chiave dimessa e domestica." },
    { fronte: "Figura retorica tipica di Pascoli", retro: "L'onomatopea e l'analogia; lo stile «franto», impressionistico." },
    { fronte: "Cosa rappresenta la rondine in X Agosto", retro: "Il padre che torna al nido e viene ucciso; «come in croce» con il verme in bocca: il male cosmico." },
    { fronte: "Il rovesciamento finale de L'assiuolo", retro: "Il «chiù» da suono notturno diventa voce dall'aldilà; «Il mio cuore si è rotto»." }
  ],

  dannunzio: [
    { fronte: "Anni di nascita e morte di D'Annunzio", retro: "1863 – 1938, Pescara" },
    { fronte: "Cos'è l'estetismo dannunziano?", retro: "La vita come opera d'arte; il culto della bellezza e del piacere. Modello: Andrea Sperelli ne Il piacere." },
    { fronte: "Cos'è il superuomo dannunziano?", retro: "Da Nietzsche: l'uomo superiore che si pone oltre la morale comune, dominatore ed esteta." },
    { fronte: "Cos'è il panismo?", retro: "La fusione totale dell'io con la natura (da «Pan»): l'uomo che si dissolve nelle forze naturali. Vertice in Alcyone." },
    { fronte: "Il romanzo dell'estetismo", retro: "Il piacere (1889): Andrea Sperelli, il dandy che vive secondo «fare della propria vita un'opera d'arte»." },
    { fronte: "Il capolavoro lirico di D'Annunzio", retro: "Alcyone (1903): l'estate, il panismo, La pioggia nel pineto, La sera fiesolana." },
    { fronte: "Tema de La pioggia nel pineto", retro: "Il panismo: l'io e l'amata Ermione si trasformano in creature vegetali sotto la pioggia. Musicalità e sinestesia." },
    { fronte: "Cos'è la «fase notturna»?", retro: "Il Notturno (1916): prosa frammentaria scritta da quasi cieco, più intima e meditativa." },
    { fronte: "Figura retorica tipica di D'Annunzio", retro: "La sinestesia e l'analogia; la musicalità del verso, l'allitterazione." },
    { fronte: "D'Annunzio e la politica", retro: "Interventista, eroe di guerra, l'impresa di Fiume (1919): il «vate» che fa della vita un gesto pubblico." },
    { fronte: "Cos'è il «vate»?", retro: "Il poeta-profeta che guida la nazione, modella i miti collettivi: D'Annunzio incarna questo ruolo." },
    { fronte: "I tre romanzi della «rosa»", retro: "Il piacere, L'innocente, Il trionfo della morte: i romanzi dell'estetismo e del superuomo." },
    { fronte: "Differenza D'Annunzio vs Verga", retro: "Opposti: D'Annunzio esalta l'io e il trionfo; Verga lo cancella e descrive la sconfitta dei vinti." },
    { fronte: "Differenza D'Annunzio vs Pascoli", retro: "I due poli del Decadentismo: il vate-superuomo contro il poeta-fanciullino." },
    { fronte: "La raccolta poetica maggiore", retro: "Le Laudi (Maia, Elettra, Alcyone): Alcyone è il libro dell'estate e del panismo." },
    { fronte: "Cosa significa «fare della propria vita un'opera d'arte»?", retro: "L'estetismo applicato all'esistenza: vivere con la massima intensità ed eleganza, come un personaggio." },
    { fronte: "L'influenza filosofica su D'Annunzio", retro: "Nietzsche (superuomo, volontà di potenza) e l'estetismo europeo (Wilde, Pater, Huysmans)." },
    { fronte: "Cos'è la sinestesia?", retro: "La fusione di sensazioni di sensi diversi (es. «verde silenzio»): figura chiave dello stile dannunziano." },
    { fronte: "Tema de La sera fiesolana", retro: "Il paesaggio toscano al tramonto come esperienza panica e religiosa; lode della sera e della natura." },
    { fronte: "Perché D'Annunzio è «decadente»", retro: "Per l'estetismo, il culto della bellezza e del piacere, la sensibilità sovraeccitata, il rifiuto del borghese." }
  ],

  pirandello: [
    { fronte: "Anni di nascita e morte di Pirandello", retro: "1867 – 1936, Agrigento. Nobel 1934." },
    { fronte: "Cos'è l'umorismo pirandelliano?", retro: "«Avvertimento» del contrario (comico) + «sentimento» del contrario (riflessione che lo rende pietoso): saggio L'umorismo (1908)." },
    { fronte: "Cos'è il relativismo conoscitivo?", retro: "Non esiste una verità oggettiva: ognuno ha la propria. La realtà dipende dal punto di vista." },
    { fronte: "Cos'è il contrasto «vita» e «forma»?", retro: "La vita è flusso continuo; la forma è la maschera fissa che la società ci impone. L'uomo soffoca nelle forme." },
    { fronte: "Cos'è la «maschera»?", retro: "L'identità sociale fittizia imposta dagli altri; sotto, nessun volto stabile. «Uno, nessuno e centomila»." },
    { fronte: "Trama de Il fu Mattia Pascal (1904)", retro: "Mattia, creduto morto, prova una nuova identità (Adriano Meis) ma scopre che senza stato civile non si può vivere: torna «il fu»." },
    { fronte: "Trama di Uno, nessuno e centomila", retro: "Vitangelo Moscarda scopre di essere visto in centomila modi diversi; distrugge la propria identità per liberarsi delle forme." },
    { fronte: "Cos'è il «teatro nel teatro»?", retro: "La trilogia metateatrale: Sei personaggi in cerca d'autore mostra la finzione teatrale stessa sulla scena." },
    { fronte: "Trama di Sei personaggi in cerca d'autore", retro: "Sei personaggi irrompono in un teatro chiedendo a una compagnia di rappresentare il loro dramma: realtà e finzione si confondono." },
    { fronte: "Cos'è Enrico IV?", retro: "Dramma: un uomo che, creduto pazzo, finge di essere l'imperatore Enrico IV; la maschera della follia come rifugio." },
    { fronte: "Raccolta di novelle di Pirandello", retro: "Novelle per un anno: 365 novelle progettate; la condizione umana còlta in episodi paradossali." },
    { fronte: "Cos'è la «trappola»?", retro: "La vita sociale (famiglia, lavoro, ruoli) come trappola che imprigiona l'individuo nelle forme." },
    { fronte: "Differenza Pirandello vs Verga", retro: "Entrambi siciliani, ma Verga attribuisce la sconfitta a leggi naturali; Pirandello alla struttura relativa di realtà e identità." },
    { fronte: "Differenza Pirandello vs Svevo", retro: "Entrambi indagano la crisi dell'io: Svevo con la psicanalisi e l'ironia; Pirandello con il relativismo e la maschera." },
    { fronte: "Cos'è il «forestiere della vita»?", retro: "Chi, vedendosi vivere dall'esterno, si sente estraneo a sé e al mondo: condizione tipica dei personaggi pirandelliani." },
    { fronte: "Periodo del «teatro grottesco»", retro: "Anni '10–'20: drammi che smascherano l'ipocrisia borghese (Così è (se vi pare), Il berretto a sonagli)." },
    { fronte: "Cos'è Così è (se vi pare)?", retro: "Dramma sul relativismo: nessuno può stabilire la verità sulla signora Ponza; «io sono colei che mi si crede»." },
    { fronte: "L'influenza filosofica su Pirandello", retro: "Il vitalismo di Bergson, il relativismo, la crisi del positivismo e dell'io unitario." },
    { fronte: "Pirandello e il fascismo", retro: "Aderì al fascismo (1924) ma il suo teatro resta critico verso ogni forma e autorità imposta." },
    { fronte: "Il significato di «Uno, nessuno e centomila»", retro: "Uno (come ci crediamo), centomila (come ci vedono gli altri), nessuno (la verità: nessuna identità fissa)." }
  ],

  svevo: [
    { fronte: "Anni di nascita e morte di Svevo", retro: "1861 – 1928, Trieste. Pseudonimo di Ettore Schmitz." },
    { fronte: "Cos'è l'«inetto» sveviano?", retro: "Il personaggio incapace di vivere e agire, paralizzato dal divario tra vita interiore e realtà: Alfonso, Emilio, Zeno." },
    { fronte: "Cos'è la «malattia» in Svevo?", retro: "Non solo fisica: la nevrosi, l'inettitudine come condizione esistenziale e, nel finale di Zeno, malattia della civiltà." },
    { fronte: "Cos'è l'autoinganno?", retro: "Il meccanismo per cui il personaggio si racconta una storia falsa su di sé: Zeno crede di voler smettere di fumare." },
    { fronte: "Cos'è il narratore inattendibile?", retro: "Il narratore (Zeno) di cui il lettore non può fidarsi: bisogna leggere «tra le righe»." },
    { fronte: "Trama di Una vita (1892)", retro: "Alfonso Nitti, impiegato di provincia con grandi speranze deluse a Trieste: il primo inetto, finisce suicida." },
    { fronte: "Cos'è la «senilità» in Svevo?", retro: "Non l'età ma uno stato dell'anima: l'incapacità di vivere pienamente. Emilio Brentani ha 35 anni ma è già «vecchio»." },
    { fronte: "Trama di Senilità (1898)", retro: "Emilio Brentani si illude di poter controllare la passione per Angiolina chiamandola «capriccio»: l'autoinganno." },
    { fronte: "Il capolavoro di Svevo", retro: "La coscienza di Zeno (1923): il romanzo della psicanalisi, dell'inettitudine e dell'ironia." },
    { fronte: "La struttura de La coscienza di Zeno", retro: "Un memoriale scritto per la terapia psicanalitica, organizzato per temi (il fumo, il padre, la moglie...), non cronologico." },
    { fronte: "Cosa simboleggia l'«ultima sigaretta»?", retro: "La malattia della volontà: Zeno non vuole davvero smettere ma ha bisogno di crederlo. «Ogni sigaretta è l'ultima.»" },
    { fronte: "Il finale de La coscienza di Zeno", retro: "«La vita è inquinata alle radici»: la malattia è universale, della civiltà; profezia di un ordigno che distruggerà la Terra." },
    { fronte: "Influenza di Freud su Svevo", retro: "La psicanalisi struttura il romanzo (il memoriale, l'analisi del profondo), ma Svevo ne è anche ironico e critico." },
    { fronte: "Influenza filosofica su Svevo", retro: "Schopenhauer (la volontà), Darwin (la lotta per la vita), Nietzsche, oltre a Freud." },
    { fronte: "Il rapporto di Svevo con Joyce", retro: "James Joyce, suo insegnante d'inglese a Trieste, lo incoraggiò e ne favorì la fortuna europea." },
    { fronte: "Trieste in Svevo", retro: "Città di frontiera, mercantile, mitteleuropea: spazio dell'alienazione e dell'incrocio di culture." },
    { fronte: "Differenza Svevo vs Verga", retro: "Verga: impersonalità e ceti bassi del Sud rurale. Svevo: introspezione e borghesia urbana mitteleuropea." },
    { fronte: "Differenza Svevo vs Pirandello", retro: "Entrambi indagano la crisi dell'io; Svevo con ironia e psicanalisi, Pirandello con relativismo e maschera." },
    { fronte: "Perché Zeno «guarisce»?", retro: "Non grazie alla psicanalisi (che abbandona): accetta la propria nevrosi come condizione normale e ci ride sopra." },
    { fronte: "La «salute» di Augusta vs la «malattia» di Zeno", retro: "Augusta, moglie «sana», vive senza dubbi; Zeno, «malato», è più lucido: la malattia come forma di coscienza." }
  ],

  ungaretti: [
    { fronte: "Anni di nascita e morte di Ungaretti", retro: "1888 – 1970, nato ad Alessandria d'Egitto." },
    { fronte: "Cos'è l'illuminazione poetica?", retro: "L'attimo in cui la parola rivela l'assoluto e l'io si fonde con il tutto. «M'illumino d'immenso»." },
    { fronte: "Cos'è la «parola» in Ungaretti?", retro: "La parola ridotta all'essenziale, isolata nel bianco della pagina, caricata di valore assoluto." },
    { fronte: "Prima raccolta di Ungaretti", retro: "L'allegria (1916/1931): la poesia di trincea, il verso brevissimo, la parola nuda." },
    { fronte: "Tema di Mattina", retro: "L'illuminazione: «M'illumino / d'immenso». Due parole, un'intera poetica di fusione con l'infinito." },
    { fronte: "Tema di Soldati", retro: "La precarietà assoluta: «Si sta come / d'autunno / sugli alberi / le foglie». L'unanimismo." },
    { fronte: "Tema di Veglia", retro: "Il paradosso vita/morte: accanto al compagno morto, «non sono mai stato tanto attaccato alla vita»." },
    { fronte: "Tema di Fratelli", retro: "La fraternità universale di fronte alla morte; la parola «fratelli» come «foglia appena nata»." },
    { fronte: "Tema de Il porto sepolto", retro: "Manifesto della poetica: il poeta scende nell'abisso e risale con i canti; resta «un nulla d'inesauribile segreto»." },
    { fronte: "Tema de I fiumi", retro: "L'identità nomade attraverso quattro fiumi (Isonzo, Serchio, Nilo, Senna); «docile fibra dell'universo»." },
    { fronte: "Tema di San Martino del Carso", retro: "La distruzione della guerra: del paese e dei compagni «non è rimasto nemmeno tanto»; «È il mio cuore il paese più straziato»." },
    { fronte: "Tema di Peso", retro: "L'attesa di una purificazione futura: «Quando il mio peso mi sarà / leggero». Impulso mistico." },
    { fronte: "La seconda fase di Ungaretti", retro: "Sentimento del tempo (1933): recupero della tradizione, del verso più disteso, della religiosità (la «conversione»)." },
    { fronte: "La terza fase di Ungaretti", retro: "Il dolore (1947): il lutto per il figlio Antonietto e per la guerra; tono meditativo e civile." },
    { fronte: "Tema di Non gridate più", retro: "Da Il dolore: il rispetto per i morti, il silenzio come unica via per ascoltarli. «Cessate d'uccidere i morti»." },
    { fronte: "A quale corrente è legato Ungaretti?", retro: "All'Ermetismo, di cui è il maestro e il precursore (con i Vociani alle spalle)." },
    { fronte: "Figura retorica tipica di Ungaretti", retro: "L'analogia (accostamento di immagini distanti senza «come») e l'ossimoro («corolla di tenebre»)." },
    { fronte: "Cos'è lo «spazio bianco»?", retro: "Il silenzio attorno alle poche parole, che le fa «esplodere»: elemento attivo della poesia, non vuoto." },
    { fronte: "Influenze su Ungaretti", retro: "Il Simbolismo francese (Mallarmé), i Vociani, l'esperienza della Prima guerra mondiale." },
    { fronte: "Cos'è l'unanimismo?", retro: "Il sentimento di appartenenza a un destino comune di tutta l'umanità; in Soldati il «si sta» impersonale." }
  ],

  saba: [
    { fronte: "Anni di nascita e morte di Saba", retro: "1883 – 1957, Trieste. Pseudonimo di Umberto Poli." },
    { fronte: "Cos'è la «poesia onesta»?", retro: "Una poesia chiara, sincera, fatta di «trite parole», contro l'oscurità ermetica e la retorica." },
    { fronte: "L'opera di una vita di Saba", retro: "Il Canzoniere: raccoglie tutte le poesie dal 1900 al 1954, come un unico libro autobiografico." },
    { fronte: "Cosa sono le «trite parole»?", retro: "Le parole comuni, logorate dall'uso (amore, madre, città): le più difficili perché le più cariche di significato umano." },
    { fronte: "Trieste in Saba", retro: "La città natale come specchio dell'anima: «scontrosa grazia», ambivalente come il poeta stesso." },
    { fronte: "Tema di Amai", retro: "La dichiarazione di poetica: «Amai trite parole che non uno / osava»; la rima fiore/amore; la verità al fondo." },
    { fronte: "Tema di A mia moglie", retro: "L'amore per Lina espresso paragonandola a femmine di animali domestici: «avvicinano a Dio»." },
    { fronte: "Tema de La capra", retro: "Il dolore universale: il belato della capra «dal viso semita» è «fraterno» al dolore del poeta." },
    { fronte: "Tema di Città vecchia", retro: "La fraternità con la «perduta gente» dei vicoli di Trieste: in loro «s'agita il Signore»." },
    { fronte: "Tema di Mio padre è stato per me «l'assassino»", retro: "Il capovolgimento del giudizio sul padre; «due razze in antica tenzone»: pesantezza materna vs leggerezza paterna." },
    { fronte: "Tema di Ulisse", retro: "Il mito di Ulisse autobiografico: la vecchiaia come isola «sempre più sola, sempre più difficile da raggiunger»." },
    { fronte: "Il romanzo di Saba", retro: "Ernesto (1953, postumo 1975): la scoperta della sessualità, l'onestà radicale; rimasto a lungo nel cassetto." },
    { fronte: "La psicanalisi in Saba", retro: "Si analizzò con il dottor Weiss (allievo di Freud); la scissione interiore e i fantasmi familiari nutrono la poesia." },
    { fronte: "L'identità ebraica di Saba", retro: "La madre era ebrea; il tema della diversità e della «scissione» (il «viso semita» della capra) attraversa l'opera." },
    { fronte: "A quale linea appartiene Saba?", retro: "Alla linea antinovecentista: chiarezza e tradizione contro l'oscurità dell'Ermetismo." },
    { fronte: "Cos'è la «scontrosa grazia»?", retro: "Ossimoro che descrive Trieste (e Saba): riservata eppure piena di vita, ruvida e dolce insieme." },
    { fronte: "Il modello metrico di Saba", retro: "La tradizione (Petrarca, Leopardi): il Canzoniere, il sonetto, l'endecasillabo, rinnovati dall'interno." },
    { fronte: "Differenza Saba vs Ermetismo", retro: "Saba: chiarezza, poesia onesta, parole comuni. Ermetismo: oscurità, parola assoluta, analogia." },
    { fronte: "Le sezioni del Canzoniere", retro: "Casa e campagna, Trieste e una donna, Il piccolo Berto, Autobiografia, Parole, Mediterranee..." },
    { fronte: "Il rapporto di Saba con la madre", retro: "Madre severa, opposta al padre «gaio e leggero» che l'aveva abbandonata: conflitto interiore irrisolto." }
  ],

  montale: [
    { fronte: "Anni di nascita e morte di Montale", retro: "1896 – 1981, Genova. Nobel 1975." },
    { fronte: "Cos'è il «male di vivere»?", retro: "La condizione esistenziale di sofferenza e prigionia connaturata all'esistenza, non agli eventi storici." },
    { fronte: "Cos'è il correlativo oggettivo?", retro: "Da T.S. Eliot: un oggetto fisico che «contiene» l'emozione senza nominarla (il rivo strozzato = il male di vivere)." },
    { fronte: "Cos'è la «divina Indifferenza»?", retro: "La natura estranea al dolore umano: non nemica né amica, semplicemente indifferente. La statua, la nuvola, il falco." },
    { fronte: "Cos'è il «varco»?", retro: "La ricerca, quasi sempre fallita, di una via di fuga o di senso dal male di vivere." },
    { fronte: "Prima raccolta di Montale", retro: "Ossi di seppia (1925): il male di vivere, il paesaggio ligure, il muro. Lo stile aspro e antimusicale." },
    { fronte: "Cosa sono gli «ossi di seppia»?", retro: "I residui calcarei dei molluschi: l'uomo spogliato di illusioni, arenato, esiliato." },
    { fronte: "Tema di Non chiederci la parola", retro: "Manifesto: la poesia non dà certezze, sa dire solo «ciò che non siamo, ciò che non vogliamo». Poetica della negazione." },
    { fronte: "Tema di Spesso il male di vivere", retro: "Tre correlativi del male (rivo strozzato, foglia riarsa, cavallo stramazzato) + tre della divina Indifferenza." },
    { fronte: "Tema di Meriggiare pallido e assorto", retro: "Il muro «con in cima cocci aguzzi di bottiglia»: l'esistenza come prigione invalicabile." },
    { fronte: "Tema de La casa dei doganieri", retro: "La memoria che tradisce: «Tu non ricordi»; la bussola impazzita; la separazione definitiva da Clizia." },
    { fronte: "Tema di Ho sceso, dandoti il braccio", retro: "Elegia per Mosca morta: lei, miope, «aveva le sole vere pupille»; il paradosso miopia/visione. Stile prosastico." },
    { fronte: "La seconda raccolta di Montale", retro: "Le occasioni (1939): i Mottetti, Clizia, la lingua più oscura e aristocratica." },
    { fronte: "Chi è Clizia?", retro: "Irma Brandeis, studiosa ebrea americana: donna-angelo, messaggera cosmica, simbolo di resistenza contro il nazifascismo." },
    { fronte: "Chi è Mosca?", retro: "Drusilla Tanzi, la moglie: soprannome per la miopia. Guida pratica e quotidiana; gli Xenia di Satura la commemorano." },
    { fronte: "La raccolta della svolta prosastica", retro: "Satura (1971): stile ironico, diaristico, quotidiano; gli Xenia per Mosca morta." },
    { fronte: "A quale corrente si avvicina Montale?", retro: "All'area ermetica (specie nelle Occasioni), pur con una posizione autonoma e antiretorica." },
    { fronte: "Cos'è la «pathetic fallacy rovesciata»?", retro: "Al contrario del Romanticismo, la natura non rispecchia i sentimenti umani: è indifferente." },
    { fronte: "Differenza Montale vs Ungaretti", retro: "Ungaretti ha epifanie/illuminazione; Montale ha lo scacco permanente, il varco fallito." },
    { fronte: "Differenza Montale vs D'Annunzio", retro: "Montale è l'anti-vate: rifiuta la poesia profetica e la parola che «apre mondi»." }
  ],

  campana: [
    { fronte: "Anni di nascita e morte di Campana", retro: "1885 – 1932, Marradi. Morì internato in manicomio." },
    { fronte: "Cos'è la poesia «orfica»?", retro: "Poesia come discesa agli inferi e rivelazione (dal mito di Orfeo): parola magica, visione, non comunicazione." },
    { fronte: "L'unica opera di Campana", retro: "Canti orfici (1914), pubblicati a proprie spese dopo la perdita del primo manoscritto." },
    { fronte: "Cosa accadde al primo manoscritto?", retro: "Il più lungo giorno fu consegnato a Soffici e Papini nel 1913 e perduto; Campana lo riscrisse a memoria. Ritrovato nel 1971." },
    { fronte: "Cos'è la «musicalità ossessiva»?", retro: "La ripetizione di immagini e parole come incantesimo: il ritmo ipnotico tipico dei Canti orfici." },
    { fronte: "Tema de La Chimera", retro: "La ricerca di una bellezza assoluta e sfuggente, figura femminile-mito; il testo più celebre." },
    { fronte: "Tema de L'invetriata", retro: "La visione cromatica e onirica; il rosso, la sera, la finestra: la realtà trasfigurata." },
    { fronte: "Il simbolismo cromatico di Campana", retro: "I colori (rosso, nero) caricati di valore simbolico ed emotivo: visione più che descrizione." },
    { fronte: "A quale corrente è vicino Campana?", retro: "Ai Vociani (area de La Voce), ma da outsider; influenzato dal Simbolismo francese." },
    { fronte: "Le letture di Campana", retro: "Autodidatta: legge Baudelaire e Rimbaud in francese, Nietzsche in tedesco, Whitman in inglese." },
    { fronte: "La relazione con Sibilla Aleramo", retro: "Tormentata storia d'amore (1916–17); il loro carteggio è tra i più intensi del Novecento." },
    { fronte: "Cosa significa che la poesia «rivela»?", retro: "Non comunica un messaggio razionale: riporta dalle zone oscure del reale una verità intraducibile." },
    { fronte: "Il vagabondaggio in Campana", retro: "Tema biografico e poetico: i viaggi (anche in Sud America), l'errare come condizione esistenziale." },
    { fronte: "La fine di Campana", retro: "Internato nel 1918 a Castel Pulci, vi rimase fino alla morte nel 1932: il poeta «folle»." },
    { fronte: "Influenza di Rimbaud su Campana", retro: "Il poeta «veggente», il sregolamento dei sensi, la visione come metodo conoscitivo." },
    { fronte: "Lo stile dei Canti orfici", retro: "Alternanza di prosa poetica e versi; potenza visionaria; sintassi franta e musicale." },
    { fronte: "Cos'è la «visione» in Campana", retro: "L'esperienza mistico-sensoriale in cui la realtà diventa simbolo e mito; il fondamento dell'orfismo." },
    { fronte: "Perché Campana è un «outsider»", retro: "Inclassificabile, ai margini della cultura ufficiale, instabile e incompreso: vita e opera leggendarie." },
    { fronte: "Il paesaggio in Campana", retro: "L'Appennino, le città notturne, i porti: luoghi reali trasfigurati in scenari onirici e simbolici." },
    { fronte: "Differenza Campana vs Ungaretti", retro: "Entrambi vicini all'orfismo/simbolismo; Ungaretti riduce all'essenziale, Campana espande nella visione musicale." }
  ],

  pavese: [
    { fronte: "Anni di nascita e morte di Pavese", retro: "1908 – 1950, Santo Stefano Belbo (Cuneo). Morì suicida." },
    { fronte: "Cos'è il «mito» in Pavese?", retro: "I luoghi dell'infanzia (le Langhe) come archetipi eterni e sacri: il mito non è nostalgia ma categoria conoscitiva (Vico, Jung)." },
    { fronte: "Cos'è il tema del «ritorno»?", retro: "Si torna ai luoghi dell'origine ma non si trova ciò che si cerca: il passato è irrecuperabile." },
    { fronte: "Cos'è la «solitudine» pavesiana?", retro: "La condizione dei personaggi: incapacità di amare e comunicare; l'amore è sempre fallimento." },
    { fronte: "Cos'è il «verso-frase»?", retro: "Il verso lungo, narrativo e prosastico di Lavorare stanca: l'opposto dell'essenzialità ermetica." },
    { fronte: "Prima raccolta poetica di Pavese", retro: "Lavorare stanca (1936): poemetti narrativi, temi rurali e urbani, solitudine; il verso-frase." },
    { fronte: "Il capolavoro-testamento di Pavese", retro: "La luna e i falò (1950): Anguilla torna nelle Langhe e trova solo morte; il mito infranto." },
    { fronte: "Chi è Anguilla?", retro: "Il protagonista de La luna e i falò: trovatello cresciuto nelle Langhe, emigrato in America, che torna in cerca delle radici." },
    { fronte: "Cosa simboleggiano «la luna e i falò»?", retro: "La luna: il ciclo cosmico eterno, il mito. I falò: il rito contadino, l'identità del luogo, ora perduta." },
    { fronte: "Tema di La casa in collina", retro: "La guerra partigiana vista da Corrado, intellettuale che non sa schierarsi: «ogni guerra è una guerra civile»." },
    { fronte: "Cos'è Il mestiere di vivere?", retro: "Il diario intimo (1935–1950, postumo): l'analisi lucida della propria incapacità di essere felice." },
    { fronte: "Tema di Verrà la morte e avrà i tuoi occhi", retro: "La fusione di amore e morte; «un vizio assurdo»; scritta pochi mesi prima del suicidio: quasi una profezia." },
    { fronte: "Pavese traduttore", retro: "Con Vittorini, principale traduttore della letteratura americana (Melville, Whitman, Dos Passos)." },
    { fronte: "Cosa sono i Dialoghi con Leucò?", retro: "Reinterpretazioni dei miti greci in forma di dialogo (1947): la teoria pavesiana del mito." },
    { fronte: "Pavese e la casa editrice Einaudi", retro: "Fu una figura centrale di Einaudi nel dopoguerra; vinse il Premio Strega nel 1950." },
    { fronte: "Pavese e il confino", retro: "Confinato a Brancaleone Calabro (1935) per antifascismo; al ritorno iniziò il diario." },
    { fronte: "A quale corrente appartiene Pavese?", retro: "Al Neorealismo, ma lo supera: aggiunge alla realtà il mito (dentro e oltre)." },
    { fronte: "Differenza Pavese vs Verga", retro: "La terra d'origine come mito (Pavese) o come realtà sociologica immutabile (Verga)." },
    { fronte: "Differenza Pavese vs Calvino", retro: "Amici all'Einaudi; il mito di Pavese è tragico, quello di Calvino è giocoso." },
    { fronte: "Cosa rivela l'incipit de La luna e i falò?", retro: "Anguilla è un trovatello senza radici biologiche; «si torna per vedere com'è, si vuol toccare»." }
  ],

  pasolini: [
    { fronte: "Anni di nascita e morte di Pasolini", retro: "1922 – 1975. Nato a Bologna, assassinato a Ostia." },
    { fronte: "Cos'è l'«omologazione culturale»?", retro: "L'annullamento delle differenze culturali e di classe operato dal consumismo: il «nuovo fascismo», più totalitario di quello storico." },
    { fronte: "Cosa rappresenta il sottoproletariato?", retro: "Una vitalità corporea e culturale autentica, pre-borghese, che il capitalismo sta distruggendo." },
    { fronte: "Cos'è la «mutazione antropologica»?", retro: "Il cambiamento profondo dell'essere umano prodotto dal consumismo: i giovani autentici diventano piccolo-borghesi senza identità." },
    { fronte: "Perché Pasolini è «corsaro» e «luterano»?", retro: "Perché è eretico verso ogni potere (sinistra, destra, borghesia, Chiesa): sempre «contro», profeta scomodo." },
    { fronte: "Prime poesie di Pasolini", retro: "Poesie a Casarsa (1942), in dialetto friulano: la lingua della madre, affettiva e pre-ideologica." },
    { fronte: "Il poemetto chiave di Pasolini", retro: "Le ceneri di Gramsci (1957): il conflitto tra ragione marxista e attrazione per il sottoproletariato." },
    { fronte: "Tema de Le ceneri di Gramsci", retro: "«Con te e contro di te»: ammirazione per Gramsci (la ragione) e amore per ciò che Gramsci vorrebbe redimere (il corpo)." },
    { fronte: "Romanzo delle borgate (1955)", retro: "Ragazzi di vita: le borgate romane viste dall'interno, il dialetto romanesco fatto lingua letteraria." },
    { fronte: "Cosa sono gli Scritti corsari (1975)?", retro: "Articoli con la critica all'omologazione, alla TV, al «nuovo fascismo» dei consumi: il testamento ideologico." },
    { fronte: "Tema dell'articolo delle lucciole", retro: "La scomparsa delle lucciole come metafora della fine di un mondo autentico, ucciso dal consumismo." },
    { fronte: "Il dialetto in Pasolini", retro: "Resistenza culturale: friulano (lingua della madre) e romanesco (voce delle borgate), non folklore." },
    { fronte: "Cos'è il «cinema di poesia»?", retro: "La teoria del cinema come «lingua scritta della realtà»: la continuazione della poetica con altri mezzi." },
    { fronte: "Film d'esordio di Pasolini", retro: "Accattone (1961), sulle borgate romane. Poi Mamma Roma, Il Vangelo secondo Matteo, Salò." },
    { fronte: "L'ultimo film di Pasolini", retro: "Salò o le 120 giornate di Sodoma (1975): l'allegoria estrema del potere come distruzione dei corpi." },
    { fronte: "A quale corrente parte da Pasolini?", retro: "Dal Neorealismo (borgate, dialetto, popolo), che supera trasfigurando il sottoproletariato in mito e sacro." },
    { fronte: "Differenza Pasolini vs Ungaretti", retro: "Poesia come azione politica e corpo (Pasolini) vs illuminazione interiore (Ungaretti)." },
    { fronte: "Differenza Pasolini vs D'Annunzio", retro: "Intellettuali totali e scandalosi entrambi, ma Pasolini contro il potere, D'Annunzio al servizio del potere." },
    { fronte: "Lo stile della poesia pasoliniana", retro: "Denso, fisico, sensoriale: la parola pesa e brucia, rende palpabile l'esperienza. L'opposto dell'Ermetismo." },
    { fronte: "Cos'è Petrolio?", retro: "Romanzo-poema enciclopedico incompiuto (postumo 1992): il potere, l'economia, la politica italiana." }
  ],

  calvino: [
    { fronte: "Anni di nascita e morte di Calvino", retro: "1923 – 1985. Nato a Cuba, morto a Siena." },
    { fronte: "Cos'è la «leggerezza»?", retro: "La capacità di sollevarsi dal peso della realtà senza negarla. Emblema: Perseo che guarda Medusa riflessa nello scudo." },
    { fronte: "Cos'è il «combinatorio»?", retro: "La concezione (Oulipo) della letteratura come gioco basato su vincoli formali: la struttura genera il senso." },
    { fronte: "Cos'è l'Oulipo?", retro: "Il gruppo francese (Queneau, Perec) della «letteratura potenziale» basata su regole e vincoli, frequentato da Calvino a Parigi." },
    { fronte: "Romanzo d'esordio di Calvino", retro: "Il sentiero dei nidi di ragno (1947): la Resistenza vista con gli occhi del bambino Pin; neorealismo già superato." },
    { fronte: "Cos'è la trilogia I nostri antenati?", retro: "Il visconte dimezzato (1952), Il barone rampante (1957), Il cavaliere inesistente (1959): allegorie filosofiche in forma di favola." },
    { fronte: "Cosa rappresenta Il visconte dimezzato?", retro: "L'identità divisa tra bene e male; la frammentazione dell'uomo moderno e l'aspirazione all'integrità." },
    { fronte: "Cosa rappresenta Il barone rampante?", retro: "Cosimo vive sugli alberi: la libertà come distanza scelta dal mondo, non come fuga." },
    { fronte: "Cosa rappresenta Il cavaliere inesistente?", retro: "Agilulfo, armatura vuota animata dalla volontà: l'esistenza ridotta a pura funzione." },
    { fronte: "Cosa sono Le cosmicomiche (1965)?", retro: "Racconti narrati da Qfwfq, essere antichissimo: scienza e mito fusi in un'ironia cosmica." },
    { fronte: "Cos'è Le città invisibili (1972)?", retro: "Marco Polo descrive a Kublai Khan 55 città immaginarie in 11 categorie: meditazione su memoria, desiderio, tempo." },
    { fronte: "Cosa rivela la città di Diomira?", retro: "Il «carattere» non sono le meraviglie ma un sentimento: l'invidia per chi ha già vissuto una sera come quella." },
    { fronte: "Cos'è Se una notte d'inverno un viaggiatore (1979)?", retro: "Romanzo postmoderno in cui il Lettore è protagonista: dieci incipit di romanzi mai finiti. Riflessione su lettura e scrittura." },
    { fronte: "Cosa sono le Lezioni americane?", retro: "Sei conferenze per Harvard (postume 1988) sui valori della letteratura: leggerezza, rapidità, esattezza, visibilità, molteplicità, coerenza." },
    { fronte: "Le fasi di Calvino", retro: "Neorealismo, fiaba filosofica, fantascienza ironica, postmoderno: una continua reinvenzione del raccontare." },
    { fronte: "Calvino e la Resistenza", retro: "Partigiano nelle Brigate Garibaldi; l'esperienza è la materia del primo romanzo." },
    { fronte: "Calvino ed Einaudi", retro: "Lavorò per la casa editrice Einaudi per gran parte della vita, come consulente e redattore." },
    { fronte: "A quale corrente parte Calvino?", retro: "Dal Neorealismo (Resistenza), che supera con lo sguardo straniato del bambino e la struttura fiabesca." },
    { fronte: "Differenza Calvino vs Pirandello", retro: "Interrogano entrambi identità e realtà; Calvino con leggerezza giocosa, Pirandello con angoscia." },
    { fronte: "Differenza Calvino vs Pavese", retro: "Entrambi lavorano col mito; quello di Calvino è giocoso, quello di Pavese è tragico." }
  ],

  carducci: [
    { fronte: "Anni di nascita e morte di Carducci", retro: "1835 Valdicastello – 1907 Bologna. Nobel 1906, primo italiano." },
    { fronte: "Cos'è l'Odi barbare?", retro: "Odi che adattano i piedi metrici latini all'accento tonico italiano. Saffiche (3 endecasillabi+adonio) e alcaiche (schema di Orazio). 'Barbare' = come le chiamerebbe un Latino." },
    { fronte: "Pianto antico — tema e struttura", retro: "Dolore per la morte del figlio Dante (3 anni, 1870). 4 quartine novenari. Antitesi melograno verde/figlio morto. Anafora 'sei ne la terra fredda/negra'." },
    { fronte: "San Martino — similitudine chiave", retro: "'Com'esuli pensieri': gli uccelli neri migratori = pensieri malinconici del poeta. Sinestesia 'aspro odor de i vini l'anime a rallegrar'." },
    { fronte: "Alla stazione in una mattina d'autunno", retro: "Ode alcaica. Il treno (modernità) porta via la donna amata. 'Corre il treno, corre, corre, ululando, e sparve.' Personificazione + triplice ripetizione." },
    { fronte: "Nevicata", retro: "Ode saffica. La neve copre tutto di silenzio anche il dolore. Apostrofe 'O neve, o silenziosa'. Statua di Garibaldi coperta di bianco: grandezza risorgimentale immobilizzata." },
    { fronte: "Inno a Satana (1865)", retro: "Manifesto anticlericale. Satana = ragione umana vs dogma ecclesiastico. Pubblicato 31 ottobre (anniversario Lutero). Carducci lo giudicherà poi 'troppo giovanile'." },
    { fronte: "Poeta vate", retro: "Vates = poeta-profeta latino. Carducci = voce civile della nazione. Patriottismo risorgimentale laico, anticlericalismo, costruzione identità italiana post-unità." },
    { fronte: "Classicismo carducciano", retro: "Programma estetico militante: recupero modelli greco-latini (Orazio, Virgilio, Pindaro) contro Romanticismo sentimentale. Non nostalgia ma battaglia civile." },
    { fronte: "Pianto antico vs San Martino", retro: "Pianto antico: dolore per figlio, antitesi natura/morte, desolazione. San Martino: paesaggio autunnale sensoriale, contrasto calore/malinconia, similitudine finale." },
    { fronte: "Premio Nobel 1906", retro: "Primo italiano nella storia. 'Profonda dottrina e fresca originalità e bellezza poetica'. Non poté ritirarlo per malattia. Morì l'anno successivo." },
    { fronte: "Metrica saffica", retro: "Tre endecasillabi saffici + adonio (5 sillabe). Usata in Nevicata. Dal modello di Saffo e Orazio. Solenne e cadenzata." },
    { fronte: "Metrica alcaica", retro: "Schema oraziano: quattro versi di lunghezze diverse. Usata in Alla stazione. Più grave e meditativa della saffica." },
    { fronte: "Carducci vs Pascoli", retro: "Pascoli = allievo a Bologna. Differenze: natura concreta (Carducci) vs simbolica (Pascoli); forma rigida vs fonosimbolismo; dolore controllato vs ossessivo." },
    { fronte: "Carducci vs D'Annunzio", retro: "Classicismo = programma civile (Carducci) vs ornamento estetico (D'Annunzio). Vate civile vs superuomo estetista. Patriottismo laico vs nazionalismo estetista." },
    { fronte: "Funere mersit acerbo", retro: "Poesia per il figlio. Titolo = citazione Eneide Virgilio. Il dolore si esprime con la dignità della lingua classica: forma come controllo." },
    { fronte: "Anticlericalismo di Carducci", retro: "Costante in tutta l'opera. Rifiuto del potere temporale della Chiesa. Positivismo laico: ragione vs dogma. L'Inno a Satana ne è il manifesto (1865)." },
    { fronte: "Incipit San Martino", retro: "'La nebbia a gl'irti colli piovigginando sale, e sotto il maestrale urla e biancheggia il mar'. Paesaggio autunnale cupo controbilanciato dal calore del borgo." },
    { fronte: "Rima costante in San Martino", retro: "La rima -ar (mar/rallegrar/rimirar/migrar) ritorna in tutte e quattro le strofe come un ritornello malinconico." },
    { fronte: "Carducci e il Positivismo", retro: "Crede nella ragione, nella scienza, nel progresso laico. Non naturalista come Zola/Verga ma condivide l'ottimismo positivista. L'anticlericalismo ne è la conseguenza." }
  ],

  marinetti: [
    { fronte: "Anni di nascita e morte di Marinetti", retro: "1876 Alessandria d'Egitto – 1944 Bellagio. Manifesto del Futurismo 1909." },
    { fronte: "Dove pubblica il Manifesto nel 1909?", retro: "Sulla prima pagina di Le Figaro di Parigi, il 20 febbraio 1909. Scelta strategica per la massima diffusione internazionale." },
    { fronte: "Antipassatismo futurista", retro: "Musei = cimiteri, biblioteche = dormitori. Il passato è un cadavere che soffoca il presente. Distruzione gioiosa, non nostalgia." },
    { fronte: "Punto 4 del Manifesto", retro: "Un automobile da corsa è più bello della Nike di Samotracia: la velocità industriale è il nuovo valore estetico." },
    { fronte: "Punto 9 del Manifesto", retro: "La guerra è la sola igiene del mondo. Per Marinetti: purificazione della decadenza borghese e accelerazione della storia." },
    { fronte: "Parole in libertà (Manifesto tecnico 1912)", retro: "Abolire: sintassi (infiniti), punteggiatura (segni matematici + × ÷ =), aggettivi. Adottare: onomatopee, analogie distanti, tavola visiva." },
    { fronte: "ZANG TUMB TUMB", retro: "Onomatopea del cannone in Zang Tumb Tuum (1914): la battaglia di Adrianopoli. Il testo-manifesto del paroliberismo." },
    { fronte: "Futurismo come arte totale", retro: "Boccioni (pittura/scultura: simultaneità), Balla (scomposizione del movimento), Russolo (Arte dei rumori 1913: intonarumori)." },
    { fronte: "Marinetti vs D'Annunzio", retro: "Marinetti: distruzione della tradizione, paroliberismo, fascismo rivoluzionario. D'Annunzio: ornamento estetico, raffinatezza metrica, cortigianeria." },
    { fronte: "Futurismo vs Crepuscolarismo", retro: "Futurismo: eroico, veloce, esalta la modernità. Crepuscolarismo: malinconico, dimesso, subisce la modernità come squallore grigio." },
    { fronte: "Mafarka il futurista (1909)", retro: "Romanzo processato per oscenità in Italia. Ambientato in Africa immaginaria. Il processo è un successo mediatico per Marinetti." },
    { fronte: "Il paroliberismo in Zang Tumb Tuum", retro: "Onomatopee (ZANG, croc-croc, glu-glu), infiniti senza soggetto, segni matematici (+ =), tavola visiva della pagina." },
    { fronte: "Manifesto tecnico della letteratura futurista", retro: "1912: codifica il paroliberismo. Abolire sintassi, punteggiatura, aggettivi. Usare infiniti, segni matematici, onomatopee, analogie distanti." },
    { fronte: "Marinetti e il fascismo", retro: "Partecipa ai Fasci con Mussolini nel 1919. Entra nell'Accademia d'Italia nel 1929: paradosso del rivoluzionario istituzionalizzato." },
    { fronte: "La 'strategia mediatica' di Marinetti", retro: "Primo intellettuale a usare il clamore come forma d'arte sistematica. Le Figaro, i processi, le serate-happening: il messaggio e il mezzo sono inseparabili." },
    { fronte: "Tavola parolibera", retro: "La pagina come campo visivo: parole disposte con angolazioni, dimensioni, direzioni diverse come in un dipinto. La letteratura diventa arte visiva." },
    { fronte: "croc-croc e glu-glu in Zang Tumb Tuum", retro: "croc-croc = il suono dei passi nel fango; glu-glu = il fango paludoso che inghiotte. Onomatopee del quotidiano lurido in contrasto con ZANG TUMB delle esplosioni." },
    { fronte: "Incipit del Manifesto — stile", retro: "Ancora simbolista (immagini esotiche, notte, lusso). Marinetti non nasce futurista: il Manifesto è la rottura con il proprio passato letterario." },
    { fronte: "Il punto 11 del Manifesto", retro: "Cantare le grandi folle agitate dal lavoro, dal piacere o dalla sommossa: il soggetto collettivo contro l'individualismo romantico." },
    { fronte: "Analogia distante futurista", retro: "Accostamento diretto di immagini lontane senza 'come'. Es: 'bue caduto = camion': il naturale equiparato al meccanico senza mediazione." }
  ],

  quasimodo: [
    { fronte: "Anni di nascita e morte di Quasimodo", retro: "1901 Modica (Sicilia) – 1968 Napoli. Nobel 1959, secondo italiano dopo Carducci." },
    { fronte: "Le due fasi di Quasimodo", retro: "Fase ermetica (1930-1942): parola pura, analogia, Sicilia come mito. Fase civile (1945-1968): testimonianza bellica, io→noi. Spartiacque: Seconda Guerra Mondiale." },
    { fronte: "Ed è subito sera — struttura e tema", retro: "3 versi (endecasillabo+novenario+senario). Ognuno=universale. Trafitto=ambiguità luce/ferita. Subito=velocità della vita. I versi si accorciano: la vita si contrae." },
    { fronte: "Principio della parola pura", retro: "Massimo significato con minimo di parole. Ed è subito sera: 3 versi, 17 parole, infinità di significato. L'oscurità è fedeltà all'esperienza interiore." },
    { fronte: "Analogia ermetica", retro: "Accostamento diretto di immagini senza 'come' (che la similitudine richiederebbe). Il vento=anima in 'Vento a Tindari' senza mediazione esplicita." },
    { fronte: "Sicilia come mito in Quasimodo", retro: "Non sfondo geografico ma mito dell'infanzia perduta. Solo da Milano, in esilio, la Sicilia diventa il luogo assoluto. Apostrofe a Tindari come persona viva." },
    { fronte: "Vento a Tindari — struttura ad anello", retro: "'Tindari, mite ti so' (apertura) → 'Mite scendi nell'anima' (chiusura). Il luogo va dall'esterno geografico all'interno dell'anima: interiorizzazione." },
    { fronte: "Alle fronde dei salici — Salmo 137", retro: "Citazione del Salmo 137 (ebrei a Babilonia che appendono le cetre ai salici). Noi italiani occupati = ebrei esiliati. Silenzio 'per voto' = atto sacro." },
    { fronte: "«Il piede straniero sopra il cuore»", retro: "Metafora dell'occupazione nazista: fisica (la Wehrmacht marcia) e interiore (violenza all'anima della nazione)." },
    { fronte: "Uomo del mio tempo — struttura", retro: "Pietra e fionda (violenza primitiva) → carlinga (aereo moderno): la barbarie non cambia, cambiano gli strumenti. Caino e Abele. Finale ai figli: spezzare il ciclo." },
    { fronte: "«Scienza esatta persuasa allo sterminio»", retro: "Paradosso illuminista: la ragione scientifica messa al servizio del genocidio. La modernità tecnologica non ha eliminato la barbarie: l'ha amplificata." },
    { fronte: "Giorno dopo giorno (1947)", retro: "Raccolta della svolta civile: Alle fronde dei salici, Uomo del mio tempo. Versi ampi, immagini bibliche, io→noi, tono di denuncia." },
    { fronte: "Lirici greci (1940) — funzione", retro: "Traduzioni creative, non filologiche: Quasimodo riscrive i lirici greci arcaici nella propria voce. Dimostrano che la brevità lapidaria greca = principio ermetico della parola pura." },
    { fronte: "Quasimodo vs Ungaretti", retro: "Brevità come risultato (Quasimodo) vs sistema strutturale (Ungaretti). Seconda Guerra Mondiale/collettiva (Quasimodo) vs Prima/autobiografica/Carso (Ungaretti)." },
    { fronte: "Quasimodo vs Montale", retro: "Analogia ermetica→interiore (Quasimodo) vs correlativo oggettivo (Montale). Impegno civile esplicito (Quasimodo) vs resistenza al 'cattivo impegno' (Montale)." },
    { fronte: "«Crocifisso sul palo del telegrafo»", retro: "Il partigiano impiccato: il martirio sacro si incontra con la tecnologia moderna. Il sacrificio del presente ha la stessa dignità di quello antico." },
    { fronte: "«Ed è subito sera» — il pronome 'ognuno'", retro: "Universalizza la solitudine: non è autobiografica ma ontologica. Ogni essere umano è strutturalmente solo, non per cause esterne ma per condizione di esistenza." },
    { fronte: "La motivazione del Nobel 1959 a Quasimodo", retro: "'Per la sua poetica lirica, che con ardente classicità esprime le tragiche esperienze della vita ai nostri tempi'. Riconosce entrambe le fasi." },
    { fronte: "Oboe sommerso (1932)", retro: "Seconda raccolta ermetica. Il titolo è un'analogia: l'oboe immerso nell'acqua = voce poetica soffocata ma ancora udibile. Oscurità crescente rispetto ad Acque e terre." },
    { fronte: "La svolta civile di Quasimodo — causa", retro: "La Seconda Guerra Mondiale: bombardamenti su Milano, esecuzioni nelle piazze, occupazione nazista. La parola pura ermetica diventa moralmente impossibile di fronte all'orrore." }
  ],

  fenoglio: [
    { fronte: "Anni di nascita e morte di Fenoglio", retro: "1922 Alba (Cuneo) – 1963 Alba, a 40 anni. Muore mentre lavora a Una questione privata e Il partigiano Johnny." },
    { fronte: "Resistenza di Fenoglio", retro: "1943-45 nelle Langhe: prima Brigate Garibaldi (comuniste), poi Badogliane (monarchiche). Doppia esperienza che alimenta complessità morale." },
    { fronte: "Il «fenogliano»", retro: "Lingua ibrida unica: italiano letterario + dialetto piemontese Langhe + calchi dall'inglese + arcaismi. Non errore: sistema narrativo consapevole." },
    { fronte: "Anti-retorica resistenziale", retro: "Partigiani con paura, errori, dubbi. Nessun eroe convenzionale, nessun martirologio. La guerra come avventura morale (Conrad), non epopea." },
    { fronte: "Influenza di Hemingway su Fenoglio", retro: "Principio dell'iceberg: ciò che il testo non dice pesa quanto ciò che dice. Dialogo asciutto per ellissi. 'Vengono. Quanti? Non so. Tanti.'" },
    { fronte: "Influenza di Conrad su Fenoglio", retro: "L'avventura come prova morale: non conta la vittoria ma come si affronta la situazione impossibile. Johnny non è eroe: è un uomo che si scopre." },
    { fronte: "Le Langhe come paesaggio morale", retro: "Come Hardy il Wessex: non sfondo pittoresco ma territorio narrativo con logica morale propria. Le colline, il Tanaro, i borghi partecipano all'azione." },
    { fronte: "I ventitre giorni della città di Alba (1952)", retro: "Esordio Einaudi. Liberazione di Alba (10 ottobre 1945) e abbandono dopo 23 giorni senza combattere. Tono tragicomico: né celebrativo né sentimentale." },
    { fronte: "La malora (1954)", retro: "La vita contadina nelle Langhe senza Resistenza. Agostino servo di una famiglia in declino. Miseria strutturale senza sentimentalismo." },
    { fronte: "Una questione privata (1963, postumo)", retro: "IL CAPOLAVORO. Milton/Fulvia/Fulvio. Calvino (1968): 'aveva quello che tutti cercavamo e nessuno trovava: costruzione classica e rapidità americana'." },
    { fronte: "Il partigiano Johnny (1968, postumo)", retro: "Romanzo-mondo della Resistenza. Due versioni manoscritte incompatibili. Curatore: Lorenzo Mondo. Problema filologico non ancora risolto." },
    { fronte: "Fenoglio vs Calvino — Resistenza", retro: "Fenoglio: immersione diretta, anti-retorica asciutta, Hemingway+Conrad. Calvino: straniamento del bambino Pin, filtro fiabesco, Stevenson+Ariosto." },
    { fronte: "Fenoglio vs Pavese — Langhe", retro: "Fenoglio: paesaggio morale concreto e presente. Pavese: mito e nostalgia simbolica del ritorno impossibile. Hemingway (Fenoglio) vs Anderson/Dos Passos (Pavese)." },
    { fronte: "Incipit I ventitre giorni — l'ironia", retro: "'Se li fossero tenuti più a lungo, il mondo ne avrebbe certo saputo qualcosa': relativizza l'episodio. 'La gente di Alba le serba rancore': la Resistenza non sempre capita." },
    { fronte: "Incipit Una questione privata — la nebbia", retro: "Nebbia fisica = nebbia mentale (incertezza su Fulvia/Fulvio). Villa 'evanescente, quasi irreale' = già memoria. 'Non vedere ma rivedere' = prigioniero del passato." },
    { fronte: "Brano Partigiano Johnny — dialogo", retro: "'Vengono. Quanti? Non so. Tanti.' + 'Pensò: sarà dura. Poi smise di pensare e cominciò a correre.' Fenomenologia dell'azione sotto pressione." },
    { fronte: "Il problema filologico di Fenoglio", retro: "Il partigiano Johnny ha due versioni manoscritte (Q e A) incompatibili. Lorenzo Mondo ha curato l'edizione 1968. Il dibattito critico continua." },
    { fronte: "Primavera di bellezza (1959)", retro: "L'8 settembre 1943 e il crollo dell'esercito italiano visto da Johnny, il giovane alter-ego di Fenoglio. Titolo ironico: la giovinezza spezzata dalla storia." },
    { fronte: "Calvino sulla costruzione di Una questione privata", retro: "'Un romanzo d'amore e di guerra, tutti e due i generi al tempo stesso e ciascuno col massimo di tensione.' (prefazione 1968)" },
    { fronte: "La doppia esperienza resistenziale di Fenoglio", retro: "Prima Brigate Garibaldi (comuniste), poi Badogliane (monarchiche): la complessità morale non è ideologica ma umana. I partigiani non sono tutti uguali." }
  ],

  /* ════════════════  CORRENTI  ════════════════ */

  carduccianesimo: [
    { fronte: "Cos'è il Carduccianesimo?", retro: "Movimento poetico ispirato a Carducci: classicismo civile, recupero della metrica greco-latina, poesia come educazione nazionale." },
    { fronte: "Date del Carduccianesimo", retro: "Attività di Carducci: 1860–1907. Influenza sui giovani poeti fino al primo Novecento." },
    { fronte: "Cos'è la «barbarie metrica»?", retro: "Uso di metri classici (esametro, saffico, alcaico) in italiano, «stranieri» alla prosodia italiana: Odi barbare (1877–1889)." },
    { fronte: "Carducci e il Positivismo", retro: "Fiducia nella scienza, nel progresso laico e nel Risorgimento. La poesia celebra la ragione e la storia, non il sentimento romantico." },
    { fronte: "Il «poeta vate»", retro: "Ruolo civile e profetico del poeta: voce della nazione, educatore collettivo. Carducci è il modello del vate risorgimentale." },
    { fronte: "Nobel 1906", retro: "Carducci è il primo italiano a vincere il Nobel per la Letteratura." },
    { fronte: "Rime nuove (1861–1887)", retro: "Raccolta di liriche più intime. Include Pianto antico (1871): elegia per la morte del figlio, antitesi natura viva / bambino morto." },
    { fronte: "Satana (1863)", retro: "Ode in onore di Satana come simbolo della scienza contro l'oscurantismo religioso. Uno scandalo dell'epoca." },
    { fronte: "Carducci vs Romanticismo", retro: "Polemica con il romanticismo sentimentale tedesco e il «romanticume» italiano. Difende il rigore formale classico." },
    { fronte: "Carducci vs Leopardi", retro: "Leopardi: pessimismo cosmico, natura matrigna. Carducci: fiducia nel progresso, dolore esorcizzato dalla ragione e dalla storia." },
    { fronte: "Il classicismo carducciano", retro: "Non imitazione pedante ma recupero critico dei valori classici: ordine, misura, chiarezza, senso civico." },
    { fronte: "Allievi e continuatori", retro: "Pascoli (allievo a Bologna, poi se ne distacca), D'Annunzio (inizialmente), Ada Negri." },
    { fronte: "Alle fonti del Clitunno", retro: "Ode barbara (1871): il fiume umbro come fonte della civiltà latina. Celebrazione della romanità e del paganesimo contro il Cattolicesimo." },
    { fronte: "Davanti San Guido", retro: "Ode (1874): ritorno ai cipressi di Bolgheri dell'infanzia. Opposizione nostalgia privata vs impegno civile del poeta." },
    { fronte: "Il programma poetico carducciano", retro: "Rinnovamento della poesia italiana tornando ai classici greco-latini e rifiutando il Romanticismo: poesia come disciplina intellettuale e civile." }
  ],

  naturalismo: [
    { fronte: "Cos'è il Naturalismo?", retro: "Movimento letterario francese (1860–1890 ca.) che applica il metodo scientifico-positivista alla narrativa: i personaggi come «casi clinici»." },
    { fronte: "Il fondatore e il manifesto", retro: "Émile Zola; teorizzato nel Romanzo sperimentale (1880): il romanzo come laboratorio scientifico." },
    { fronte: "Cos'è il determinismo?", retro: "Il comportamento umano è determinato da ereditarietà e ambiente. Il personaggio è «prevedibile» come un fenomeno fisico." },
    { fronte: "L'impersonalità naturalista", retro: "L'autore non giudica i personaggi: mostra i fatti come uno specchio. Il narratore è invisibile." },
    { fronte: "Il ciclo dei Rougon-Macquart", retro: "20 romanzi di Zola (1871–1893): storia di una famiglia attraverso ereditarietà e ambiente. Ammazzatoio, Nana, Germinale." },
    { fronte: "Fratelli Goncourt", retro: "Precursori del Naturalismo: Germinie Lacerteux (1865), primo romanzo a descrivere i bassifondi senza pietà né sentimentalismo." },
    { fronte: "Germinale (1885) — tema", retro: "Sciopero dei minatori nel Nord della Francia. Il romanzo più politicamente esplicito di Zola: il proletariato industriale come protagonista." },
    { fronte: "Naturalismo vs Romanticismo", retro: "Romanticismo: emozione, ideale, soggettività. Naturalismo: osservazione, documento, scienza, oggettività." },
    { fronte: "Il ruolo dello scrittore naturalista", retro: "Medico della società: diagnostica le malattie sociali attraverso il romanzo. Impegno sociale e scientifico." },
    { fronte: "L'ambiente nel Naturalismo", retro: "La città industriale (Parigi, Londra) come nuovo protagonista: fabbrica, miseria operaia, prostituzione, alcolismo." },
    { fronte: "Naturalismo vs Verismo", retro: "Naturalismo: Francia, operai, ottimismo progressista. Verismo: Italia meridionale, contadini/pescatori, pessimismo radicale." },
    { fronte: "Influenza del Naturalismo", retro: "Ispira il Verismo italiano (Verga, Capuana), il Realismo nordico (Ibsen), il Realismo russo (Tolstoj)." },
    { fronte: "L'Ammazzatoio (1877)", retro: "Il più celebre romanzo di Zola prima di Germinale: l'alcolismo nella classe operaia parigina. Ambientato nei bassifondi di Parigi." },
    { fronte: "Critica al Naturalismo", retro: "Maupassant: il narratore non è mai veramente impersonale. Il Naturalismo è un'illusione scientifica applicata all'arte." },
    { fronte: "Naturalismo e classe operaia", retro: "Per la prima volta il proletariato è protagonista serio, non solo folkloristico: rottura con la tradizione romantica borghese." }
  ],

  verismo: [
    { fronte: "Cos'è il Verismo?", retro: "Versione italiana del Naturalismo: racconta la realtà del Sud rurale, con pessimismo radicale e nessuna fiducia nel progresso." },
    { fronte: "Verismo vs Naturalismo", retro: "Zola: operai + speranza nel progresso. Verga: contadini/pescatori + pessimismo totale. Il Verismo è la declinazione meridionale e disperata." },
    { fronte: "Il metodo impersonale verista", retro: "L'autore si eclissa: regressione del narratore al livello dei personaggi, discorso indiretto libero (DIL), nessun giudizio esplicito." },
    { fronte: "Temi centrali del Verismo", retro: "Povertà, immobilità sociale, «ideale dell'ostrica», «ciclo dei vinti», il Sud come condizione umana irredimibile." },
    { fronte: "La lingua verista", retro: "Italiano con interferenze dialettali, costruzioni sintattiche popolari, DIL: la voce del popolo senza filtri letterari." },
    { fronte: "Il padre del Verismo", retro: "Giovanni Verga: Rosso Malpelo (1878), Vita dei campi (1880). Capuana è il teorico del movimento." },
    { fronte: "Luigi Capuana — il teorico", retro: "Giacinta (1879): propone un'analisi clinica dei personaggi. Scrive che «la Scienza è il metodo» ma l'arte è più del documento." },
    { fronte: "Federico De Roberto — I Viceré (1894)", retro: "Saga degli Uzeda di Catania: l'aristocrazia siciliana non cambia mai nonostante il Risorgimento. Il più pessimista del Verismo." },
    { fronte: "Matilde Serao — Il ventre di Napoli (1884)", retro: "Reportage-racconto sulla miseria napoletana. «L'Italia non può fare a meno di Napoli, ma Napoli può fare a meno dell'Italia»." },
    { fronte: "Fine del Verismo", retro: "Dopo il 1890 il movimento si esaurisce: il Decadentismo sostituisce l'attenzione sociale con quella all'io interiore." },
    { fronte: "Cos'è la regressione del narratore?", retro: "Il narratore scende al livello culturale e linguistico dei personaggi: adotta la loro mentalità e logica, senza il distacco intellettuale dell'autore." },
    { fronte: "Il pessimismo verista", retro: "Nessuna soluzione: lotta spietata per sopravvivere, chi si stacca dalle radici è schiacciato, il progresso è un'illusione borghese." },
    { fronte: "Cavalleria rusticana — la storia", retro: "Novella (1880) → dramma teatrale (1884) → opera di Mascagni (1890): tradimento, onore e vendetta in Sicilia. La prima opera verista in musica." },
    { fronte: "Il Verismo e il Positivismo", retro: "Applica il metodo osservativo positivista ma senza la fede nel progresso: la scienza serve a smascherare la realtà, non a migliorarla." },
    { fronte: "Cos'è la novella verista?", retro: "La forma breve preferita dal Verismo: sintesi, essenzialità, impassibilità. Vita dei campi (1880), Novelle rusticane (1883)." }
  ],

  decadentismo: [
    { fronte: "Cos'è il Decadentismo?", retro: "Movimento artistico-letterario europeo (1880–1920 ca.) che rifiuta il Positivismo e la razionalità borghese, privilegiando l'irrazionale, il simbolo, l'inconscio." },
    { fronte: "Origine del termine", retro: "Da «décadence»: la rivista Le Décadent (Parigi, 1886) di Anatole Baju. Il termine nasce come insulto, poi rivendicato con orgoglio." },
    { fronte: "Il padre fondatore", retro: "Charles Baudelaire con I fiori del male (1857): la bellezza nel male, il «bello maledetto», la teoria delle corrispondenze." },
    { fronte: "La teoria delle «corrispondenze»", retro: "Sonetto Correspondances (Baudelaire): la natura è un «tempio» di simboli. I sensi si corrispondono tra loro (sinestesia). Il poeta-veggente svela queste connessioni." },
    { fronte: "Cos'è la sinestesia?", retro: "Figura retorica che mescola percezioni sensoriali diverse: «profumi verdi come prati» (Baudelaire). È la tecnica espressiva centrale del Decadentismo." },
    { fronte: "Lo «spleen» baudelairiano", retro: "Noia esistenziale, malessere cosmico, disgusto del mondo borghese: l'opposto dell'«idéal» (l'ideale irraggiungibile). Tensione fondamentale de I fiori del male." },
    { fronte: "Rimbaud e la lettera del veggente (1871)", retro: "Il poeta deve diventare veggente attraverso il «lungo, immenso e ragionato sregolamento di tutti i sensi». La poesia svela la realtà nascosta." },
    { fronte: "Il poeta-veggente", retro: "Rimbaud: il poeta accede all'invisibile attraverso il disordine sensoriale. Ruolo opposto al poeta-vate carducciano: non civile ma mistico." },
    { fronte: "Il concetto di «décadence»", retro: "Rifiuto dei valori borghesi (progresso, lavoro, famiglia), culto della bellezza artificiosa, del perverso, della morte, dell'«artificiale»." },
    { fronte: "Autori decadenti italiani", retro: "D'Annunzio (estetismo e panismo), Pascoli (simbolismo del quotidiano), Campana (orfismo)." },
    { fronte: "Il superuomo decadente", retro: "D'Annunzio: l'artista come essere superiore che vive al di là della morale borghese. «Fare della propria vita un'opera d'arte»." },
    { fronte: "Decadentismo e irrazionalismo", retro: "Contro la scienza positivista: fiducia nei sogni, nell'inconscio, nel mito, nel primitivo, nel simbolo." },
    { fronte: "Differenza Naturalismo-Decadentismo", retro: "Naturalismo: osservazione + scienza + impersonalità. Decadentismo: io + simbolo + musica + irrazionale + estetismo." },
    { fronte: "Il Decadentismo in Europa", retro: "Francia (Baudelaire, Verlaine, Rimbaud, Mallarmé), Inghilterra (Wilde), Germania (Hofmannsthal), Italia (D'Annunzio, Pascoli, Campana)." },
    { fronte: "Decadentismo e simbolismo", retro: "Il Simbolismo è una corrente interna al Decadentismo: tutte le correnti simboliste sono decadenti, ma non tutti i decadenti sono simbolisti." }
  ],

  simbolismo: [
    { fronte: "Cos'è il Simbolismo?", retro: "Corrente poetica francese (1886 ca.) che usa il simbolo per evocare la realtà interiore, rifiutando la descrizione diretta. La poesia deve essere musica." },
    { fronte: "Il manifesto ufficiale", retro: "Jean Moréas sul Le Figaro (1886): la poesia deve «vestire l'Idea di una forma sensibile» attraverso il simbolo, non descrivere." },
    { fronte: "Il motto di Verlaine", retro: "«De la musique avant toute chose» (Arte poetica, 1874): la poesia deve essere musica dell'anima, non descrizione intellettuale." },
    { fronte: "Paul Verlaine — caratteristiche", retro: "Canzoni senza parole (1874): emozioni sfumate, vaghe, musicali. «Prendi l'eloquenza e torcile il collo»: contro la retorica." },
    { fronte: "Arthur Rimbaud — il veggente", retro: "Le illuminazioni (1886), Una stagione all'inferno (1873). Smette di scrivere a 19 anni. Il poeta come profeta sregolato." },
    { fronte: "Stéphane Mallarmé — la poesia pura", retro: "La parola usata per il suo valore sonoro ed evocativo più che per il significato. Poesia come struttura musicale autonoma dal «senso» ordinario." },
    { fronte: "Cos'è il simbolo poetico?", retro: "A differenza dell'allegoria (significato fisso 1:1), il simbolo è polisemico e aperto: evoca stati d'animo e verità inaccessibili alla logica." },
    { fronte: "Il simbolismo cromatico", retro: "I colori portano significati emotivi: bianco = purezza, nero = morte, rosso = passione/violenza. Tecnica chiave in Verlaine, Rimbaud, Campana." },
    { fronte: "Simbolismo e musica", retro: "La poesia simbolista aspira alla condizione della musica: indeterminata, evocativa, corporea. La musica è l'arte assoluta (Schopenhauer)." },
    { fronte: "Simbolismo vs Parnassianesimo", retro: "Parnasso: poesia perfetta nella forma, oggettiva, fredda. Simbolismo: poesia musicale, soggettiva, calda, irrazionale." },
    { fronte: "La sinestesia nel Simbolismo", retro: "«Ho sentito odore di inchiostri, il sonno degli aromi» (Rimbaud): i sensi si mescolano per evocare stati interiori indescrivibili con un solo senso." },
    { fronte: "Influenza del Simbolismo in Italia", retro: "Pascoli (simbolo del quotidiano), D'Annunzio (panismo come simbolismo della natura), Campana (orfismo)." },
    { fronte: "Il fondatore: Baudelaire", retro: "Baudelaire con le Correspondances (1857) è il precursore: la natura come tempio di simboli. I poeti simbolisti si riconoscono suoi eredi." },
    { fronte: "Eredità del Simbolismo nel '900", retro: "Influenza su tutto il modernismo poetico: Ermetismo italiano, T.S. Eliot, W.B. Yeats, García Lorca." },
    { fronte: "Simbolismo e inconscio", retro: "Prima di Freud, il Simbolismo intuisce che la mente ha uno strato non-razionale che la poesia musicale può raggiungere meglio della prosa logica." }
  ],

  estetismo: [
    { fronte: "Cos'è l'Estetismo?", retro: "Movimento artistico-letterario (1880–1900 ca.) che pone la bellezza come valore assoluto, superiore alla morale, all'utilità e alla verità." },
    { fronte: "Il motto", retro: "«Art for Art's Sake» (L'arte per l'arte): Théophile Gautier, poi elaborato da Walter Pater e Oscar Wilde." },
    { fronte: "Walter Pater — il teorico", retro: "Studi sulla storia del Rinascimento (1873): vivere per l'intensità dell'esperienza estetica. «Bruciare sempre con fiamma dura e gemmata»." },
    { fronte: "Oscar Wilde — l'estetista per eccellenza", retro: "Il ritratto di Dorian Gray (1890), L'importanza di chiamarsi Ernesto (1895). «Non sono d'accordo con nessuna cosa. È il mio metodo»." },
    { fronte: "Il dandy", retro: "Personaggio estetista: eleganza assoluta, distacco ironico, culto di sé, rifiuto del lavoro borghese, provocazione come stile di vita." },
    { fronte: "Dorian Gray — sintesi dell'Estetismo", retro: "La bellezza fisica eterna a prezzo dell'anima: il ritratto invecchia al suo posto. Corruzione morale dietro la perfezione estetica." },
    { fronte: "D'Annunzio e l'estetismo italiano", retro: "Andrea Sperelli in Il piacere (1889): «fare della propria vita un'opera d'arte». L'estetismo come programma di vita mondana." },
    { fronte: "Des Esseintes e À rebours (Huysmans, 1884)", retro: "Il prototipo del decadente-estetista: vive in totale isolamento artificiale, rifiuta la natura, coltiva solo sensazioni raffinate e perverse." },
    { fronte: "L'arte come religione", retro: "L'Estetismo eleva l'arte a dimensione spirituale superiore alla religione tradizionale: il bello sostituisce il bene come valore guida." },
    { fronte: "Oscar Wilde — il processo (1895)", retro: "Condannato per «gross indecency» con Lord Alfred Douglas: 2 anni di lavori forzati. De Profundis (1897): riflessione sulla sofferenza e la caduta." },
    { fronte: "Il paradosso wilde-ano", retro: "Lord Henry nel Ritratto: «Only the shallow know themselves». L'intelligenza non è profondità ma superficie brillante. L'ironia è sempre autoironica." },
    { fronte: "La crisi dell'Estetismo", retro: "Wilde e D'Annunzio mostrano entrambi i limiti: Dorian Gray finisce in rovina, Sperelli in paralisi estetica. Il superuomo estetico è una trappola." },
    { fronte: "Estetismo e Decadentismo", retro: "L'Estetismo è una corrente interna al Decadentismo: condivide il rifiuto del Positivismo, ma enfatizza specificamente la bellezza come valore assoluto." },
    { fronte: "Des Esseintes vs Andrea Sperelli", retro: "Des Esseintes: radicale, distrugge la natura per l'artificio. Sperelli: più mondano ed esibizionista, vive tra arte e amore aristocratico." },
    { fronte: "L'eredità dell'Estetismo", retro: "Il design Arts and Crafts (Morris), l'Art Nouveau, il concept di «bella vita» nell'alta borghesia. Sul piano letterario: D'Annunzio come stile di vita nazionale." }
  ],

  futurismo: [
    { fronte: "Cos'è il Futurismo?", retro: "Avanguardia artistica italiana fondata da Marinetti (1909): esaltazione della modernità (macchina, velocità, violenza), rottura totale con la tradizione." },
    { fronte: "Data e luogo di fondazione", retro: "20 febbraio 1909, Le Figaro (Parigi): Manifesto del Futurismo di Filippo Tommaso Marinetti." },
    { fronte: "La citazione simbolo", retro: "«Un'automobile da corsa [...] è più bella della Vittoria di Samotracia»: il mito della modernità contro il passato classico." },
    { fronte: "I punti chiave del Manifesto", retro: "Amore per il pericolo, elogio dell'aggressività, bellezza della velocità, gloria della guerra, distruzione di musei/biblioteche/accademie." },
    { fronte: "Cos'è il «paroliberismo»?", retro: "Eliminazione di sintassi, punteggiatura, aggettivi, avverbi: le parole in libertà per mimarne il dinamismo. Zang Tumb Tuum (1914)." },
    { fronte: "Zang Tumb Tuum (1914)", retro: "Poesia sonora di Marinetti che mima la battaglia di Adrianopoli (1912) con onomatopee, tipografia espressiva e distruzione della sintassi." },
    { fronte: "Futurismo e arte visiva", retro: "Boccioni (Forme uniche nella continuità dello spazio), Balla (Dinamismo di un cane), Russolo (arte dei rumori — intonarumori)." },
    { fronte: "Futurismo e politica", retro: "Nazionalismo aggressivo, interventismo nella WWI, poi fascismo. Marinetti firma il programma fascista nel 1919." },
    { fronte: "Il «passatismo»", retro: "Termine coniato dai Futuristi per indicare il culto del passato: Venezia = «città lacustre», musei = «cimiteri». Tutto il passato va distrutto." },
    { fronte: "Futurismo e la donna", retro: "Misoginia esplicita nel Manifesto: «il disprezzo per la donna». La donna è associata al sentimento, nemico del dinamismo futurista." },
    { fronte: "Futurismo russo (Cubo-Futurismo)", retro: "Majakovskij, Khlebnikov: avanguardia del comunismo, non del nazionalismo. Stessa tecnica linguistica, direzione politica opposta." },
    { fronte: "Il Teatro Futurista", retro: "Sintesi teatrale: spettacoli brevissimi (anche 2 minuti), provocatori, antisentimentali. Lo scopo è scandalizzare il pubblico borghese." },
    { fronte: "Secondo Futurismo (anni '20–'30)", retro: "Dopo la WWI: Aeropittura (esaltazione dell'aviazione). Perde la carica rivoluzionaria e si avvicina al regime fascista." },
    { fronte: "La velocità come nuovo valore estetico", retro: "Treni, automobili, aeroplani trasformano la percezione del tempo e dello spazio: nuova estetica della modernità industriale." },
    { fronte: "Eredità del Futurismo", retro: "Influenza su Dadaismo, Surrealismo, Arte concettuale, performance art. Il concetto di provocazione artistica istituzionalizzata nasce qui." }
  ],

  crepuscolarismo: [
    { fronte: "Cos'è il Crepuscolarismo?", retro: "Corrente poetica italiana (1900–1915 ca.) con tono dimesso, anti-eroico, nostalgia del quotidiano grigio e provinciale. Contro D'Annunzio." },
    { fronte: "L'origine del nome", retro: "Da Giuseppe Antonio Borgese (critico, 1910): la poesia al «crepuscolo» del grande lirismo. I crepuscolari accettano il nome con ironia consapevole." },
    { fronte: "Autori principali", retro: "Guido Gozzano, Corrado Corazzini (muore di tisi a 21 anni), Marino Moretti, Fausto Maria Martini, Sergio Corazzini." },
    { fronte: "Guido Gozzano — caratteristiche", retro: "La via del rifugio (1907), I colloqui (1911): ironia distaccata, rimpianto del passato, eleganza dimessa, autocommiserazione intellettuale." },
    { fronte: "«Le buone cose di pessimo gusto»", retro: "Titolo di poesia di Gozzano (1907): gli oggetti kitsch della nonna come rifugio sentimentale dal presente. La bruttezza quotidiana come poesia." },
    { fronte: "La Signorina Felicita", retro: "L'amata di Gozzano: non bella né eroina, ma autentica e provinciale. Contrario della donna fatale dannunziana. Il suo contrario è intenzionale." },
    { fronte: "Corrado Corazzini vs Gozzano", retro: "Corazzini: sincero dolore, morte come tema ossessivo (muore a 21 anni di tisi). Gozzano: ironia intellettuale distante dalla propria sofferenza." },
    { fronte: "«Io sono un fanciullo che piange» (Corazzini)", retro: "Polemica con il poeta-vate: «Non sono un poeta. Sono un piccolo fanciullo che piange». Rivendicazione dell'inadeguatezza e della semplicità." },
    { fronte: "Il «piccolo mondo» crepuscolare", retro: "Ambienti: case di provincia, giardini in declino, salotti borghesi, vecchie fotografie. Contro le grandi ambizioni eroiche e nazionali." },
    { fronte: "Crepuscolarismo vs D'Annunzio", retro: "Reazione polemica diretta al superomismo: «non siamo eroi». Il tono dimesso è anti-dannunziano per programma estetico." },
    { fronte: "Marino Moretti e la prosa poetica", retro: "«Versi scritti col lapis»: abbassare la poesia al livello della prosa quotidiana. Dialogo diretto e colloquiale con il lettore." },
    { fronte: "Crepuscolarismo e Simbolismo", retro: "Assorbe il simbolismo francese ma ne attenua la tensione verso l'assoluto: l'oggetto simbolico è umile, non trascendente." },
    { fronte: "Fine del Crepuscolarismo", retro: "Soppiantato dal Futurismo (energia vs grigiore) e dalla Grande Guerra (trauma collettivo vs malinconia privata). Gozzano muore di tisi nel 1916." },
    { fronte: "La «muffa sentimentale» di Gozzano", retro: "Gozzano è consapevole di essere «in ritardo» rispetto all'eroismo poetico. L'ironia su se stesso è il marchio del Crepuscolarismo maturo." },
    { fronte: "Eredità del Crepuscolarismo", retro: "Anticipazione del tono colloquiale e quotidiano della poesia del '900. Influenza su Saba (poesia onesta) e sulla linea antinovecentista." }
  ],

  vociani: [
    { fronte: "Chi sono i Vociani?", retro: "Gruppo di scrittori-poeti intorno alla rivista La Voce (Firenze, 1908–1916): Giuseppe Prezzolini, poi Giuseppe De Robertis." },
    { fronte: "La rivista La Voce", retro: "Fondata 1908 da Prezzolini: inizialmente politico-culturale, dal 1914 (De Robertis) puramente letteraria. 264 numeri totali." },
    { fronte: "Autori principali", retro: "Dino Campana, Camillo Sbarbaro, Clemente Rebora, Scipio Slataper, Piero Jahier." },
    { fronte: "Il «frammento» come forma", retro: "I Vociani privilegiano il brano breve, incompiuto, confessionale: contro il romanzo naturalista e la poesia retorica. L'incompletezza è estetica." },
    { fronte: "Camillo Sbarbaro — Pianissimo (1914)", retro: "Poesia dell'indifferenza e dell'aridità interiore. Genova come paesaggio dell'anima. «Io che sono indifferente / al bene e al male»." },
    { fronte: "Clemente Rebora — Frammenti lirici (1913)", retro: "Tensione spirituale tra impegno etico e frammentazione esistenziale. Poi si farà frate rosminiano: la ricerca spirituale come destino." },
    { fronte: "Scipio Slataper — Il mio Carso (1912)", retro: "Prosa lirica sull'identità triestina: tra italiano e sloveno, tra mare e altopiano. Morirà al fronte nel 1915." },
    { fronte: "La «prosa d'arte» vociana", retro: "Genere di confine tra prosa e poesia: frammentata, soggettiva, confessionale. Si oppone sia al romanzo naturalista sia alla poesia retorica." },
    { fronte: "Campana e i Canti orfici (1914)", retro: "Pubblicati autonomamente dopo il rifiuto de La Voce (perso il manoscritto). Campana è il massimo rappresentante dello spirito vociano." },
    { fronte: "Differenza Vociani-Futuristi", retro: "Futurismo: collettivo, rumoroso, politico, ottimista. Vociani: individuali, silenziosi, morali, angosciati. Entrambi rifiutano la tradizione ma in modo opposto." },
    { fronte: "I Vociani e la crisi borghese", retro: "Tutti interrogano l'identità (chi sono? dove vado?) contro il conformismo. Esistenzialismo ante litteram nell'Italia giolittiana." },
    { fronte: "Prima e seconda serie de La Voce", retro: "Prima (1908–1913, Prezzolini): cultura e politica. Seconda (1914–1916, De Robertis): lirica pura e analisi testuale ravvicinata." },
    { fronte: "Il Vocianismo e la Grande Guerra", retro: "Molti Vociani sono interventisti. Slataper muore al fronte (1915). La guerra interrompe il progetto culturale della rivista." },
    { fronte: "La letteratura come responsabilità", retro: "Prezzolini: la letteratura deve contribuire al risanamento morale dell'Italia. Contro il dilettantismo estetico dannunziano." },
    { fronte: "Eredità dei Vociani", retro: "La poetica del frammento influenza l'Ermetismo. La prosa d'arte diventa un genere autonomo degli anni '20–'30 (Moravia, Cardarelli)." }
  ],

  ermetismo: [
    { fronte: "Cos'è l'Ermetismo?", retro: "Corrente poetica italiana (1920–1945 ca.) con linguaggio oscuro e densamente analogico, autonomia assoluta della parola poetica, io lirico rarefatto." },
    { fronte: "L'origine del nome", retro: "Da «ermetico» (sigillato): coniato polemicamente dal critico Francesco Flora (1936). I poeti prima lo rifiutano, poi lo accettano." },
    { fronte: "Autori principali", retro: "Giuseppe Ungaretti (padre), Salvatore Quasimodo, Mario Luzi, Alfonso Gatto, Leonardo Sinisgalli. Centro: Firenze anni '30." },
    { fronte: "La «parola pura» ungarettiana", retro: "La parola ridotta all'essenziale, depurata da ogni retorica: capace di illuminare l'essere. «M'illumino / d'immenso» (1917): 2 versi, infinito." },
    { fronte: "L'analogia nell'Ermetismo", retro: "Due termini lontani uniti senza «come» o «così»: crea immagini folgoranti e polisemiche. Più potente della similitudine perché lascia il lettore nel vuoto." },
    { fronte: "Il centro dell'Ermetismo", retro: "Firenze degli anni '30: la rivista Letteratura, la casa editrice Vallecchi, il critico Carlo Bo, la «scuola fiorentina»." },
    { fronte: "Quasimodo — la fase ermetica", retro: "Acque e terre (1930), Oboe sommerso (1932): la Sicilia come mito dell'origine, parola scarnificata, solitudine cosmica. Premio Nobel 1959." },
    { fronte: "Mario Luzi e l'Ermetismo", retro: "La barca (1935), Avvento notturno (1940): il mistero dell'esistere, linguaggio rarefatto, tensione spirituale cattolica." },
    { fronte: "Ermetismo come risposta al Fascismo", retro: "La poesia oscura è resistenza passiva: l'oscurità protegge dalla censura e contrasta la retorica vuota del fascismo." },
    { fronte: "Differenza Ermetismo-Futurismo", retro: "Futurismo: rumoroso, collettivo, politico, ottimista. Ermetismo: silenzioso, privato, individuale, angosciato." },
    { fronte: "La verticalità dell'Ermetismo", retro: "Ogni parola deve avere densità spirituale: il poema breve concentra più verità di un lungo poema narrativo. Meno = più." },
    { fronte: "Critica all'Ermetismo (Pasolini)", retro: "«Borghese», fuga estetica dalla responsabilità civile. Il poeta deve parlare al popolo: non si può essere oscuri quando ci sono Auschwitz e fame." },
    { fronte: "Quasimodo — la fase civile", retro: "Giorno dopo giorno (1947): «Ognuno sta solo sul cuor della terra / trafitto da un raggio di sole: / ed è subito sera». La guerra cambia tutto." },
    { fronte: "Il tramonto dell'Ermetismo", retro: "Il Neorealismo (1945+) impone la testimonianza diretta. La poesia non può più essere oscura quando deve rendere conto dei campi di sterminio." },
    { fronte: "L'eredità dell'Ermetismo", retro: "La densità del linguaggio poetico contemporaneo italiano. Il «troppo» ermetico genera per reazione sia il Neorealismo sia la poesia antiermetica di Caproni e Saba." }
  ],

  antinovecentismo: [
    { fronte: "Cos'è la «linea antinovecentista»?", retro: "Filone poetico italiano (1920–1960 ca.) che rifiuta l'oscurità ermetica e le avanguardie, cercando chiarezza comunicativa e recupero della tradizione." },
    { fronte: "Il nome", retro: "Pier Vincenzo Mengaldo e altri critici lo usano per indicare gli autori alternativi all'Ermetismo. Non è un gruppo organizzato ma una tendenza." },
    { fronte: "Autori principali", retro: "Umberto Saba, Giorgio Caproni, Cesare Pavese (in poesia), Franco Fortini, Biagio Marin." },
    { fronte: "Saba — la «poesia onesta»", retro: "«Ho amato parole che nessuno amava»: poesia chiara, piana, che dice le cose con il loro nome. Contro l'oscurità ermetica e il superomismo." },
    { fronte: "La «difficile semplicità» di Saba", retro: "«Ho percorso un cammino in senso contrario agli altri poeti del mio tempo: la difficoltà in me è in ciò che ho detto, non nel come.»" },
    { fronte: "Giorgio Caproni", retro: "Il passaggio d'Enea (1956), Il conte di Kevenhuller (1986): viaggio della morte, Genova come spazio dell'anima. Poesia narrativa e colloquiale." },
    { fronte: "Caproni e Saba a confronto", retro: "Entrambi scelgono il quotidiano e la chiarezza. Ma Caproni è più ironico e allegorico (il viaggio, il limite), Saba più direttamente autobiografico." },
    { fronte: "Pavese in poesia — Lavorare stanca (1936)", retro: "Poesia narrativa con il mito delle Langhe piemontesi: paesaggi, figure, storie. Un'alternativa alla poesia lirica ermetica basata sulla narrazione." },
    { fronte: "Franco Fortini", retro: "Foglio di via (1946): poesia impegnata, collettiva, marxista. Contro l'individualismo ermetico. La poesia deve essere strumento di lotta civile." },
    { fronte: "La tradizione come scelta consapevole", retro: "Gli antinovecentisti non sono reazionari: scelgono la forma tradizionale come resistenza alle avanguardie vuote e all'ermetismo borghese." },
    { fronte: "Comunicabilità come valore", retro: "La poesia deve essere comprensibile: non per facilità ma per rispetto del lettore e responsabilità civile. Il Novecento ermetico ha tradito questa responsabilità." },
    { fronte: "Confronto con l'Ermetismo", retro: "Ermetismo: io assoluto, parola sigillata, resistenza passiva. Antinovecentismo: io quotidiano, parola aperta, responsabilità civile attiva." },
    { fronte: "Biagio Marin", retro: "Il poeta dialettale di Grado: la tradizione come resistenza dell'identità locale contro l'omologazione moderna della cultura italiana." },
    { fronte: "Il Canzoniere di Saba — struttura", retro: "Raccolta unica a sezioni (1900–1954): tutta la vita del poeta in ordine cronologico, come un «libro della vita». Modello: Petrarca." },
    { fronte: "Eredità antinovecentista", retro: "Influenza sulla poesia degli anni '60–'70. Il Gruppo 63 deve fare i conti sia con l'Ermetismo sia con questa linea alternativa. La chiarezza sopravvive all'ermetismo." }
  ],

  neorealismo: [
    { fronte: "Cos'è il Neorealismo?", retro: "Movimento letterario e cinematografico italiano (1945–1955 ca.): racconta la guerra, la Resistenza, la miseria popolare con stile diretto e linguaggio parlato." },
    { fronte: "Il contesto storico", retro: "Fine della WWII, liberazione dal fascismo, Resistenza partigiana: la letteratura deve rendere conto della storia. Non si può tornare all'Ermetismo." },
    { fronte: "Autori principali", retro: "Calvino (Il sentiero dei nidi di ragno), Pavese (La casa in collina), Fenoglio (I ventitré giorni), Primo Levi (Se questo è un uomo), Vittorini (Uomini e no)." },
    { fronte: "Il Neorealismo cinematografico", retro: "Rossellini (Roma città aperta, 1945), De Sica (Ladri di biciclette, 1948), Visconti (La terra trema, 1948): stessa poetica, ripresa esterna, attori non professionisti." },
    { fronte: "Lo stile neorealista", retro: "Linguaggio semplice, diretto, spesso dialettale; frasi brevi; il dialetto come voce autentica del popolo. Anti-letterario come programma." },
    { fronte: "Il «narratore testimone»", retro: "Il narratore è qualcuno che c'era: racconta con immedesimazione totale. Diverso dall'impersonalità naturalista — qui l'io morale è sempre presente." },
    { fronte: "Calvino e il Neorealismo", retro: "Il sentiero dei nidi di ragno (1947): la Resistenza vista da un bambino (Pin). Distanza ironica e fiabesca già nella prima opera: il Neorealismo «strano» di Calvino." },
    { fronte: "Pavese e il trauma del ritorno", retro: "La casa in collina (1949): un intellettuale che non riesce a combattere. Senso di colpa per la propria neutralità. La guerra degli altri." },
    { fronte: "Levi e la testimonianza", retro: "Se questo è un uomo (1947): documento del lager nazista. «Se questo è un uomo / che lavora nel fango». La scrittura come dovere morale." },
    { fronte: "Il «documento» nel Neorealismo", retro: "La realtà vale più dell'invenzione: i fatti della guerra, la miseria, i paesaggi reali (Langhe, borghi meridionali) come materiale grezzo non elaborato." },
    { fronte: "Neorealismo e impegno gramsciano", retro: "La letteratura deve essere nazionale-popolare: raggiungere le masse, non solo gli intellettuali. Risposta al manifesto culturale del PCI del dopoguerra." },
    { fronte: "Neorealismo vs Ermetismo", retro: "Ermetismo: io privato, parola sigillata, resistenza passiva. Neorealismo: io collettivo, parola aperta, testimonianza attiva." },
    { fronte: "La crisi del Neorealismo", retro: "Calvino (prefazione 1964): col benessere degli anni '50 il senso urgente della storia si perde. Il Neorealismo non può durare oltre la contingenza storica." },
    { fronte: "Critica interna (Pasolini)", retro: "Il Neorealismo ha trattato il popolo come materiale documentario senza capirlo davvero. La critica più feroce viene da Pasolini, che viene dall'interno." },
    { fronte: "L'eredità del Neorealismo", retro: "Influenza sul cinema italiano fino agli anni '70, sulla letteratura impegnata (Sciascia, Morante, Volponi). Ma la forma «pura» dura meno di un decennio." }
  ]

};
