/* =========================================================================
   flashcard-data.js — Banca flashcard per autore
   Minimo 20 carte per autore: date, poetica, opere, testi, figure, confronti.
   ========================================================================= */
window.flashcardData = {

  verga: [
    { fronte: "Anni di nascita e morte di Verga", retro: "1840 – 1922, Catania" },
    { fronte: "Cos'è la «svolta verista»?", retro: "Dal 1878 (Rosso Malpelo) abbandona il romanzo mondano e adotta l'impersonalità naturalista applicata al Sud rurale." },
    { fronte: "Cos'è l'impersonalità verghiana?", retro: "L'autore si eclissa: «la mano dell'artista deve restare invisibile». Non è metodo scientifico ma conseguenza del pessimismo." },
    { fronte: "Cos'è la regressione del narratore?", retro: "L'autore scende al livello culturale e linguistico dei personaggi, adottandone mentalità e logica." },
    { fronte: "Cos'è il Discorso Indiretto Libero (DIL)?", retro: "Pensieri e parole dei personaggi senza virgolette né verba dicendi: si fonde la voce del narratore con quella del personaggio." },
    { fronte: "Cos'è la «fiumana del progresso»?", retro: "Metafora (Prefazione ai Malavoglia): il progresso come forza cieca che travolge i deboli, i «vinti», senza beneficarli." },
    { fronte: "Cos'è l'«ideale dell'ostrica»?", retro: "Da Fantasticheria: per sopravvivere bisogna restare attaccati al proprio ambiente come l'ostrica allo scoglio; chi si stacca è divorato." },
    { fronte: "Chi è Rosso Malpelo?", retro: "Bambino dai capelli rossi che lavora in una cava di rena. Escluso per pregiudizio, non per colpa: muore nelle gallerie." },
    { fronte: "Cos'è «la roba» per Mazzarò?", retro: "L'unica forma di identità e riscatto: l'accumulo ossessivo di beni. Ma alla morte non si può portare nulla." },
    { fronte: "Che cos'è il Ciclo dei Vinti?", retro: "Progetto di 5 romanzi sulla scala sociale: realizzati solo I Malavoglia (1881) e Mastro-don Gesualdo (1889)." },
    { fronte: "Trama de I Malavoglia (1881)", retro: "La famiglia Toscano di Aci Trezza perde la casa del nespolo dopo il naufragio della Provvidenza. Chi resta (Alessi) si salva; chi parte ('Ntoni) si perde." },
    { fronte: "Il significato del titolo «Mastro-don Gesualdo»", retro: "Mastro (manovale) + Don (notabile): due identità incompatibili. Gesualdo vince economicamente ma muore solo." },
    { fronte: "Prima raccolta verista di Verga", retro: "Vita dei campi (1880): Rosso Malpelo, La lupa, Cavalleria rusticana, Fantasticheria." },
    { fronte: "Tema centrale di Novelle rusticane (1883)", retro: "La «roba»: l'ossessione per i beni materiali e l'interesse economico. Contiene La roba e Libertà." },
    { fronte: "Cos'è lo straniamento in Verga?", retro: "Fatti assurdi presentati come normali (e viceversa) dal narratore regredito: il lettore vede l'assurdità che i personaggi non vedono." },
    { fronte: "Differenza Verga vs Zola", retro: "Stessa impersonalità, ragioni opposte: Zola per metodo scientifico e fiducia nel progresso; Verga per pessimismo filosofico, senza riscatto." },
    { fronte: "Differenza Verga vs Manzoni", retro: "Stesso interesse per gli umili, ma Verga non ha narratore onnisciente né Provvidenza: solo distacco e pessimismo." },
    { fronte: "Da quale corrente nasce il Verismo?", retro: "Dal Naturalismo francese di Zola, ma con pessimismo più radicale e ambientazione nel Sud arcaico." },
    { fronte: "Cosa fa Verga dal 1893?", retro: "Torna a Catania e smette di scrivere: silenzio letterario quasi trentennale. Il ciclo resta incompiuto." },
    { fronte: "Il finale de I Malavoglia", retro: "'Ntoni torna di notte, ma la casa è «veleno»: «Ora che so ogni cosa devo andarmene». La conoscenza come condanna." }
  ],

  pascoli: [
    { fronte: "Anni di nascita e morte di Pascoli", retro: "1855 – 1912, San Mauro di Romagna" },
    { fronte: "Il trauma fondativo di Pascoli", retro: "L'assassinio del padre Ruggero il 10 agosto 1867, rimasto impunito: il «nido» spezzato." },
    { fronte: "Cos'è il «fanciullino»?", retro: "La voce interiore infantile che vede il mondo con meraviglia e crea poesia per intuizione. Saggio del 1897." },
    { fronte: "Cos'è il «nido»?", retro: "La casa e la famiglia come rifugio dal male esterno: luogo affettivo ma fragile, sempre minacciato." },
    { fronte: "Cos'è il fonosimbolismo?", retro: "Il suono delle parole vale quanto il significato: onomatopee, allitterazioni riproducono la natura («bubbolìo»)." },
    { fronte: "Prima e più celebre raccolta di Pascoli", retro: "Myricae (1891): le piccole cose, la natura, la morte, la memoria. Il titolo richiama le umili tamerici virgiliane." },
    { fronte: "Raccolta dedicata alla madre", retro: "Canti di Castelvecchio: il nido, le stagioni, la campagna, i suoni naturali." },
    { fronte: "Tema di X Agosto", retro: "Il lutto per il padre: parallelo rondine/padre uccisi mentre tornano al nido. «Disse: Perché?»" },
    { fronte: "Tema di Lavandare", retro: "L'abbandono: l'aratro senza buoi e il canto delle lavandaie. «Nessuno attende a casa.»" },
    { fronte: "Tema de L'assiuolo", retro: "Il verso «Chiù» dell'assiuolo come eco di morte; il fantasma della sorella che passa nell'alba." },
    { fronte: "Tema di Novembre", retro: "L'inganno delle apparenze: una scena apparentemente primaverile si rovescia nell'«estate fredda dei morti» (ossimoro)." },
    { fronte: "Tema de Il gelsomino notturno", retro: "La vita che nasce nel buio (la notte di nozze); il poeta escluso, che pensa ai suoi morti." },
    { fronte: "Cos'è il poemetto Italy?", retro: "Dai Poemetti: l'emigrazione, il ritorno dei figli con lingua ibrida italo-inglese, la morte della piccola Molly." },
    { fronte: "Cos'è La grande proletaria si è mossa?", retro: "Discorso del 1911 che giustifica la guerra di Libia: la fase civile e nazionalista di Pascoli." },
    { fronte: "Differenza Pascoli vs D'Annunzio", retro: "I due poli del Decadentismo italiano: il fanciullino (Pascoli) contro il vate-superuomo (D'Annunzio)." },
    { fronte: "Differenza Pascoli e Leopardi", retro: "Entrambi leggono dolore e natura, ma Leopardi tende alla natura matrigna; Pascoli alla natura simbolica e ai legami familiari." },
    { fronte: "A quale corrente è legato Pascoli?", retro: "Al Simbolismo/Decadentismo italiano, in chiave dimessa e domestica." },
    { fronte: "Figura retorica tipica di Pascoli", retro: "L'onomatopea e l'analogia; lo stile «franto», impressionistico." },
    { fronte: "Cosa rappresenta la rondine in X Agosto", retro: "Il padre che torna al nido e viene ucciso; «come in croce» con il verme in bocca: il male cosmico." },
    { fronte: "Il rovesciamento finale de L'assiuolo", retro: "Il «chiù» da suono notturno diventa voce dall'aldilà; «Il mio cuore si è rotto»." }
  ],

  dannunzio: [
    { fronte: "Anni di nascita e morte di D'Annunzio", retro: "1863 – 1938, Pescara" },
    { fronte: "Cos'è l'estetismo dannunziano?", retro: "La vita come opera d'arte; il culto della bellezza e del piacere. Modello: Andrea Sperelli ne Il piacere." },
    { fronte: "Cos'è il superuomo dannunziano?", retro: "Da Nietzsche: l'uomo superiore che si pone oltre la morale comune, dominatore ed esteta." },
    { fronte: "Cos'è il panismo?", retro: "La fusione totale dell'io con la natura (da «Pan»): l'uomo che si dissolve nelle forze naturali. Vertice in Alcyone." },
    { fronte: "Il romanzo dell'estetismo", retro: "Il piacere (1889): Andrea Sperelli, il dandy che vive secondo «fare della propria vita un'opera d'arte»." },
    { fronte: "Il capolavoro lirico di D'Annunzio", retro: "Alcyone (1903): l'estate, il panismo, La pioggia nel pineto, La sera fiesolana." },
    { fronte: "Tema de La pioggia nel pineto", retro: "Il panismo: l'io e l'amata Ermione si trasformano in creature vegetali sotto la pioggia. Musicalità e sinestesia." },
    { fronte: "Cos'è la «fase notturna»?", retro: "Il Notturno (1916): prosa frammentaria scritta da quasi cieco, più intima e meditativa." },
    { fronte: "Figura retorica tipica di D'Annunzio", retro: "La sinestesia e l'analogia; la musicalità del verso, l'allitterazione." },
    { fronte: "D'Annunzio e la politica", retro: "Interventista, eroe di guerra, l'impresa di Fiume (1919): il «vate» che fa della vita un gesto pubblico." },
    { fronte: "Cos'è il «vate»?", retro: "Il poeta-profeta che guida la nazione, modella i miti collettivi: D'Annunzio incarna questo ruolo." },
    { fronte: "I tre romanzi della «rosa»", retro: "Il piacere, L'innocente, Il trionfo della morte: i romanzi dell'estetismo e del superuomo." },
    { fronte: "Differenza D'Annunzio vs Verga", retro: "Opposti: D'Annunzio esalta l'io e il trionfo; Verga lo cancella e descrive la sconfitta dei vinti." },
    { fronte: "Differenza D'Annunzio vs Pascoli", retro: "I due poli del Decadentismo: il vate-superuomo contro il poeta-fanciullino." },
    { fronte: "La raccolta poetica maggiore", retro: "Le Laudi (Maia, Elettra, Alcyone): Alcyone è il libro dell'estate e del panismo." },
    { fronte: "Cosa significa «fare della propria vita un'opera d'arte»?", retro: "L'estetismo applicato all'esistenza: vivere con la massima intensità ed eleganza, come un personaggio." },
    { fronte: "L'influenza filosofica su D'Annunzio", retro: "Nietzsche (superuomo, volontà di potenza) e l'estetismo europeo (Wilde, Pater, Huysmans)." },
    { fronte: "Cos'è la sinestesia?", retro: "La fusione di sensazioni di sensi diversi (es. «verde silenzio»): figura chiave dello stile dannunziano." },
    { fronte: "Tema de La sera fiesolana", retro: "Il paesaggio toscano al tramonto come esperienza panica e religiosa; lode della sera e della natura." },
    { fronte: "Perché D'Annunzio è «decadente»", retro: "Per l'estetismo, il culto della bellezza e del piacere, la sensibilità sovraeccitata, il rifiuto del borghese." }
  ],

  pirandello: [
    { fronte: "Anni di nascita e morte di Pirandello", retro: "1867 – 1936, Agrigento. Nobel 1934." },
    { fronte: "Cos'è l'umorismo pirandelliano?", retro: "«Avvertimento» del contrario (comico) + «sentimento» del contrario (riflessione che lo rende pietoso): saggio L'umorismo (1908)." },
    { fronte: "Cos'è il relativismo conoscitivo?", retro: "Non esiste una verità oggettiva: ognuno ha la propria. La realtà dipende dal punto di vista." },
    { fronte: "Cos'è il contrasto «vita» e «forma»?", retro: "La vita è flusso continuo; la forma è la maschera fissa che la società ci impone. L'uomo soffoca nelle forme." },
    { fronte: "Cos'è la «maschera»?", retro: "L'identità sociale fittizia imposta dagli altri; sotto, nessun volto stabile. «Uno, nessuno e centomila»." },
    { fronte: "Trama de Il fu Mattia Pascal (1904)", retro: "Mattia, creduto morto, prova una nuova identità (Adriano Meis) ma scopre che senza stato civile non si può vivere: torna «il fu»." },
    { fronte: "Trama di Uno, nessuno e centomila", retro: "Vitangelo Moscarda scopre di essere visto in centomila modi diversi; distrugge la propria identità per liberarsi delle forme." },
    { fronte: "Cos'è il «teatro nel teatro»?", retro: "La trilogia metateatrale: Sei personaggi in cerca d'autore mostra la finzione teatrale stessa sulla scena." },
    { fronte: "Trama di Sei personaggi in cerca d'autore", retro: "Sei personaggi irrompono in un teatro chiedendo a una compagnia di rappresentare il loro dramma: realtà e finzione si confondono." },
    { fronte: "Cos'è Enrico IV?", retro: "Dramma: un uomo che, creduto pazzo, finge di essere l'imperatore Enrico IV; la maschera della follia come rifugio." },
    { fronte: "Raccolta di novelle di Pirandello", retro: "Novelle per un anno: 365 novelle progettate; la condizione umana còlta in episodi paradossali." },
    { fronte: "Cos'è la «trappola»?", retro: "La vita sociale (famiglia, lavoro, ruoli) come trappola che imprigiona l'individuo nelle forme." },
    { fronte: "Differenza Pirandello vs Verga", retro: "Entrambi siciliani, ma Verga attribuisce la sconfitta a leggi naturali; Pirandello alla struttura relativa di realtà e identità." },
    { fronte: "Differenza Pirandello vs Svevo", retro: "Entrambi indagano la crisi dell'io: Svevo con la psicanalisi e l'ironia; Pirandello con il relativismo e la maschera." },
    { fronte: "Cos'è il «forestiere della vita»?", retro: "Chi, vedendosi vivere dall'esterno, si sente estraneo a sé e al mondo: condizione tipica dei personaggi pirandelliani." },
    { fronte: "Periodo del «teatro grottesco»", retro: "Anni '10–'20: drammi che smascherano l'ipocrisia borghese (Così è (se vi pare), Il berretto a sonagli)." },
    { fronte: "Cos'è Così è (se vi pare)?", retro: "Dramma sul relativismo: nessuno può stabilire la verità sulla signora Ponza; «io sono colei che mi si crede»." },
    { fronte: "L'influenza filosofica su Pirandello", retro: "Il vitalismo di Bergson, il relativismo, la crisi del positivismo e dell'io unitario." },
    { fronte: "Pirandello e il fascismo", retro: "Aderì al fascismo (1924) ma il suo teatro resta critico verso ogni forma e autorità imposta." },
    { fronte: "Il significato di «Uno, nessuno e centomila»", retro: "Uno (come ci crediamo), centomila (come ci vedono gli altri), nessuno (la verità: nessuna identità fissa)." }
  ],

  svevo: [
    { fronte: "Anni di nascita e morte di Svevo", retro: "1861 – 1928, Trieste. Pseudonimo di Ettore Schmitz." },
    { fronte: "Cos'è l'«inetto» sveviano?", retro: "Il personaggio incapace di vivere e agire, paralizzato dal divario tra vita interiore e realtà: Alfonso, Emilio, Zeno." },
    { fronte: "Cos'è la «malattia» in Svevo?", retro: "Non solo fisica: la nevrosi, l'inettitudine come condizione esistenziale e, nel finale di Zeno, malattia della civiltà." },
    { fronte: "Cos'è l'autoinganno?", retro: "Il meccanismo per cui il personaggio si racconta una storia falsa su di sé: Zeno crede di voler smettere di fumare." },
    { fronte: "Cos'è il narratore inattendibile?", retro: "Il narratore (Zeno) di cui il lettore non può fidarsi: bisogna leggere «tra le righe»." },
    { fronte: "Trama di Una vita (1892)", retro: "Alfonso Nitti, impiegato di provincia con grandi speranze deluse a Trieste: il primo inetto, finisce suicida." },
    { fronte: "Cos'è la «senilità» in Svevo?", retro: "Non l'età ma uno stato dell'anima: l'incapacità di vivere pienamente. Emilio Brentani ha 35 anni ma è già «vecchio»." },
    { fronte: "Trama di Senilità (1898)", retro: "Emilio Brentani si illude di poter controllare la passione per Angiolina chiamandola «capriccio»: l'autoinganno." },
    { fronte: "Il capolavoro di Svevo", retro: "La coscienza di Zeno (1923): il romanzo della psicanalisi, dell'inettitudine e dell'ironia." },
    { fronte: "La struttura de La coscienza di Zeno", retro: "Un memoriale scritto per la terapia psicanalitica, organizzato per temi (il fumo, il padre, la moglie...), non cronologico." },
    { fronte: "Cosa simboleggia l'«ultima sigaretta»?", retro: "La malattia della volontà: Zeno non vuole davvero smettere ma ha bisogno di crederlo. «Ogni sigaretta è l'ultima.»" },
    { fronte: "Il finale de La coscienza di Zeno", retro: "«La vita è inquinata alle radici»: la malattia è universale, della civiltà; profezia di un ordigno che distruggerà la Terra." },
    { fronte: "Influenza di Freud su Svevo", retro: "La psicanalisi struttura il romanzo (il memoriale, l'analisi del profondo), ma Svevo ne è anche ironico e critico." },
    { fronte: "Influenza filosofica su Svevo", retro: "Schopenhauer (la volontà), Darwin (la lotta per la vita), Nietzsche, oltre a Freud." },
    { fronte: "Il rapporto di Svevo con Joyce", retro: "James Joyce, suo insegnante d'inglese a Trieste, lo incoraggiò e ne favorì la fortuna europea." },
    { fronte: "Trieste in Svevo", retro: "Città di frontiera, mercantile, mitteleuropea: spazio dell'alienazione e dell'incrocio di culture." },
    { fronte: "Differenza Svevo vs Verga", retro: "Verga: impersonalità e ceti bassi del Sud rurale. Svevo: introspezione e borghesia urbana mitteleuropea." },
    { fronte: "Differenza Svevo vs Pirandello", retro: "Entrambi indagano la crisi dell'io; Svevo con ironia e psicanalisi, Pirandello con relativismo e maschera." },
    { fronte: "Perché Zeno «guarisce»?", retro: "Non grazie alla psicanalisi (che abbandona): accetta la propria nevrosi come condizione normale e ci ride sopra." },
    { fronte: "La «salute» di Augusta vs la «malattia» di Zeno", retro: "Augusta, moglie «sana», vive senza dubbi; Zeno, «malato», è più lucido: la malattia come forma di coscienza." }
  ],

  ungaretti: [
    { fronte: "Anni di nascita e morte di Ungaretti", retro: "1888 – 1970, nato ad Alessandria d'Egitto." },
    { fronte: "Cos'è l'illuminazione poetica?", retro: "L'attimo in cui la parola rivela l'assoluto e l'io si fonde con il tutto. «M'illumino d'immenso»." },
    { fronte: "Cos'è la «parola» in Ungaretti?", retro: "La parola ridotta all'essenziale, isolata nel bianco della pagina, caricata di valore assoluto." },
    { fronte: "Prima raccolta di Ungaretti", retro: "L'allegria (1916/1931): la poesia di trincea, il verso brevissimo, la parola nuda." },
    { fronte: "Tema di Mattina", retro: "L'illuminazione: «M'illumino / d'immenso». Due parole, un'intera poetica di fusione con l'infinito." },
    { fronte: "Tema di Soldati", retro: "La precarietà assoluta: «Si sta come / d'autunno / sugli alberi / le foglie». L'unanimismo." },
    { fronte: "Tema di Veglia", retro: "Il paradosso vita/morte: accanto al compagno morto, «non sono mai stato tanto attaccato alla vita»." },
    { fronte: "Tema di Fratelli", retro: "La fraternità universale di fronte alla morte; la parola «fratelli» come «foglia appena nata»." },
    { fronte: "Tema de Il porto sepolto", retro: "Manifesto della poetica: il poeta scende nell'abisso e risale con i canti; resta «un nulla d'inesauribile segreto»." },
    { fronte: "Tema de I fiumi", retro: "L'identità nomade attraverso quattro fiumi (Isonzo, Serchio, Nilo, Senna); «docile fibra dell'universo»." },
    { fronte: "Tema di San Martino del Carso", retro: "La distruzione della guerra: del paese e dei compagni «non è rimasto nemmeno tanto»; «È il mio cuore il paese più straziato»." },
    { fronte: "Tema di Peso", retro: "L'attesa di una purificazione futura: «Quando il mio peso mi sarà / leggero». Impulso mistico." },
    { fronte: "La seconda fase di Ungaretti", retro: "Sentimento del tempo (1933): recupero della tradizione, del verso più disteso, della religiosità (la «conversione»)." },
    { fronte: "La terza fase di Ungaretti", retro: "Il dolore (1947): il lutto per il figlio Antonietto e per la guerra; tono meditativo e civile." },
    { fronte: "Tema di Non gridate più", retro: "Da Il dolore: il rispetto per i morti, il silenzio come unica via per ascoltarli. «Cessate d'uccidere i morti»." },
    { fronte: "A quale corrente è legato Ungaretti?", retro: "All'Ermetismo, di cui è il maestro e il precursore (con i Vociani alle spalle)." },
    { fronte: "Figura retorica tipica di Ungaretti", retro: "L'analogia (accostamento di immagini distanti senza «come») e l'ossimoro («corolla di tenebre»)." },
    { fronte: "Cos'è lo «spazio bianco»?", retro: "Il silenzio attorno alle poche parole, che le fa «esplodere»: elemento attivo della poesia, non vuoto." },
    { fronte: "Influenze su Ungaretti", retro: "Il Simbolismo francese (Mallarmé), i Vociani, l'esperienza della Prima guerra mondiale." },
    { fronte: "Cos'è l'unanimismo?", retro: "Il sentimento di appartenenza a un destino comune di tutta l'umanità; in Soldati il «si sta» impersonale." }
  ],

  saba: [
    { fronte: "Anni di nascita e morte di Saba", retro: "1883 – 1957, Trieste. Pseudonimo di Umberto Poli." },
    { fronte: "Cos'è la «poesia onesta»?", retro: "Una poesia chiara, sincera, fatta di «trite parole», contro l'oscurità ermetica e la retorica." },
    { fronte: "L'opera di una vita di Saba", retro: "Il Canzoniere: raccoglie tutte le poesie dal 1900 al 1954, come un unico libro autobiografico." },
    { fronte: "Cosa sono le «trite parole»?", retro: "Le parole comuni, logorate dall'uso (amore, madre, città): le più difficili perché le più cariche di significato umano." },
    { fronte: "Trieste in Saba", retro: "La città natale come specchio dell'anima: «scontrosa grazia», ambivalente come il poeta stesso." },
    { fronte: "Tema di Amai", retro: "La dichiarazione di poetica: «Amai trite parole che non uno / osava»; la rima fiore/amore; la verità al fondo." },
    { fronte: "Tema di A mia moglie", retro: "L'amore per Lina espresso paragonandola a femmine di animali domestici: «avvicinano a Dio»." },
    { fronte: "Tema de La capra", retro: "Il dolore universale: il belato della capra «dal viso semita» è «fraterno» al dolore del poeta." },
    { fronte: "Tema di Città vecchia", retro: "La fraternità con la «perduta gente» dei vicoli di Trieste: in loro «s'agita il Signore»." },
    { fronte: "Tema di Mio padre è stato per me «l'assassino»", retro: "Il capovolgimento del giudizio sul padre; «due razze in antica tenzone»: pesantezza materna vs leggerezza paterna." },
    { fronte: "Tema di Ulisse", retro: "Il mito di Ulisse autobiografico: la vecchiaia come isola «sempre più sola, sempre più difficile da raggiunger»." },
    { fronte: "Il romanzo di Saba", retro: "Ernesto (1953, postumo 1975): la scoperta della sessualità, l'onestà radicale; rimasto a lungo nel cassetto." },
    { fronte: "La psicanalisi in Saba", retro: "Si analizzò con il dottor Weiss (allievo di Freud); la scissione interiore e i fantasmi familiari nutrono la poesia." },
    { fronte: "L'identità ebraica di Saba", retro: "La madre era ebrea; il tema della diversità e della «scissione» (il «viso semita» della capra) attraversa l'opera." },
    { fronte: "A quale linea appartiene Saba?", retro: "Alla linea antinovecentista: chiarezza e tradizione contro l'oscurità dell'Ermetismo." },
    { fronte: "Cos'è la «scontrosa grazia»?", retro: "Ossimoro che descrive Trieste (e Saba): riservata eppure piena di vita, ruvida e dolce insieme." },
    { fronte: "Il modello metrico di Saba", retro: "La tradizione (Petrarca, Leopardi): il Canzoniere, il sonetto, l'endecasillabo, rinnovati dall'interno." },
    { fronte: "Differenza Saba vs Ermetismo", retro: "Saba: chiarezza, poesia onesta, parole comuni. Ermetismo: oscurità, parola assoluta, analogia." },
    { fronte: "Le sezioni del Canzoniere", retro: "Casa e campagna, Trieste e una donna, Il piccolo Berto, Autobiografia, Parole, Mediterranee..." },
    { fronte: "Il rapporto di Saba con la madre", retro: "Madre severa, opposta al padre «gaio e leggero» che l'aveva abbandonata: conflitto interiore irrisolto." }
  ],

  montale: [
    { fronte: "Anni di nascita e morte di Montale", retro: "1896 – 1981, Genova. Nobel 1975." },
    { fronte: "Cos'è il «male di vivere»?", retro: "La condizione esistenziale di sofferenza e prigionia connaturata all'esistenza, non agli eventi storici." },
    { fronte: "Cos'è il correlativo oggettivo?", retro: "Da T.S. Eliot: un oggetto fisico che «contiene» l'emozione senza nominarla (il rivo strozzato = il male di vivere)." },
    { fronte: "Cos'è la «divina Indifferenza»?", retro: "La natura estranea al dolore umano: non nemica né amica, semplicemente indifferente. La statua, la nuvola, il falco." },
    { fronte: "Cos'è il «varco»?", retro: "La ricerca, quasi sempre fallita, di una via di fuga o di senso dal male di vivere." },
    { fronte: "Prima raccolta di Montale", retro: "Ossi di seppia (1925): il male di vivere, il paesaggio ligure, il muro. Lo stile aspro e antimusicale." },
    { fronte: "Cosa sono gli «ossi di seppia»?", retro: "I residui calcarei dei molluschi: l'uomo spogliato di illusioni, arenato, esiliato." },
    { fronte: "Tema di Non chiederci la parola", retro: "Manifesto: la poesia non dà certezze, sa dire solo «ciò che non siamo, ciò che non vogliamo». Poetica della negazione." },
    { fronte: "Tema di Spesso il male di vivere", retro: "Tre correlativi del male (rivo strozzato, foglia riarsa, cavallo stramazzato) + tre della divina Indifferenza." },
    { fronte: "Tema di Meriggiare pallido e assorto", retro: "Il muro «con in cima cocci aguzzi di bottiglia»: l'esistenza come prigione invalicabile." },
    { fronte: "Tema de La casa dei doganieri", retro: "La memoria che tradisce: «Tu non ricordi»; la bussola impazzita; la separazione definitiva da Clizia." },
    { fronte: "Tema di Ho sceso, dandoti il braccio", retro: "Elegia per Mosca morta: lei, miope, «aveva le sole vere pupille»; il paradosso miopia/visione. Stile prosastico." },
    { fronte: "La seconda raccolta di Montale", retro: "Le occasioni (1939): i Mottetti, Clizia, la lingua più oscura e aristocratica." },
    { fronte: "Chi è Clizia?", retro: "Irma Brandeis, studiosa ebrea americana: donna-angelo, messaggera cosmica, simbolo di resistenza contro il nazifascismo." },
    { fronte: "Chi è Mosca?", retro: "Drusilla Tanzi, la moglie: soprannome per la miopia. Guida pratica e quotidiana; gli Xenia di Satura la commemorano." },
    { fronte: "La raccolta della svolta prosastica", retro: "Satura (1971): stile ironico, diaristico, quotidiano; gli Xenia per Mosca morta." },
    { fronte: "A quale corrente si avvicina Montale?", retro: "All'area ermetica (specie nelle Occasioni), pur con una posizione autonoma e antiretorica." },
    { fronte: "Cos'è la «pathetic fallacy rovesciata»?", retro: "Al contrario del Romanticismo, la natura non rispecchia i sentimenti umani: è indifferente." },
    { fronte: "Differenza Montale vs Ungaretti", retro: "Ungaretti ha epifanie/illuminazione; Montale ha lo scacco permanente, il varco fallito." },
    { fronte: "Differenza Montale vs D'Annunzio", retro: "Montale è l'anti-vate: rifiuta la poesia profetica e la parola che «apre mondi»." }
  ],

  campana: [
    { fronte: "Anni di nascita e morte di Campana", retro: "1885 – 1932, Marradi. Morì internato in manicomio." },
    { fronte: "Cos'è la poesia «orfica»?", retro: "Poesia come discesa agli inferi e rivelazione (dal mito di Orfeo): parola magica, visione, non comunicazione." },
    { fronte: "L'unica opera di Campana", retro: "Canti orfici (1914), pubblicati a proprie spese dopo la perdita del primo manoscritto." },
    { fronte: "Cosa accadde al primo manoscritto?", retro: "Il più lungo giorno fu consegnato a Soffici e Papini nel 1913 e perduto; Campana lo riscrisse a memoria. Ritrovato nel 1971." },
    { fronte: "Cos'è la «musicalità ossessiva»?", retro: "La ripetizione di immagini e parole come incantesimo: il ritmo ipnotico tipico dei Canti orfici." },
    { fronte: "Tema de La Chimera", retro: "La ricerca di una bellezza assoluta e sfuggente, figura femminile-mito; il testo più celebre." },
    { fronte: "Tema de L'invetriata", retro: "La visione cromatica e onirica; il rosso, la sera, la finestra: la realtà trasfigurata." },
    { fronte: "Il simbolismo cromatico di Campana", retro: "I colori (rosso, nero) caricati di valore simbolico ed emotivo: visione più che descrizione." },
    { fronte: "A quale corrente è vicino Campana?", retro: "Ai Vociani (area de La Voce), ma da outsider; influenzato dal Simbolismo francese." },
    { fronte: "Le letture di Campana", retro: "Autodidatta: legge Baudelaire e Rimbaud in francese, Nietzsche in tedesco, Whitman in inglese." },
    { fronte: "La relazione con Sibilla Aleramo", retro: "Tormentata storia d'amore (1916–17); il loro carteggio è tra i più intensi del Novecento." },
    { fronte: "Cosa significa che la poesia «rivela»?", retro: "Non comunica un messaggio razionale: riporta dalle zone oscure del reale una verità intraducibile." },
    { fronte: "Il vagabondaggio in Campana", retro: "Tema biografico e poetico: i viaggi (anche in Sud America), l'errare come condizione esistenziale." },
    { fronte: "La fine di Campana", retro: "Internato nel 1918 a Castel Pulci, vi rimase fino alla morte nel 1932: il poeta «folle»." },
    { fronte: "Influenza di Rimbaud su Campana", retro: "Il poeta «veggente», il sregolamento dei sensi, la visione come metodo conoscitivo." },
    { fronte: "Lo stile dei Canti orfici", retro: "Alternanza di prosa poetica e versi; potenza visionaria; sintassi franta e musicale." },
    { fronte: "Cos'è la «visione» in Campana", retro: "L'esperienza mistico-sensoriale in cui la realtà diventa simbolo e mito; il fondamento dell'orfismo." },
    { fronte: "Perché Campana è un «outsider»", retro: "Inclassificabile, ai margini della cultura ufficiale, instabile e incompreso: vita e opera leggendarie." },
    { fronte: "Il paesaggio in Campana", retro: "L'Appennino, le città notturne, i porti: luoghi reali trasfigurati in scenari onirici e simbolici." },
    { fronte: "Differenza Campana vs Ungaretti", retro: "Entrambi vicini all'orfismo/simbolismo; Ungaretti riduce all'essenziale, Campana espande nella visione musicale." }
  ],

  pavese: [
    { fronte: "Anni di nascita e morte di Pavese", retro: "1908 – 1950, Santo Stefano Belbo (Cuneo). Morì suicida." },
    { fronte: "Cos'è il «mito» in Pavese?", retro: "I luoghi dell'infanzia (le Langhe) come archetipi eterni e sacri: il mito non è nostalgia ma categoria conoscitiva (Vico, Jung)." },
    { fronte: "Cos'è il tema del «ritorno»?", retro: "Si torna ai luoghi dell'origine ma non si trova ciò che si cerca: il passato è irrecuperabile." },
    { fronte: "Cos'è la «solitudine» pavesiana?", retro: "La condizione dei personaggi: incapacità di amare e comunicare; l'amore è sempre fallimento." },
    { fronte: "Cos'è il «verso-frase»?", retro: "Il verso lungo, narrativo e prosastico di Lavorare stanca: l'opposto dell'essenzialità ermetica." },
    { fronte: "Prima raccolta poetica di Pavese", retro: "Lavorare stanca (1936): poemetti narrativi, temi rurali e urbani, solitudine; il verso-frase." },
    { fronte: "Il capolavoro-testamento di Pavese", retro: "La luna e i falò (1950): Anguilla torna nelle Langhe e trova solo morte; il mito infranto." },
    { fronte: "Chi è Anguilla?", retro: "Il protagonista de La luna e i falò: trovatello cresciuto nelle Langhe, emigrato in America, che torna in cerca delle radici." },
    { fronte: "Cosa simboleggiano «la luna e i falò»?", retro: "La luna: il ciclo cosmico eterno, il mito. I falò: il rito contadino, l'identità del luogo, ora perduta." },
    { fronte: "Tema di La casa in collina", retro: "La guerra partigiana vista da Corrado, intellettuale che non sa schierarsi: «ogni guerra è una guerra civile»." },
    { fronte: "Cos'è Il mestiere di vivere?", retro: "Il diario intimo (1935–1950, postumo): l'analisi lucida della propria incapacità di essere felice." },
    { fronte: "Tema di Verrà la morte e avrà i tuoi occhi", retro: "La fusione di amore e morte; «un vizio assurdo»; scritta pochi mesi prima del suicidio: quasi una profezia." },
    { fronte: "Pavese traduttore", retro: "Con Vittorini, principale traduttore della letteratura americana (Melville, Whitman, Dos Passos)." },
    { fronte: "Cosa sono i Dialoghi con Leucò?", retro: "Reinterpretazioni dei miti greci in forma di dialogo (1947): la teoria pavesiana del mito." },
    { fronte: "Pavese e la casa editrice Einaudi", retro: "Fu una figura centrale di Einaudi nel dopoguerra; vinse il Premio Strega nel 1950." },
    { fronte: "Pavese e il confino", retro: "Confinato a Brancaleone Calabro (1935) per antifascismo; al ritorno iniziò il diario." },
    { fronte: "A quale corrente appartiene Pavese?", retro: "Al Neorealismo, ma lo supera: aggiunge alla realtà il mito (dentro e oltre)." },
    { fronte: "Differenza Pavese vs Verga", retro: "La terra d'origine come mito (Pavese) o come realtà sociologica immutabile (Verga)." },
    { fronte: "Differenza Pavese vs Calvino", retro: "Amici all'Einaudi; il mito di Pavese è tragico, quello di Calvino è giocoso." },
    { fronte: "Cosa rivela l'incipit de La luna e i falò?", retro: "Anguilla è un trovatello senza radici biologiche; «si torna per vedere com'è, si vuol toccare»." }
  ],

  pasolini: [
    { fronte: "Anni di nascita e morte di Pasolini", retro: "1922 – 1975. Nato a Bologna, assassinato a Ostia." },
    { fronte: "Cos'è l'«omologazione culturale»?", retro: "L'annullamento delle differenze culturali e di classe operato dal consumismo: il «nuovo fascismo», più totalitario di quello storico." },
    { fronte: "Cosa rappresenta il sottoproletariato?", retro: "Una vitalità corporea e culturale autentica, pre-borghese, che il capitalismo sta distruggendo." },
    { fronte: "Cos'è la «mutazione antropologica»?", retro: "Il cambiamento profondo dell'essere umano prodotto dal consumismo: i giovani autentici diventano piccolo-borghesi senza identità." },
    { fronte: "Perché Pasolini è «corsaro» e «luterano»?", retro: "Perché è eretico verso ogni potere (sinistra, destra, borghesia, Chiesa): sempre «contro», profeta scomodo." },
    { fronte: "Prime poesie di Pasolini", retro: "Poesie a Casarsa (1942), in dialetto friulano: la lingua della madre, affettiva e pre-ideologica." },
    { fronte: "Il poemetto chiave di Pasolini", retro: "Le ceneri di Gramsci (1957): il conflitto tra ragione marxista e attrazione per il sottoproletariato." },
    { fronte: "Tema de Le ceneri di Gramsci", retro: "«Con te e contro di te»: ammirazione per Gramsci (la ragione) e amore per ciò che Gramsci vorrebbe redimere (il corpo)." },
    { fronte: "Romanzo delle borgate (1955)", retro: "Ragazzi di vita: le borgate romane viste dall'interno, il dialetto romanesco fatto lingua letteraria." },
    { fronte: "Cosa sono gli Scritti corsari (1975)?", retro: "Articoli con la critica all'omologazione, alla TV, al «nuovo fascismo» dei consumi: il testamento ideologico." },
    { fronte: "Tema dell'articolo delle lucciole", retro: "La scomparsa delle lucciole come metafora della fine di un mondo autentico, ucciso dal consumismo." },
    { fronte: "Il dialetto in Pasolini", retro: "Resistenza culturale: friulano (lingua della madre) e romanesco (voce delle borgate), non folklore." },
    { fronte: "Cos'è il «cinema di poesia»?", retro: "La teoria del cinema come «lingua scritta della realtà»: la continuazione della poetica con altri mezzi." },
    { fronte: "Film d'esordio di Pasolini", retro: "Accattone (1961), sulle borgate romane. Poi Mamma Roma, Il Vangelo secondo Matteo, Salò." },
    { fronte: "L'ultimo film di Pasolini", retro: "Salò o le 120 giornate di Sodoma (1975): l'allegoria estrema del potere come distruzione dei corpi." },
    { fronte: "A quale corrente parte da Pasolini?", retro: "Dal Neorealismo (borgate, dialetto, popolo), che supera trasfigurando il sottoproletariato in mito e sacro." },
    { fronte: "Differenza Pasolini vs Ungaretti", retro: "Poesia come azione politica e corpo (Pasolini) vs illuminazione interiore (Ungaretti)." },
    { fronte: "Differenza Pasolini vs D'Annunzio", retro: "Intellettuali totali e scandalosi entrambi, ma Pasolini contro il potere, D'Annunzio al servizio del potere." },
    { fronte: "Lo stile della poesia pasoliniana", retro: "Denso, fisico, sensoriale: la parola pesa e brucia, rende palpabile l'esperienza. L'opposto dell'Ermetismo." },
    { fronte: "Cos'è Petrolio?", retro: "Romanzo-poema enciclopedico incompiuto (postumo 1992): il potere, l'economia, la politica italiana." }
  ],

  calvino: [
    { fronte: "Anni di nascita e morte di Calvino", retro: "1923 – 1985. Nato a Cuba, morto a Siena." },
    { fronte: "Cos'è la «leggerezza»?", retro: "La capacità di sollevarsi dal peso della realtà senza negarla. Emblema: Perseo che guarda Medusa riflessa nello scudo." },
    { fronte: "Cos'è il «combinatorio»?", retro: "La concezione (Oulipo) della letteratura come gioco basato su vincoli formali: la struttura genera il senso." },
    { fronte: "Cos'è l'Oulipo?", retro: "Il gruppo francese (Queneau, Perec) della «letteratura potenziale» basata su regole e vincoli, frequentato da Calvino a Parigi." },
    { fronte: "Romanzo d'esordio di Calvino", retro: "Il sentiero dei nidi di ragno (1947): la Resistenza vista con gli occhi del bambino Pin; neorealismo già superato." },
    { fronte: "Cos'è la trilogia I nostri antenati?", retro: "Il visconte dimezzato (1952), Il barone rampante (1957), Il cavaliere inesistente (1959): allegorie filosofiche in forma di favola." },
    { fronte: "Cosa rappresenta Il visconte dimezzato?", retro: "L'identità divisa tra bene e male; la frammentazione dell'uomo moderno e l'aspirazione all'integrità." },
    { fronte: "Cosa rappresenta Il barone rampante?", retro: "Cosimo vive sugli alberi: la libertà come distanza scelta dal mondo, non come fuga." },
    { fronte: "Cosa rappresenta Il cavaliere inesistente?", retro: "Agilulfo, armatura vuota animata dalla volontà: l'esistenza ridotta a pura funzione." },
    { fronte: "Cosa sono Le cosmicomiche (1965)?", retro: "Racconti narrati da Qfwfq, essere antichissimo: scienza e mito fusi in un'ironia cosmica." },
    { fronte: "Cos'è Le città invisibili (1972)?", retro: "Marco Polo descrive a Kublai Khan 55 città immaginarie in 11 categorie: meditazione su memoria, desiderio, tempo." },
    { fronte: "Cosa rivela la città di Diomira?", retro: "Il «carattere» non sono le meraviglie ma un sentimento: l'invidia per chi ha già vissuto una sera come quella." },
    { fronte: "Cos'è Se una notte d'inverno un viaggiatore (1979)?", retro: "Romanzo postmoderno in cui il Lettore è protagonista: dieci incipit di romanzi mai finiti. Riflessione su lettura e scrittura." },
    { fronte: "Cosa sono le Lezioni americane?", retro: "Sei conferenze per Harvard (postume 1988) sui valori della letteratura: leggerezza, rapidità, esattezza, visibilità, molteplicità, coerenza." },
    { fronte: "Le fasi di Calvino", retro: "Neorealismo, fiaba filosofica, fantascienza ironica, postmoderno: una continua reinvenzione del raccontare." },
    { fronte: "Calvino e la Resistenza", retro: "Partigiano nelle Brigate Garibaldi; l'esperienza è la materia del primo romanzo." },
    { fronte: "Calvino ed Einaudi", retro: "Lavorò per la casa editrice Einaudi per gran parte della vita, come consulente e redattore." },
    { fronte: "A quale corrente parte Calvino?", retro: "Dal Neorealismo (Resistenza), che supera con lo sguardo straniato del bambino e la struttura fiabesca." },
    { fronte: "Differenza Calvino vs Pirandello", retro: "Interrogano entrambi identità e realtà; Calvino con leggerezza giocosa, Pirandello con angoscia." },
    { fronte: "Differenza Calvino vs Pavese", retro: "Entrambi lavorano col mito; quello di Calvino è giocoso, quello di Pavese è tragico." }
  ]

};
