/* =========================================================================
   quiz-data.js — Tech & Digital English Quiz Data
   Format: window.QUIZ_DATA[key] = array of question objects
   { q, opts:[a,b,c,d], ans:0-3, expl }
   ========================================================================= */

window.QUIZ_DATA = {};

/* ══ HARDWARE ══ */
window.QUIZ_DATA.hardware = [
  { q:"What does CPU stand for?", opts:["Central Processing Unit","Computer Processing Utility","Core Programming Unit","Central Program Uploader"], ans:0, expl:"CPU — Central Processing Unit — is the primary component that executes instructions in a computer." },
  { q:"What is RAM?", opts:["A type of permanent storage","Random Access Memory — volatile, fast temporary storage","Read-only Archival Memory","A type of CPU cache"], ans:1, expl:"RAM (Random Access Memory) stores data temporarily while the computer is running. It is volatile — lost when power is removed." },
  { q:"What does 'volatile' mean in the context of computer memory?", opts:["The memory is very fast","Data is lost when the power is turned off","The memory can be written to many times","The memory is permanent"], ans:1, expl:"Volatile memory loses its content when power is removed. RAM is volatile; ROM and SSDs are non-volatile." },
  { q:"What is Moore's Law?", opts:["Internet speeds double every 2 years","The number of transistors on a chip doubles approximately every 2 years","Computer prices halve every year","Software complexity doubles every 18 months"], ans:1, expl:"Gordon Moore (Intel co-founder) observed in 1965 that transistor density doubled roughly every 2 years, driving exponential performance growth." },
  { q:"What is a bus in computer architecture?", opts:["Software that manages hardware drivers","A communication pathway connecting computer components","A type of CPU register","A high-speed cache memory"], ans:1, expl:"A bus is a communication channel that transfers data between the CPU, RAM, and other components." },
  { q:"What does SSD stand for?", opts:["Super Speed Drive","Solid State Drive","Sequential Storage Device","System Storage Disk"], ans:1, expl:"SSD — Solid State Drive — uses flash memory for storage, with no moving parts, making it faster and more reliable than HDDs." },
  { q:"What is cache memory?", opts:["A type of internet browser storage","An ultra-fast memory layer close to the CPU","External backup storage","A type of RAM"], ans:1, expl:"Cache is a small, fast memory between the CPU and RAM that stores frequently accessed data to reduce access time." },
  { q:"What does the clock speed of a CPU measure?", opts:["The physical size of the processor","How many instructions per second the CPU can execute","The power consumption of the CPU","The temperature of the CPU"], ans:1, expl:"Clock speed (measured in GHz) indicates how many cycles per second the CPU can perform — higher = faster instruction execution." },
  { q:"What is the Von Neumann architecture?", opts:["A CPU design with multiple cores","A computer design where program instructions and data share the same memory","A distributed computing model","A type of parallel processing"], ans:1, expl:"Von Neumann architecture stores both program instructions and data in the same memory — the basis of most modern computers." },
  { q:"What is the difference between a 32-bit and 64-bit processor?", opts:["Speed only","The maximum amount of RAM the processor can address","The number of cores","The cache size"], ans:1, expl:"A 64-bit processor can address vastly more RAM (up to 16 exabytes theoretically) than 32-bit (max 4GB)." }
];

/* ══ OPERATING SYSTEMS ══ */
window.QUIZ_DATA.os = [
  { q:"What is the kernel of an operating system?", opts:["The user interface of the OS","The core of the OS that manages hardware resources","An application installed on top of the OS","The OS file system"], ans:1, expl:"The kernel is the core component of an OS — it manages CPU, memory, and I/O devices, mediating between hardware and software." },
  { q:"What is multitasking in an operating system?", opts:["Running multiple monitors","The ability to run multiple applications seemingly simultaneously","Having multiple user accounts","Processing multiple files at once"], ans:1, expl:"Multitasking allows an OS to manage multiple running processes — switching between them rapidly to give the illusion of simultaneous execution." },
  { q:"What is the difference between a process and a thread?", opts:["A process is faster than a thread","A thread is an independent program, a process is a sub-task","A process is a running program; a thread is the smallest unit of execution within it","There is no difference"], ans:2, expl:"A process is a running program with its own memory space. A thread is a smaller unit of execution within a process — threads share the same memory." },
  { q:"What does BIOS stand for?", opts:["Basic Input/Output System","Binary Internet Operating Software","Built-in Operating System","Basic Integrated Output System"], ans:0, expl:"BIOS (Basic Input/Output System) is firmware that initialises hardware during startup before the operating system loads." },
  { q:"What is a file system?", opts:["A collection of user files","The structure an OS uses to organise and manage data on storage devices","A type of database","The OS interface for browsing the internet"], ans:1, expl:"A file system (e.g., NTFS, FAT32, ext4) defines how data is stored, organised and retrieved on a storage device." },
  { q:"What is virtual memory?", opts:["Memory on a virtual machine","Disk space used to extend RAM when physical RAM is full","Cloud-based memory storage","Memory used by virtual reality applications"], ans:1, expl:"Virtual memory uses disk space as an extension of RAM, allowing programs to use more memory than is physically available — at the cost of speed." },
  { q:"Which of these is an open-source operating system?", opts:["Windows 11","macOS","Linux","iOS"], ans:2, expl:"Linux is open-source — its source code is publicly available and freely distributable. Windows and macOS are proprietary." },
  { q:"What is a device driver?", opts:["Software that backs up data","Software that allows the OS to communicate with hardware devices","A user who manages the OS","A type of network protocol"], ans:1, expl:"A device driver is software that allows the OS to communicate with and control hardware devices (printers, graphics cards, etc.)." },
  { q:"What is deadlock in an operating system?", opts:["A computer that won't turn on","A situation where two or more processes are each waiting for the other to release resources","An unresponsive application","A type of malware"], ans:1, expl:"Deadlock occurs when processes are each waiting for resources held by the others — all are blocked and none can proceed." },
  { q:"What does GUI stand for?", opts:["General User Interface","Graphical User Interface","Global Utility Integration","General Unix Interface"], ans:1, expl:"GUI — Graphical User Interface — allows users to interact with software through visual elements (windows, icons, menus) rather than text commands." }
];

/* ══ NETWORKS ══ */
window.QUIZ_DATA.networks = [
  { q:"What does LAN stand for?", opts:["Long Access Network","Local Area Network","Large Application Network","Linked Analogue Network"], ans:1, expl:"LAN — Local Area Network — connects devices within a limited area such as a home, school, or office building." },
  { q:"What is the OSI model?", opts:["A type of network hardware","A 7-layer conceptual framework for understanding network communication","A wireless networking standard","An internet protocol"], ans:1, expl:"The OSI (Open Systems Interconnection) model has 7 layers (Physical, Data Link, Network, Transport, Session, Presentation, Application) describing network communication." },
  { q:"What does a router do?", opts:["Connects devices within the same network","Forwards data packets between different networks","Amplifies wireless signal","Converts analogue to digital signals"], ans:1, expl:"A router forwards packets between different networks — directing traffic on the internet. A switch connects devices within the same network." },
  { q:"What is an IP address?", opts:["The hardware address of a network card","A numerical label identifying a device on a network","A domain name for a website","A type of network protocol"], ans:1, expl:"An IP address (e.g., 192.168.1.1) uniquely identifies a device on a network, allowing data to be routed to the correct destination." },
  { q:"What is the difference between TCP and UDP?", opts:["TCP is faster; UDP is more reliable","TCP guarantees delivery and order; UDP is faster but unreliable","They are identical protocols","TCP is wireless; UDP is wired"], ans:1, expl:"TCP (Transmission Control Protocol) ensures reliable, ordered delivery with error-checking. UDP (User Datagram Protocol) is faster but does not guarantee delivery — used for streaming, gaming." },
  { q:"What does DNS stand for?", opts:["Digital Network System","Domain Name System — translates domain names to IP addresses","Data Navigation Service","Dynamic Network Settings"], ans:1, expl:"DNS (Domain Name System) translates human-readable domain names (google.com) into IP addresses (142.250.185.78)." },
  { q:"What is bandwidth?", opts:["The length of a network cable","The maximum rate of data transfer across a network","The number of connected devices","The latency of a network"], ans:1, expl:"Bandwidth is the maximum rate at which data can be transferred over a network connection — measured in bits per second (Mbps, Gbps)." },
  { q:"What is a MAC address?", opts:["A type of Apple computer address","A permanent hardware address assigned to a network interface card","A type of IP address","A wireless network protocol"], ans:1, expl:"A MAC (Media Access Control) address is a unique hardware identifier for each network interface — used at the Data Link layer." },
  { q:"What is VPN?", opts:["Very Private Network","Virtual Private Network — creates an encrypted connection over a public network","Video Protocol Network","Verified Public Node"], ans:1, expl:"A VPN (Virtual Private Network) creates an encrypted tunnel over a public network, providing privacy and security." },
  { q:"What is packet switching?", opts:["Physically switching network cables","Dividing data into packets sent independently across a network","A type of wireless switching","Switching between different networks"], ans:1, expl:"Packet switching breaks data into small packets transmitted independently across a network — they may take different routes and are reassembled at the destination." }
];

/* ══ CYBERSECURITY ══ */
window.QUIZ_DATA.cybersecurity = [
  { q:"What is malware?", opts:["Hardware that malfunctions","Malicious software designed to damage or gain unauthorised access to systems","A type of network configuration error","A programming language"], ans:1, expl:"Malware (malicious software) includes viruses, worms, trojans, ransomware and spyware — designed to harm systems or steal data." },
  { q:"What is phishing?", opts:["A technique to test network speed","A social engineering attack using fraudulent emails or websites to steal credentials","A type of encryption","A method of network scanning"], ans:1, expl:"Phishing uses fake emails or websites impersonating trusted organisations to trick users into revealing passwords, credit card numbers or other sensitive data." },
  { q:"What does the CIA triad stand for in cybersecurity?", opts:["Computer Intelligence Agency","Confidentiality, Integrity, Availability","Centralised Internet Access","Control, Identify, Authenticate"], ans:1, expl:"The CIA triad is the foundation of information security: Confidentiality (only authorised access), Integrity (data unchanged), Availability (accessible when needed)." },
  { q:"What is ransomware?", opts:["Software that mines cryptocurrency","Malware that encrypts victim's data and demands payment for the decryption key","A type of firewall","Software that monitors network traffic"], ans:1, expl:"Ransomware encrypts a victim's files, making them inaccessible, then demands a ransom (usually cryptocurrency) for the decryption key." },
  { q:"What is two-factor authentication (2FA)?", opts:["Using two different passwords","A security process requiring two forms of verification (e.g., password + SMS code)","Logging in from two devices","A type of encryption"], ans:1, expl:"2FA adds a second layer of security beyond a password — typically something you know + something you have (phone) or something you are (fingerprint)." },
  { q:"What is a DDoS attack?", opts:["A type of data encryption","Distributed Denial of Service — overwhelming a server with traffic to make it unavailable","A method of stealing data","Direct Database Override System"], ans:1, expl:"A DDoS (Distributed Denial of Service) attack uses many compromised computers to flood a target server with requests, making it unavailable to legitimate users." },
  { q:"What is a firewall?", opts:["A physical barrier protecting servers","A network security device that monitors and filters incoming/outgoing traffic","A type of antivirus software","A fireproof server room"], ans:1, expl:"A firewall filters network traffic based on predefined rules, blocking unauthorised access while allowing legitimate communication." },
  { q:"What is social engineering in cybersecurity?", opts:["Using social media for marketing","Manipulating people into revealing confidential information or taking security-compromising actions","Engineering social networks","Building secure social platforms"], ans:1, expl:"Social engineering exploits human psychology rather than technical vulnerabilities — tricking people into giving access or revealing sensitive information." },
  { q:"What is the difference between a virus and a worm?", opts:["A virus is more dangerous than a worm","A virus attaches to files and requires user action to spread; a worm self-replicates across networks","A worm requires human action; a virus does not","They are identical types of malware"], ans:1, expl:"A virus needs a host file and user action (e.g., opening an infected file) to spread. A worm is self-replicating — it spreads automatically across networks." },
  { q:"What is encryption?", opts:["Deleting data permanently","Converting data into an unreadable format using a key, so only authorised parties can read it","Compressing files to save space","Backing up data to a secure location"], ans:1, expl:"Encryption transforms plaintext into ciphertext using an algorithm and key — only someone with the correct key can decrypt and read the data." }
];

/* ══ AI & MACHINE LEARNING ══ */
window.QUIZ_DATA.ai = [
  { q:"Who proposed the Turing Test?", opts:["Alan Turing in 1950","John McCarthy in 1956","Ada Lovelace in 1843","Tim Berners-Lee in 1989"], ans:0, expl:"Alan Turing proposed the 'Imitation Game' (Turing Test) in 1950 — a test of a machine's ability to exhibit intelligent behaviour indistinguishable from a human." },
  { q:"What is machine learning?", opts:["Programming computers with all possible rules","A subset of AI where systems learn from data without being explicitly programmed","Teaching children to use computers","Programming machines to follow instructions"], ans:1, expl:"Machine learning uses algorithms to identify patterns in data, allowing systems to improve performance on tasks without being explicitly programmed for each scenario." },
  { q:"What is a neural network?", opts:["A computer network connecting multiple computers","A computational model inspired by the human brain, consisting of interconnected nodes (neurons)","A type of database","A network for AI researchers"], ans:1, expl:"Artificial neural networks consist of layers of interconnected nodes that process data — used in image recognition, NLP and many other AI applications." },
  { q:"What is supervised learning?", opts:["Learning with a human teacher present","Training a model on labelled data where the correct output is known","AI that monitors itself","Learning through trial and error without feedback"], ans:1, expl:"In supervised learning, the model is trained on a dataset where each input has a known correct output (label) — the model learns to map inputs to outputs." },
  { q:"What does NLP stand for in AI?", opts:["Numeric Logic Programming","Natural Language Processing — AI that understands and generates human language","Network Level Protocol","Non-Linear Programming"], ans:1, expl:"NLP (Natural Language Processing) enables computers to understand, interpret and generate human language — used in chatbots, translation and sentiment analysis." },
  { q:"What is algorithm bias in AI?", opts:["An AI that prefers certain programming languages","Systematic errors in AI output caused by biased training data","An algorithm that is too slow","A preference for certain users"], ans:1, expl:"Algorithm bias occurs when an AI system produces systematically unfair results because it was trained on biased data — reflecting and amplifying existing societal inequalities." },
  { q:"What is deep learning?", opts:["Learning about complex subjects","A subset of ML using deep neural networks with many layers to learn complex patterns","AI that digs deep into databases","Learning that takes a long time"], ans:1, expl:"Deep learning uses neural networks with many hidden layers, enabling AI to learn complex representations from large datasets — behind image recognition, speech recognition and LLMs." },
  { q:"What is the difference between AI and ML?", opts:["They are identical terms","AI is the broad field of intelligent machines; ML is a technique within AI where systems learn from data","ML is more advanced than AI","AI is older than ML"], ans:1, expl:"AI is the broad concept of machines simulating human intelligence. ML is a specific approach within AI — training systems to learn from data rather than programming all rules explicitly." },
  { q:"What are the main ethical concerns about AI?", opts:["AI is too slow","Bias, lack of transparency (black box), job displacement, privacy, autonomous weapons","AI uses too much electricity","AI is not creative enough"], ans:1, expl:"Key AI ethics concerns: algorithmic bias, explainability (black box decisions), automation displacing workers, privacy through data collection, and autonomous weapons systems." },
  { q:"What is a large language model (LLM)?", opts:["A very long programming manual","An AI system trained on vast amounts of text to generate and understand human language","A database of languages","A translation tool"], ans:1, expl:"LLMs (like GPT, Claude) are AI models trained on huge text datasets, capable of generating coherent text, answering questions, writing code and more." }
];

/* ══ CLOUD COMPUTING ══ */
window.QUIZ_DATA.cloud = [
  { q:"What is cloud computing?", opts:["Computing on very fast computers","Delivering IT resources (servers, storage, software) over the internet on demand","Computing using weather data","A type of network topology"], ans:1, expl:"Cloud computing provides IT resources over the internet — users access computing power, storage and applications without managing physical infrastructure." },
  { q:"What is SaaS?", opts:["Storage as a Service","Software as a Service — applications delivered over the internet","Server as a System","Security as a Solution"], ans:1, expl:"SaaS (Software as a Service) delivers applications over the internet — examples include Gmail, Office 365, Salesforce. No local installation needed." },
  { q:"What is the difference between IaaS and PaaS?", opts:["There is no difference","IaaS provides virtual infrastructure (VMs, storage); PaaS provides a development platform on top of that infrastructure","IaaS is for individuals; PaaS is for companies","PaaS is older than IaaS"], ans:1, expl:"IaaS (Infrastructure as a Service) provides virtual hardware. PaaS (Platform as a Service) adds a development environment on top — developers build apps without managing infrastructure." },
  { q:"What is virtualisation?", opts:["Creating visual graphics","Running multiple operating systems or applications on a single physical machine using software","A type of cloud storage","A programming paradigm"], ans:1, expl:"Virtualisation uses software (hypervisors) to create multiple virtual machines on one physical server, maximising hardware utilisation." },
  { q:"What is scalability in cloud computing?", opts:["The size of the data centre","The ability to increase or decrease resources on demand to match workload","The speed of internet connection","The security of cloud services"], ans:1, expl:"Scalability means cloud resources can grow (scale up/out) when demand increases and shrink when demand decreases — you pay for what you use." },
  { q:"What is a container in computing?", opts:["A physical box for storing hardware","A lightweight, portable unit of software that packages code and dependencies","A type of cloud storage bucket","A database table"], ans:1, expl:"Containers (e.g., Docker) package an application with all its dependencies into a portable unit that runs consistently across different environments." },
  { q:"What is a public cloud?", opts:["A cloud owned by a government","Cloud services provided by third-party providers over the internet, shared among multiple customers","A cloud accessible to anyone with a computer","A type of open-source cloud"], ans:1, expl:"Public cloud (AWS, Azure, Google Cloud) provides shared infrastructure to multiple customers over the internet — cost-effective but less control than private cloud." },
  { q:"What is serverless computing?", opts:["Computing without any servers","A cloud model where the provider automatically manages server infrastructure — developers focus only on code","A type of edge computing","Computing using client machines only"], ans:1, expl:"Serverless (e.g., AWS Lambda, Azure Functions) lets developers run code without provisioning servers — the cloud provider manages all infrastructure automatically." }
];

/* ══ INTERNET & WEB ══ */
window.QUIZ_DATA.internet = [
  { q:"Who invented the World Wide Web?", opts:["Bill Gates","Steve Jobs","Tim Berners-Lee","Vint Cerf"], ans:2, expl:"Tim Berners-Lee invented the World Wide Web in 1989 at CERN, proposing a system of linked hypertext documents accessible over the internet." },
  { q:"What is the difference between the internet and the World Wide Web?", opts:["They are the same thing","The internet is the global network infrastructure; the WWW is one service that runs on it","The web is older than the internet","The internet is only used for web browsing"], ans:1, expl:"The internet is the global network of interconnected computers. The WWW is a service built on the internet — a system of linked web pages accessed via browsers." },
  { q:"What does HTTP stand for?", opts:["Hyper Text Transfer Protocol","High Tech Transmission Program","Hosted Text Transfer Process","HyperText Tracking Protocol"], ans:0, expl:"HTTP (HyperText Transfer Protocol) is the protocol used to transfer web pages over the internet. HTTPS adds TLS encryption for security." },
  { q:"What is a URL?", opts:["A type of programming language","A Uniform Resource Locator — the address of a resource on the web","A User Registration Link","An Underline Request Language"], ans:1, expl:"A URL (Uniform Resource Locator) is the complete address of a web resource, e.g., https://www.example.com/page." },
  { q:"What is HTML?", opts:["A programming language","HyperText Markup Language — the standard language for creating web pages","A type of database","A network protocol"], ans:1, expl:"HTML (HyperText Markup Language) is the standard markup language for creating web pages — it defines the structure and content of web documents." },
  { q:"What is a cookie in web technology?", opts:["An error in a web page","A small text file stored on the user's device by a website to remember information","A type of malware","A web development framework"], ans:1, expl:"Cookies are small text files stored by websites on your device — used for session management, personalisation and tracking." },
  { q:"What is responsive web design?", opts:["A web design that responds to user comments","Design that adapts to different screen sizes and devices","A website that loads very quickly","Interactive web design with animations"], ans:1, expl:"Responsive web design uses CSS media queries to ensure websites look and function well across different screen sizes (desktop, tablet, mobile)." }
];

/* ══ PRIVACY & GDPR ══ */
window.QUIZ_DATA.privacy = [
  { q:"What does GDPR stand for?", opts:["General Data Privacy Regulation","General Data Protection Regulation — EU privacy law since 2018","Government Data Processing Rules","Global Digital Privacy Rights"], ans:1, expl:"GDPR (General Data Protection Regulation) is an EU regulation (effective May 2018) governing how personal data is collected, processed and stored." },
  { q:"What is 'consent' under GDPR?", opts:["Automatic agreement to terms","Freely given, specific, informed and unambiguous agreement to data processing","A legal contract","Payment for data services"], ans:1, expl:"GDPR requires that consent to process personal data must be freely given, specific, informed, and unambiguous — pre-ticked boxes are not valid consent." },
  { q:"What is the 'right to erasure' under GDPR?", opts:["The right to delete photos from social media","The right of individuals to request the deletion of their personal data from organisations","The right to refuse data collection","The right to clear browser history"], ans:1, expl:"Also called the 'right to be forgotten', GDPR Article 17 gives individuals the right to request deletion of their personal data under certain conditions." },
  { q:"What is a data breach under GDPR?", opts:["An error in a database","A security incident leading to accidental or unlawful access, disclosure or destruction of personal data","A type of cyberattack","A privacy policy update"], ans:1, expl:"A data breach is any security incident that compromises personal data. Under GDPR, organisations must notify the supervisory authority within 72 hours." },
  { q:"What is net neutrality?", opts:["An international treaty about the internet","The principle that internet service providers must treat all internet traffic equally","A type of network configuration","A cybersecurity policy"], ans:1, expl:"Net neutrality requires ISPs to treat all internet traffic the same — not blocking, throttling or giving paid priority to specific content or websites." }
];

/* ══ EMPLOYMENT ══ */
window.QUIZ_DATA.employment = [
  { q:"What is a CV (Curriculum Vitae)?", opts:["A type of computer program","A document summarising a person's education, skills and work experience for job applications","A professional certificate","A type of employment contract"], ans:1, expl:"A CV (Curriculum Vitae) is a document used when applying for jobs, summarising education, skills, experience and achievements." },
  { q:"What are 'soft skills' in a professional context?", opts:["Skills related to using software","Interpersonal skills: communication, teamwork, problem-solving, time management","Skills that are easy to learn","Technical skills in IT"], ans:1, expl:"Soft skills are non-technical interpersonal abilities — communication, collaboration, adaptability, critical thinking — highly valued alongside technical expertise." },
  { q:"What does 'full-stack developer' mean?", opts:["A developer who works very long hours","A developer competent in both front-end (user interface) and back-end (server, database) development","A developer who uses all programming languages","A team of developers"], ans:1, expl:"A full-stack developer has skills across the entire web development stack — front-end (HTML, CSS, JavaScript) and back-end (server, databases, APIs)." },
  { q:"What is Agile methodology in software development?", opts:["A fast internet connection","An iterative development approach with short cycles (sprints), collaboration and adaptability","A type of project management software","A programming language"], ans:1, expl:"Agile is an iterative approach to software development emphasising flexibility, collaboration, and delivering working software in short cycles (sprints) rather than one big delivery." },
  { q:"What is a cover letter?", opts:["The cover page of a report","A letter accompanying a CV, explaining why you are applying and what you offer","A type of employment contract","A recommendation letter from a previous employer"], ans:1, expl:"A cover letter (or covering letter) introduces your job application, highlighting relevant experience and explaining why you are interested in and suited for the specific role." }
];

/* ══ BLOCKCHAIN & EMERGING ══ */
window.QUIZ_DATA.emerging = [
  { q:"What is blockchain technology?", opts:["A type of internet connection","A distributed, immutable ledger of transactions shared across a peer-to-peer network","A cloud storage system","A type of database management system"], ans:1, expl:"Blockchain is a distributed ledger where transactions are grouped in blocks, cryptographically linked, and stored across many nodes — making it extremely difficult to tamper with." },
  { q:"What is cryptocurrency?", opts:["An encrypted password","A digital currency that uses cryptography to secure transactions and operates on a blockchain","A type of online banking","A government-issued digital currency"], ans:1, expl:"Cryptocurrency (e.g., Bitcoin, Ethereum) is a decentralised digital currency using cryptographic techniques to secure transactions and control the creation of new units." },
  { q:"What is the difference between VR and AR?", opts:["VR is cheaper than AR","VR immerses the user in a fully digital environment; AR overlays digital content onto the real world","AR is fully immersive; VR adds digital elements to reality","They are the same technology"], ans:1, expl:"VR (Virtual Reality) replaces the real world with a fully digital environment. AR (Augmented Reality) adds digital elements to the real world view." },
  { q:"What is quantum computing?", opts:["Very fast traditional computing","Computing that uses quantum mechanical phenomena (superposition, entanglement) to perform calculations","Computing using quantum encryption","A type of AI"], ans:1, expl:"Quantum computers use qubits that can be in superposition (0 and 1 simultaneously), enabling them to solve certain problems exponentially faster than classical computers." },
  { q:"What is a smart contract?", opts:["A legally binding digital document","Self-executing code stored on a blockchain that automatically enforces contract terms","A type of AI chatbot","A secure email system"], ans:1, expl:"A smart contract is code stored on a blockchain that executes automatically when predefined conditions are met — no intermediary (bank, lawyer) needed." }
];

/* ══ IOT ══ */
window.QUIZ_DATA.iot = [
  { q:"What does IoT stand for?", opts:["Internet of Technology","Internet of Things — the network of connected physical devices","Integrated Online Technology","Internet of Trade"], ans:1, expl:"IoT (Internet of Things) refers to the network of physical devices embedded with sensors, software and connectivity to exchange data over the internet." },
  { q:"What is a sensor in an IoT context?", opts:["A type of camera","A device that detects and measures physical phenomena (temperature, motion, humidity)","A network router for IoT devices","A programming interface"], ans:1, expl:"IoT sensors detect and measure physical parameters (temperature, pressure, light, motion) and convert them to digital data for processing." },
  { q:"What is a major security concern with IoT devices?", opts:["They use too much electricity","Many IoT devices have weak security, creating vulnerabilities in networks","They are too expensive","They produce too much data"], ans:1, expl:"IoT devices often have minimal processing power, making it hard to implement strong security. Weak default passwords and unencrypted data make them easy targets for cyberattacks." },
  { q:"What is 'Industry 4.0'?", opts:["The fourth generation of the internet","The fourth industrial revolution: automation, IoT, AI and data exchange in manufacturing","A generation of computer processors","A type of cloud service"], ans:1, expl:"Industry 4.0 refers to the current phase of industrial revolution combining IoT, AI, robotics, and big data in manufacturing and production — also called 'smart factory'." }
];
