/* =========================================================================
   flashcard-data.js — Flashcard Informatica · 6 moduli · 15 carte ciascuno
   ========================================================================= */

window.flashcardData = {

  /* ──────────────────────────────────────────────────────────
     MODULO 1 — Basi di Dati e Algebra Relazionale
  ────────────────────────────────────────────────────────── */
  "basi-di-dati": [
    { fronte: "Cos'è un DBMS?",
      retro: "Database Management System: sistema software per creare, organizzare e interrogare basi di dati. Funzioni principali: definizione dati, manipolazione, controllo accessi, garanzia integrità, gestione transazioni." },
    { fronte: "Differenza tra sistema informatico e sistema informativo",
      retro: "Sistema informativo: insieme di risorse (umane, tecnologiche, organizzative) per gestire informazioni. Sistema informatico: la componente tecnologica (HW + SW) del sistema informativo." },
    { fronte: "Architettura ANSI/SPARC — i tre livelli",
      retro: "1. Livello esterno (viste utente). 2. Livello logico/concettuale (schema globale). 3. Livello fisico/interno (memorizzazione effettiva su disco)." },
    { fronte: "Cos'è una superchiave?",
      retro: "Insieme di uno o più attributi che identifica univocamente ogni tupla di una relazione. Ogni chiave primaria è superchiave, ma non viceversa." },
    { fronte: "Differenza tra chiave candidata e chiave primaria",
      retro: "Chiave candidata: superchiave minimale (non contiene attributi in eccesso). Chiave primaria: la chiave candidata scelta come identificatore principale — non può essere NULL." },
    { fronte: "Cos'è una chiave esterna (foreign key)?",
      retro: "Attributo (o insieme di attributi) che referenzia la chiave primaria di un'altra relazione, garantendo l'integrità referenziale tra tabelle." },
    { fronte: "Vincolo di integrità referenziale",
      retro: "I valori di una chiave esterna devono essere presenti come chiave primaria nella tabella referenziata, oppure essere NULL (se ammesso)." },
    { fronte: "Cosa rappresenta NULL in un database?",
      retro: "Valore speciale che indica assenza di informazione o valore sconosciuto. NON è zero, né stringa vuota. Trattato in modo speciale nelle query (IS NULL / IS NOT NULL)." },
    { fronte: "Grado e cardinalità di una relazione",
      retro: "Grado = numero di attributi (colonne). Cardinalità = numero di tuple (righe). Lo schema è fisso, l'istanza (cardinalità) cambia nel tempo." },
    { fronte: "Differenza tra selezione e proiezione (algebra relazionale)",
      retro: "Selezione (σ): filtra le righe secondo una condizione — riduzione orizzontale. Proiezione (π): seleziona le colonne — riduzione verticale." },
    { fronte: "Operatori insiemistici dell'algebra relazionale",
      retro: "Unione (∪), Intersezione (∩), Differenza (−), Prodotto cartesiano (×). Le relazioni devono essere compatibili (stesso schema) per ∪, ∩, −." },
    { fronte: "Cos'è il join naturale?",
      retro: "Combina due relazioni sugli attributi con lo stesso nome e stesso dominio, eliminando le copie duplicate degli attributi di giunzione." },
    { fronte: "Vincolo di dominio",
      retro: "Specifica i valori ammissibili per un attributo: tipo di dato (INT, VARCHAR…), range, CHECK constraint. Prima linea di difesa dell'integrità dei dati." },
    { fronte: "Regola CASCADE nelle foreign key",
      retro: "Quando si elimina/modifica un record padre, le modifiche si propagano automaticamente ai record figli. Alternativa: RESTRICT (blocca), SET NULL, SET DEFAULT." },
    { fronte: "Schema vs istanza di una relazione",
      retro: "Schema: struttura fissa — nome della relazione + lista attributi + domini. È invariante nel tempo. Istanza: il contenuto attuale (insieme di tuple). Cambia con INSERT, UPDATE, DELETE." }
  ],

  /* ──────────────────────────────────────────────────────────
     MODULO 2 — PHP lato server
  ────────────────────────────────────────────────────────── */
  "php": [
    { fronte: "Differenza GET e POST in PHP",
      retro: "GET: dati nell'URL, visibili, max ~2 KB, idempotente — per lettura. POST: dati nel body HTTP, invisibili nell'URL — per invio/modifica di dati sensibili o grandi." },
    { fronte: "Cos'è una sessione PHP?",
      retro: "Meccanismo per mantenere dati tra richieste HTTP successive. I dati sono sul server, identificati da un session_id inviato al client tramite cookie. Si avvia con session_start()." },
    { fronte: "Differenza tra cookie e sessione",
      retro: "Cookie: dati memorizzati sul client, possono essere persistenti, max ~4 KB. Sessione: dati sul server, temporanei (scadono alla chiusura del browser o per timeout)." },
    { fronte: "Variabili superglobali PHP — principali",
      retro: "$_GET, $_POST, $_SESSION, $_COOKIE, $_FILES, $_SERVER, $GLOBALS, $_REQUEST, $_ENV. Accessibili in qualsiasi scope senza dichiarare global." },
    { fronte: "password_hash() e password_verify()",
      retro: "password_hash($pwd, PASSWORD_BCRYPT): genera hash sicuro con salt automatico. password_verify($pwd, $hash): confronta una password con il suo hash in modo sicuro contro timing attack." },
    { fronte: "Array associativi in PHP",
      retro: "Array con chiavi stringa invece di indici numerici: $user = ['nome' => 'Mario', 'eta' => 20]. Si accede con $user['nome']. Si itera con foreach ($arr as $key => $value)." },
    { fronte: "Ciclo foreach in PHP",
      retro: "foreach ($array as $value) — itera sui valori. foreach ($array as $key => $value) — itera su chiave e valore. Ideale per array indicizzati e associativi." },
    { fronte: "include vs require in PHP",
      retro: "include: include il file, genera WARNING se non trovato (script continua). require: genera FATAL ERROR se non trovato (script si blocca). Le versioni _once evitano inclusioni duplicate." },
    { fronte: "Connessione a MySQL con MySQLi in PHP",
      retro: "mysqli_connect($host, $user, $pwd, $db) oppure new mysqli(). Poi mysqli_query() per le query, mysqli_fetch_assoc() per leggere i risultati, mysqli_close() per chiudere." },
    { fronte: "json_encode() e json_decode() in PHP",
      retro: "json_encode($array): converte array/oggetto PHP in stringa JSON. json_decode($str, true): converte JSON in array associativo PHP (false → oggetto stdClass)." },
    { fronte: "Scope delle variabili in PHP",
      retro: "Le variabili dentro le funzioni sono locali. Per usare una variabile globale dentro una funzione: dichiarare global $var oppure usare $GLOBALS['var']." },
    { fronte: "Gestione file in PHP",
      retro: "fopen(), fread()/fgets(), fwrite(), fclose() per accesso sequenziale. file_get_contents() e file_put_contents() per operazioni semplici su intero file." },
    { fronte: "Espressioni regolari in PHP",
      retro: "preg_match('/pattern/', $str): verifica corrispondenza. preg_replace(): sostituisce. preg_split(): divide stringa. Usa sintassi PCRE con delimitatori (es. /^\\d{3}$/)." },
    { fronte: "Operatore ternario in PHP",
      retro: "$result = ($condizione) ? $valoreSe : $valoreAltrimenti; Forma breve (Elvis): $a ?: $b — restituisce $a se truthy, altrimenti $b." },
    { fronte: "Funzione header() in PHP",
      retro: "Invia un header HTTP prima dell'output. Usi comuni: header('Location: pagina.php') per redirect, header('Content-Type: application/json') per risposte JSON." }
  ],

  /* ──────────────────────────────────────────────────────────
     MODULO 3 — JavaScript lato client
  ────────────────────────────────────────────────────────── */
  "javascript": [
    { fronte: "Cos'è il DOM?",
      retro: "Document Object Model: rappresentazione ad albero della pagina HTML manipolabile via JavaScript. Ogni elemento HTML è un nodo. Modificare il DOM cambia la pagina in tempo reale." },
    { fronte: "JSON.parse() vs JSON.stringify()",
      retro: "JSON.parse(str): converte stringa JSON → oggetto/array JavaScript. JSON.stringify(obj): converte oggetto/array JavaScript → stringa JSON. Usati per scambiare dati con il server." },
    { fronte: "Cos'è XMLHttpRequest?",
      retro: "Oggetto JavaScript per fare richieste HTTP asincrone al server senza ricaricare la pagina. Base tecnica di AJAX. Oggi spesso sostituito dalla Fetch API." },
    { fronte: "Differenza tra var, let e const",
      retro: "var: scope di funzione, hoisting. let: scope di blocco ({}), no hoisting — preferito per variabili che cambiano. const: scope di blocco, non riassegnabile — preferito per costanti." },
    { fronte: "Event bubbling in JavaScript",
      retro: "Quando un evento si verifica su un elemento, si propaga (bubble) verso i genitori nel DOM. Si ferma con event.stopPropagation(). Utile per la delegazione degli eventi." },
    { fronte: "Metodi di selezione DOM — principali",
      retro: "getElementById('id'): un elemento per ID. querySelector('selettore CSS'): primo elemento. querySelectorAll(): NodeList di tutti. getElementsByClassName(), getElementsByTagName()." },
    { fronte: "innerHTML vs textContent",
      retro: "innerHTML: imposta/legge HTML (interpreta tag, rischio XSS se contiene input utente). textContent: solo testo, più sicuro, non interpreta HTML." },
    { fronte: "addEventListener",
      retro: "elemento.addEventListener('evento', funzione, useCapture). Permette più handler per lo stesso evento. Preferito a onclick= perché non sovrascrive handler esistenti." },
    { fronte: "DOMContentLoaded vs window.onload",
      retro: "DOMContentLoaded: DOM completamente costruito (senza immagini/CSS). window.onload: tutto caricato incluse risorse esterne. Usare DOMContentLoaded per la maggior parte dei casi." },
    { fronte: "createElement e appendChild",
      retro: "createElement('tag') crea un nodo HTML. appendChild(nodo) lo aggiunge al DOM come ultimo figlio. removeChild(nodo) lo rimuove. insertBefore() per inserzioni precise." },
    { fronte: "Cos'è una closure?",
      retro: "Funzione che mantiene accesso alle variabili dello scope esterno anche dopo che la funzione esterna è terminata. Usata per dati privati e factory functions." },
    { fronte: "Cos'è AJAX?",
      retro: "Asynchronous JavaScript And XML: tecnica per aggiornare parti di una pagina senza ricaricarla, tramite richieste HTTP asincrone. Oggi si usa JSON invece di XML." },
    { fronte: "Validazione form lato client",
      retro: "Controllo degli input prima dell'invio con JavaScript (required, pattern, min/max, custom logic). Migliora UX ma NON garantisce sicurezza — serve sempre validazione server-side." },
    { fronte: "Costruzione dinamica tabella HTML",
      retro: "Creare table > tbody con createElement. Iterare i dati con for/forEach, creare tr e td per ogni riga, inserire dati con textContent, appendChild la riga al tbody." },
    { fronte: "Funzioni freccia (arrow functions)",
      retro: "Sintassi breve: const fn = (param) => espressione. Non hanno il proprio this — lo ereditano dallo scope esterno. Ideale per callback brevi." }
  ],

  /* ──────────────────────────────────────────────────────────
     MODULO 4 — SQL
  ────────────────────────────────────────────────────────── */
  "sql": [
    { fronte: "Differenza DDL e DML in SQL",
      retro: "DDL (Data Definition Language): definisce la struttura — CREATE, ALTER, DROP, TRUNCATE. DML (Data Manipulation Language): manipola i dati — SELECT, INSERT, UPDATE, DELETE." },
    { fronte: "Differenza WHERE e HAVING",
      retro: "WHERE filtra le singole righe PRIMA del raggruppamento (GROUP BY). HAVING filtra i gruppi DOPO il raggruppamento. WHERE non può usare funzioni di aggregazione, HAVING sì." },
    { fronte: "INNER JOIN vs LEFT JOIN",
      retro: "INNER JOIN: restituisce solo le righe con corrispondenza in entrambe le tabelle. LEFT JOIN: tutte le righe della tabella sinistra + NULL dove non c'è corrispondenza a destra." },
    { fronte: "Funzioni di aggregazione SQL",
      retro: "COUNT(*): conta righe. SUM(col): somma. AVG(col): media. MAX(col)/MIN(col): massimo/minimo. Si usano con SELECT e opzionalmente GROUP BY." },
    { fronte: "Subquery correlata",
      retro: "Subquery che fa riferimento a colonne della query esterna. Viene eseguita una volta per ogni riga della query esterna — più lenta ma più flessibile." },
    { fronte: "DISTINCT in SQL",
      retro: "Elimina le righe duplicate dal risultato: SELECT DISTINCT colonna FROM tabella. Utile per ottenere valori unici. Lavora sull'intera riga selezionata." },
    { fronte: "Cos'è una VIEW?",
      retro: "Tabella virtuale definita da una query SQL salvata. Non contiene dati fisici: li calcola ogni volta che viene interrogata. Semplifica query complesse e aumenta la sicurezza." },
    { fronte: "Cos'è un trigger?",
      retro: "Procedura automatica eseguita BEFORE o AFTER un evento DML (INSERT, UPDATE, DELETE) su una tabella. Usata per audit, validazione dati o mantenimento di coerenza." },
    { fronte: "TRUNCATE vs DELETE",
      retro: "DELETE: rimuove righe una per una (con WHERE possibile, loggabile, può fare ROLLBACK). TRUNCATE: svuota tutta la tabella, più veloce, non loggabile riga per riga, azzera AUTO_INCREMENT." },
    { fronte: "ON DUPLICATE KEY UPDATE",
      retro: "Istruzione MySQL: se INSERT viola una chiave univoca, esegue UPDATE al posto dell'errore. Utile per operazioni 'upsert' (insert OR update)." },
    { fronte: "UNION vs UNION ALL",
      retro: "UNION: combina risultati di due SELECT eliminando i duplicati (più lento). UNION ALL: combina tutti i risultati inclusi i duplicati (più veloce). Le SELECT devono avere stesso numero e tipo di colonne." },
    { fronte: "GROUP BY in SQL",
      retro: "Raggruppa le righe con lo stesso valore nelle colonne specificate. Ogni gruppo produce una sola riga nel risultato. Usato con funzioni di aggregazione come COUNT, SUM, AVG." },
    { fronte: "DATE_FORMAT() in MySQL",
      retro: "DATE_FORMAT(data, formato): formatta una data. Esempi: DATE_FORMAT(NOW(), '%d/%m/%Y') → '01/06/2026'. Formati: %Y anno, %m mese, %d giorno, %H ora, %i minuti." },
    { fronte: "Cos'è una stored procedure?",
      retro: "Blocco di istruzioni SQL salvato sul server con un nome. Eseguibile con CALL nomeProcedura(). Accetta parametri IN/OUT. Migliora performance (precompilata) e sicurezza." },
    { fronte: "Indici in MySQL",
      retro: "Strutture che velocizzano la ricerca di dati (come l'indice di un libro). Creati automaticamente su PRIMARY KEY e FOREIGN KEY. Manualmente con CREATE INDEX. Rallentano INSERT/UPDATE." }
  ],

  /* ──────────────────────────────────────────────────────────
     MODULO 5 — Applicazioni Web Integrate
  ────────────────────────────────────────────────────────── */
  "applicazioni-web": [
    { fronte: "Stack tecnologico app web dinamiche",
      retro: "HTML/CSS (presentazione) + JavaScript (logica client) + PHP (logica server) + MySQL (database). Comunicazione tra client e server via AJAX, dati in formato JSON." },
    { fronte: "Ciclo di vita di una richiesta AJAX",
      retro: "1. JS crea XMLHttpRequest o fetch(). 2. Invia richiesta HTTP al server (GET o POST). 3. PHP elabora e risponde con JSON. 4. JS riceve risposta. 5. Aggiorna il DOM senza ricaricare." },
    { fronte: "SQL Injection — cos'è e come prevenirla",
      retro: "Attacco che inserisce codice SQL malevolo nei parametri di una query. Prevenzione: PREPARED STATEMENTS in MySQLi (bind_param) o PDO. Mai concatenare input utente in SQL." },
    { fronte: "Cross-Site Scripting (XSS)",
      retro: "Attacco che inietta JavaScript malevolo nella pagina vista da altri utenti. Prevenzione PHP: htmlspecialchars() prima di stampare input utente. Lato JS: textContent invece di innerHTML." },
    { fronte: "Come PHP risponde con JSON",
      retro: "header('Content-Type: application/json'); echo json_encode($array); exit; — Imposta il tipo di risposta, serializza l'array PHP in JSON e termina lo script." },
    { fronte: "Cos'è il CRUD?",
      retro: "Create, Read, Update, Delete — le quattro operazioni fondamentali su qualsiasi risorsa. Mappano su: INSERT, SELECT, UPDATE, DELETE in SQL e POST, GET, PUT/PATCH, DELETE in REST." },
    { fronte: "Vantaggi dell'uso di viste SQL in un'app web",
      retro: "Semplificano le query PHP (SELECT su vista invece di JOIN complessi), nascondono la struttura interna, migliorano sicurezza (esponi solo dati necessari) e manutenibilità." },
    { fronte: "Session hijacking — cos'è e prevenzione",
      retro: "Furto del session_id per impersonare un utente. Prevenzione: HTTPS, session_regenerate_id() dopo login, timeout breve di sessione, HttpOnly e Secure sui cookie." },
    { fronte: "Differenza tra elaborazione client-side e server-side",
      retro: "Client-side (JavaScript): elaborazione nel browser, visibile all'utente, veloce ma non sicura. Server-side (PHP): elaborazione sul server, non visibile, sicura, accesso al database." },
    { fronte: "Fasi di sviluppo di un'applicazione web",
      retro: "1. Analisi requisiti. 2. Progettazione (DB, interfaccia, architettura). 3. Sviluppo (PHP + JS + SQL). 4. Test e debug. 5. Deploy. 6. Manutenzione." }
  ],

  /* ──────────────────────────────────────────────────────────
     MODULO 6 — Progettazione concettuale, logica e fisica del DB
  ────────────────────────────────────────────────────────── */
  "progettazione-db": [
    { fronte: "Le tre fasi della progettazione di un DB",
      retro: "1. Concettuale: analisi requisiti + diagramma E/R. 2. Logica: traduzione E/R → schema relazionale (tabelle + chiavi). 3. Fisica: implementazione SQL su MySQL con tipi di dato e indici." },
    { fronte: "Cos'è un'entità debole?",
      retro: "Entità senza attributi sufficienti per identificarsi da sola. Dipende da un'entità forte tramite una relazione identificante. La sua chiave primaria include la PK dell'entità forte." },
    { fronte: "Come si traduce N:N nel modello relazionale",
      retro: "Si crea una tabella di associazione (tabella ponte) con le PK di entrambe le entità come FK. La PK della tabella ponte è la combinazione delle due FK (PK composta)." },
    { fronte: "Prima Forma Normale (1NF)",
      retro: "Ogni attributo deve essere atomico (valore singolo, non divisibile). Nessun gruppo ripetuto. La tabella ha una chiave primaria definita." },
    { fronte: "Seconda Forma Normale (2NF)",
      retro: "Soddisfa 1NF + ogni attributo non-chiave dipende funzionalmente dall'INTERA chiave primaria (nessuna dipendenza parziale). Si applica quando la PK è composta." },
    { fronte: "Terza Forma Normale (3NF)",
      retro: "Soddisfa 2NF + nessun attributo non-chiave dipende transitivamente da un altro attributo non-chiave (nessuna dipendenza transitiva). Elimina ridondanze." },
    { fronte: "Cos'è una dipendenza funzionale?",
      retro: "A → B: il valore di A determina univocamente il valore di B. Se conosco A, conosco B. Fondamentale per identificare le anomalie e normalizzare il database." },
    { fronte: "Generalizzazione ISA",
      retro: "Relazione tra un'entità padre e entità figlie: le figlie 'sono un tipo di' padre (es. Persona ISA Studente/Professore). Le figlie ereditano gli attributi del padre." },
    { fronte: "Anomalie nei database non normalizzati",
      retro: "Inserimento: impossibile inserire dati senza informazioni non pertinenti. Cancellazione: perdita accidentale di dati correlati. Aggiornamento: necessità di modificare righe multiple rischiando inconsistenza." },
    { fronte: "Come si traduce la cardinalità 1:N",
      retro: "La PK dell'entità 'uno' diventa FK (chiave esterna) nell'entità 'molti'. Non si crea tabella aggiuntiva. La FK può avere vincoli NOT NULL o essere nullable (partecipazione opzionale)." },
    { fronte: "Ristrutturazione del diagramma E/R",
      retro: "Passi: 1. Eliminare attributi multivalore (→ nuova entità). 2. Eliminare generalizzazioni (3 strategie: unica tabella, tabella padre+figlie, solo tabelle figlie). 3. Semplificare associazioni complesse." },
    { fronte: "Gerarchia subset vs gerarchia totale",
      retro: "Subset (parziale): non ogni istanza padre ha un'istanza figlia. Totale: ogni istanza padre DEVE essere in almeno una figlia. Esclusiva: ogni istanza è al massimo in una figlia." },
    { fronte: "Cos'è la progettazione fisica?",
      retro: "Traduzione dello schema logico in SQL concreto: scelta tipi di dato (INT vs BIGINT, VARCHAR(n)), vincoli SQL (NOT NULL, UNIQUE, CHECK), CREATE TABLE con FK, indici per ottimizzare le query." },
    { fronte: "Differenza tra schema E/R e schema relazionale",
      retro: "E/R: rappresentazione visuale e concettuale — entità, attributi, associazioni con simboli grafici. Relazionale: tabelle con colonne, tipi di dato, chiavi primarie ed esterne — pronto per SQL." },
    { fronte: "Partecipazione obbligatoria vs opzionale",
      retro: "Obbligatoria: ogni istanza DEVE partecipare all'associazione (FK NOT NULL). Opzionale: può non partecipare (FK ammette NULL). Nel modello E/R si indica con linea doppia (obbligatoria)." }
  ],

  /* ──────────────────────────────────────────────────────────
     MODULO 7 — Sicurezza delle applicazioni web
  ────────────────────────────────────────────────────────── */
  "sicurezza": [
    { fronte: "CIA Triad",
      retro: "I tre pilastri della sicurezza informatica: Confidenzialità (solo gli autorizzati accedono ai dati), Integrità (i dati non vengono alterati non autorizzatamente), Disponibilità (i servizi sono accessibili quando servono)." },
    { fronte: "SQL Injection — cos'è e come si previene",
      retro: "Attacco che inietta codice SQL nell'input per alterare le query. Prevenzione OBBLIGATORIA: prepared statements con bind_param() in PHP. MAI concatenare input utente in stringhe SQL." },
    { fronte: "XSS — Cross-Site Scripting",
      retro: "Attacco che inietta JavaScript malevolo nell'HTML della pagina visto dagli utenti. Prevenzione PHP: htmlspecialchars($input, ENT_QUOTES, 'UTF-8'). Prevenzione JS: textContent invece di innerHTML." },
    { fronte: "CSRF — Cross-Site Request Forgery",
      retro: "Un sito malevolo forza il browser della vittima autenticata a inviare richieste non volute. Mitigazione: token CSRF univoco per sessione nel form, verificato server-side. Anche SameSite=Strict nei cookie." },
    { fronte: "password_hash() e password_verify()",
      retro: "password_hash($pwd, PASSWORD_BCRYPT): genera hash bcrypt con salt casuale. password_verify($input, $hash): confronta in modo sicuro contro timing attack. MAI usare md5/sha1 per le password." },
    { fronte: "HttpOnly e Secure nei cookie",
      retro: "HttpOnly: il cookie non è leggibile da JavaScript (previene furto via XSS). Secure: il cookie viene inviato solo su HTTPS (previene intercettazione). Entrambi vanno sempre impostati per i cookie di sessione." },
    { fronte: "HTTPS e TLS",
      retro: "HTTPS usa TLS per crittografare tutto il traffico tra browser e server. Garantisce: confidenzialità (nessuno intercetta), integrità (dati non modificati in transito), autenticazione server (certificato digitale)." },
    { fronte: "session_regenerate_id(true)",
      retro: "Genera un nuovo session_id dopo il login, invalidando quello precedente. Previene il session fixation attack (l'attaccante non può predeterminare il session_id). Va chiamata SEMPRE dopo autenticazione riuscita." },
    { fronte: "Defense in depth",
      retro: "Principio di sicurezza: applicare più livelli di protezione sovrapposti. Se un livello fallisce, gli altri proteggono. Web app: validazione client + server + prepared statements + htmlspecialchars + HTTPS + password_hash." },
    { fronte: "HSTS — HTTP Strict Transport Security",
      retro: "Header HTTP che istruisce il browser a usare SEMPRE HTTPS per un dominio, anche se l'utente digita http://. Previene attacchi downgrade. Esempio: Strict-Transport-Security: max-age=31536000; includeSubDomains" },
    { fronte: "Differenza validazione client vs server",
      retro: "Client-side (JS): migliora UX, feedback immediato, ma FACILMENTE aggirabile. Server-side (PHP): obbligatoria per la sicurezza, un attaccante può bypassare il browser. Servono ENTRAMBE, per scopi diversi." },
    { fronte: "Prepared statements — come funzionano",
      retro: "$stmt = $conn->prepare('SELECT * FROM u WHERE email=?'); $stmt->bind_param('s', $email); $stmt->execute(); — Il driver MySQL separa la struttura SQL dai dati: l'input non può mai diventare codice SQL." },
    { fronte: "TLS vs SSL",
      retro: "SSL (Secure Sockets Layer) è il predecessore deprecato e insicuro. TLS (Transport Layer Security) è il successore attuale (versioni 1.2 e 1.3). Il termine 'SSL' viene spesso usato impropriamente per indicare TLS." },
    { fronte: "Content Security Policy (CSP)",
      retro: "Header HTTP che dice al browser da quali fonti può caricare script, stili, immagini ecc. Mitiga gli attacchi XSS limitando l'esecuzione di script non autorizzati. Esempio: Content-Security-Policy: default-src 'self'" },
    { fronte: "Same-Origin Policy",
      retro: "Politica del browser che impedisce a JavaScript di accedere a risorse di un'origine diversa (schema+dominio+porta). Protegge dall'accesso cross-domain ai dati. CORS è il meccanismo per consentire eccezioni controllate." }
  ],

  /* ──────────────────────────────────────────────────────────
     MODULO 8 — Algoritmi e strutture dati
  ────────────────────────────────────────────────────────── */
  "algoritmi": [
    { fronte: "Big-O — notazione O-grande",
      retro: "Descrive il limite superiore asintotico della complessità al crescere di n. Non misura tempi assoluti ma tendenze di crescita. O(1)=costante, O(log n)=logaritmico, O(n)=lineare, O(n²)=quadratico, O(2ⁿ)=esponenziale." },
    { fronte: "Bubble Sort",
      retro: "Confronta coppie adiacenti e le scambia se non sono in ordine; ripete per n passate. Semplice ma inefficiente. Complessità: O(n²) nel caso medio e peggiore, O(n) nel migliore (array già ordinato con ottimizzazione)." },
    { fronte: "Selection Sort",
      retro: "Ad ogni passata i, trova il minimo negli elementi da i a n, lo scambia con la posizione i. Complessità SEMPRE O(n²) — indipendente dall'input. Vantaggio: poche scritture in memoria." },
    { fronte: "Merge Sort",
      retro: "Divide et impera: divide l'array a metà ricorsivamente, poi fonde (merge) le metà ordinate. Complessità SEMPRE O(n log n) — stabile. Svantaggio: richiede O(n) spazio extra per l'array temporaneo." },
    { fronte: "Quick Sort",
      retro: "Sceglie un pivot, partiziona in <pivot e >pivot, applica ricorsivamente. Caso medio O(n log n), caso peggiore O(n²) se il pivot è sempre l'estremo. In pratica spesso più veloce di Merge Sort (cache-friendly)." },
    { fronte: "Ricerca binaria",
      retro: "Cerca in un array ORDINATO dimezzando lo spazio di ricerca: confronta con il centro, va a destra o sinistra. Prerequisito: array ordinato. Complessità O(log n). Per 1.000.000 elementi: solo ~20 confronti." },
    { fronte: "Ricerca lineare",
      retro: "Scorre l'array dall'inizio fino a trovare l'elemento. Non richiede ordinamento. Complessità O(n) nel caso peggiore. Unica opzione per array non ordinati o strutture dati senza accesso random." },
    { fronte: "Stack — pila (LIFO)",
      retro: "Last In First Out: l'ultimo elemento inserito è il primo a uscire. Operazioni: push (inserisce in cima), pop (rimuove dalla cima), peek (legge la cima). Usi: call stack, undo/redo, valutazione espressioni." },
    { fronte: "Queue — coda (FIFO)",
      retro: "First In First Out: il primo elemento inserito è il primo a uscire. Operazioni: enqueue (inserisce in fondo), dequeue (rimuove dalla testa). Usi: coda di stampa, BFS nei grafi, gestione richieste web." },
    { fronte: "Array — complessità operazioni",
      retro: "Accesso per indice: O(1). Ricerca non ordinato: O(n). Inserimento/cancellazione in mezzo: O(n) (sposta elementi). Inserimento in coda: O(1) amortizzato. Memoria contigua → ottimale per cache." },
    { fronte: "Lista collegata (linked list)",
      retro: "Sequenza di nodi, ognuno con dato e puntatore al successivo. Inserimento/cancellazione (con puntatore): O(1). Accesso per indice: O(n). Nessun accesso random — scorre sempre dalla testa." },
    { fronte: "Tabella hash — hash table",
      retro: "Struttura che mappa chiavi a valori tramite una funzione hash. Complessità media: O(1) per inserimento, ricerca, cancellazione. Caso peggiore O(n) per collisioni. Collisioni gestite con chaining o open addressing." },
    { fronte: "Albero binario di ricerca (BST)",
      retro: "Albero dove ogni nodo ha al massimo 2 figli. Proprietà: sottoalbero sinistro < nodo < sottoalbero destro. Ricerca/inserimento: O(log n) medio, O(n) peggiore (albero sbilanciato). BST bilanciati (AVL, Red-Black): O(log n) garantito." },
    { fronte: "Divide et impera",
      retro: "Tecnica algoritmica: 1) Divide il problema in sotto-problemi più piccoli. 2) Risolve ricorsivamente. 3) Combina le soluzioni. Esempi: Merge Sort, Quick Sort, ricerca binaria. Porta spesso a O(n log n)." },
    { fronte: "Complessità spaziale",
      retro: "Quantità di memoria extra usata dall'algoritmo (non conta l'input). Merge Sort: O(n) spazio. Quick Sort in-place: O(log n) per lo stack ricorsivo. Ricerca binaria iterativa: O(1). Da considerare insieme alla complessità temporale." }
  ],

  /* ──────────────────────────────────────────────────────────
     MODULO 9 — API REST e architetture moderne
  ────────────────────────────────────────────────────────── */
  "api-rest": [
    { fronte: "REST — Representational State Transfer",
      retro: "Stile architetturale per API web formulato da Roy Fielding. Principi chiave: stateless (ogni richiesta è autocontenuta), uniform interface (URL=risorsa, HTTP method=azione), client-server separati, cacheable." },
    { fronte: "Metodi HTTP: GET, POST, PUT, PATCH, DELETE",
      retro: "GET: legge (sicuro, idempotente). POST: crea risorsa. PUT: sostituisce intera risorsa. PATCH: aggiornamento parziale. DELETE: elimina. Idempotente = ripetere N volte = stesso effetto di 1 volta." },
    { fronte: "HTTP Status Codes principali",
      retro: "200 OK, 201 Created (POST riuscito), 204 No Content (DELETE), 400 Bad Request (input errato), 401 Unauthorized (non autenticato), 403 Forbidden (non autorizzato), 404 Not Found, 500 Internal Server Error." },
    { fronte: "Stateless nelle API REST",
      retro: "Il server non mantiene stato del client tra richieste. Ogni richiesta deve contenere TUTTE le info necessarie (incluso il token di autenticazione). Vantaggio: scalabilità orizzontale semplice, nessuna sessione da sincronizzare." },
    { fronte: "JWT — JSON Web Token",
      retro: "Token firmato digitalmente composto da: Header.Payload.Signature (separati da punti, Base64-encoded). Il server verifica la firma senza consultare il DB. Il payload contiene i claim (es. user_id, ruolo, scadenza)." },
    { fronte: "API Key vs JWT",
      retro: "API Key: stringa segreta semplice, il server deve verificarla nel DB. JWT: token firmato che contiene già i dati, verificabile senza DB (stateless). JWT è preferito per scalabilità; API Key per semplicità machine-to-machine." },
    { fronte: "cURL in PHP",
      retro: "curl_init() → curl_setopt(CURLOPT_URL, CURLOPT_RETURNTRANSFER=true, CURLOPT_HTTPHEADER) → curl_exec() → curl_close(). Poi json_decode($response, true). Usato per consumare API esterne in PHP." },
    { fronte: "fetch() in JavaScript",
      retro: "API nativa moderna: fetch('/api/dati', {method:'POST', headers:{...}, body:JSON.stringify(dati)}).then(r => r.json()).then(data => ...). Restituisce una Promise. Sostituisce XMLHttpRequest per le nuove applicazioni." },
    { fronte: "CORS — Cross-Origin Resource Sharing",
      retro: "Meccanismo per consentire richieste JavaScript cross-domain. Il server deve includere: Access-Control-Allow-Origin: https://miodominio.com. Senza CORS il browser blocca le richieste fetch verso altri domini." },
    { fronte: "Endpoint REST — design URL",
      retro: "Best practice: /risorse (plurale, lowercase). GET /utenti → lista. POST /utenti → crea. GET /utenti/5 → dettaglio. PUT /utenti/5 → aggiorna. DELETE /utenti/5 → elimina. Nomi, non verbi nell'URL." },
    { fronte: "Bearer token nell'header HTTP",
      retro: "Authorization: Bearer eyJ... è il modo standard per inviare token JWT nelle richieste API. Il server legge: $token = str_replace('Bearer ', '', $_SERVER['HTTP_AUTHORIZATION']); e verifica la firma." },
    { fronte: "Content-Type: application/json",
      retro: "Header HTTP che indica il formato del body. Il server PHP deve inviarlo prima di echo json_encode(): header('Content-Type: application/json'). Il client deve inviarlo nelle richieste POST/PUT con JSON nel body." },
    { fronte: "php://input",
      retro: "Stream PHP che contiene il body grezzo della richiesta HTTP. Necessario per leggere JSON inviato da fetch/axios in POST/PUT: $body = json_decode(file_get_contents('php://input'), true). Non usa $_POST per JSON." },
    { fronte: "Idempotenza nelle API",
      retro: "Un'operazione idempotente produce lo stesso risultato se ripetuta N volte. GET, PUT, DELETE sono idempotenti. POST non è idempotente (crea nuove risorse ad ogni chiamata). PATCH può o non può esserlo a seconda dell'implementazione." },
    { fronte: "Rate limiting",
      retro: "Limitazione del numero di richieste per client in un periodo. Previene abuso, DDoS, brute force. Risposta: 429 Too Many Requests. Implementabile con contatori Redis o variabili di sessione. Header: Retry-After." }
  ],

  /* ──────────────────────────────────────────────────────────
     MODULO 10 — Gestione avanzata dei database
  ────────────────────────────────────────────────────────── */
  "db-avanzato": [
    { fronte: "Proprietà ACID",
      retro: "Atomicità: tutto o niente. Consistenza: stato valido→stato valido. Isolamento: transazioni concorrenti non si interferiscono. Durabilità: dopo COMMIT i dati persistono anche dopo crash. Garantite da InnoDB in MySQL." },
    { fronte: "BEGIN, COMMIT, ROLLBACK",
      retro: "BEGIN (o START TRANSACTION): avvia una transazione. COMMIT: conferma tutte le modifiche rendendole permanenti. ROLLBACK: annulla tutte le modifiche dall'ultima BEGIN. SAVEPOINT nome: crea punto di ripristino parziale." },
    { fronte: "Autocommit in MySQL",
      retro: "Default MySQL: ogni istruzione DML è automaticamente una transazione (autocommit=1). Per transazioni multi-statement: SET autocommit=0 oppure usare BEGIN...COMMIT/ROLLBACK esplicitamente." },
    { fronte: "Indice B-tree",
      retro: "Tipo di indice default in InnoDB. Struttura ad albero bilanciato che supporta: eguaglianza (=), confronto (<, >, BETWEEN), LIKE 'prefix%'. Non supporta LIKE '%suffix'. Creato automaticamente su PK e FK." },
    { fronte: "Quando creare un indice?",
      retro: "Conviene: colonne in WHERE/ORDER BY/JOIN frequenti, alta cardinalità (es. email). NON conviene: bassa selettività (es. genere M/F), tabelle piccole, colonne con molte scritture (ogni INSERT/UPDATE aggiorna l'indice)." },
    { fronte: "EXPLAIN in MySQL",
      retro: "EXPLAIN SELECT ... mostra il piano di esecuzione: type (ALL=full scan pericoloso, ref/eq_ref=usa indice), key (quale indice), rows (stima righe esaminate). type=ALL + rows alto = problema di performance." },
    { fronte: "Deadlock",
      retro: "Due transazioni si bloccano a vicenda: T1 attende T2 e T2 attende T1. MySQL rileva il ciclo e fa ROLLBACK della 'victim'. Prevenzione: accedere alle risorse sempre nello stesso ordine, tenere le transazioni brevi." },
    { fronte: "mysqldump — backup",
      retro: "mysqldump -u root -p nomeDB > backup.sql esporta il database in SQL (CREATE TABLE + INSERT). Per ripristinare: mysql -u root -p nomeDB < backup.sql. phpMyAdmin ha un'interfaccia grafica per la stessa operazione." },
    { fronte: "NoSQL vs SQL",
      retro: "SQL: schema fisso, ACID, relazioni via JOIN, ottimale per dati strutturati. NoSQL: schema flessibile, scalabilità orizzontale semplice, ottimale per big data e dati non strutturati. Non è superiore — ha casi d'uso diversi." },
    { fronte: "MongoDB — struttura",
      retro: "Database NoSQL orientato ai documenti. Struttura: Database → Collections (≈tabelle) → Documents (≈righe, formato BSON/JSON). I documenti nella stessa collection possono avere campi diversi (schema flessibile). _id è il campo ID auto-generato." },
    { fronte: "ORM — Object-Relational Mapper",
      retro: "Libreria che mappa oggetti del linguaggio a tabelle del DB, astraendo SQL. Esempi: Eloquent (Laravel/PHP), SQLAlchemy (Python), Hibernate (Java). Pro: sviluppo rapido, portabile. Contro: query generate possono essere inefficienti." },
    { fronte: "Livelli di isolamento SQL",
      retro: "READ UNCOMMITTED (dirty reads possibili), READ COMMITTED (no dirty reads), REPEATABLE READ (default MySQL InnoDB, no non-repeatable reads), SERIALIZABLE (massimo isolamento, minima concorrenza)." },
    { fronte: "Scalabilità verticale vs orizzontale",
      retro: "Verticale (scale up): aggiungere più CPU/RAM allo stesso server. Limite fisico e costi alti. Orizzontale (scale out): aggiungere più server. NoSQL è progettato per scalabilità orizzontale. SQL può scalare verticalmente più facilmente." },
    { fronte: "Replicazione database",
      retro: "Copia sincronizzata del database su più server. Master-slave: il master gestisce le scritture, gli slave le letture. Vantaggi: alta disponibilità, bilanciamento del carico in lettura, failover automatico." },
    { fronte: "Query plan e ottimizzazione",
      retro: "Il query optimizer di MySQL sceglie il piano di esecuzione più efficiente. Se sceglie male: FORCE INDEX(nome_indice) o riscrivere la query. ANALYZE TABLE aggiorna le statistiche che il planner usa per le sue decisioni." }
  ]
};
