/* =========================================================================
   quiz-data.js — English Literature Quiz Data (300+ questions)
   Format: window.QUIZ_DATA[key] = array of question objects
   { q, opts:[a,b,c,d], ans:0-3, expl }
   ========================================================================= */

window.QUIZ_DATA = {};

/* ══ GEORGE ORWELL ══ */
window.QUIZ_DATA.orwell = [
  { q:"In which year was George Orwell's novel '1984' published?", opts:["1946","1948","1949","1952"], ans:2, expl:"1984 was published in June 1949, a year before Orwell's death." },
  { q:"What is the real name of the protagonist of 1984?", opts:["John Smith","Winston Smith","James Orwell","Bernard Marx"], ans:1, expl:"Winston Smith is a low-ranking member of the Party who works at the Ministry of Truth." },
  { q:"What does 'Big Brother' represent in 1984?", opts:["A television programme","The omnipresent leader of the Party","Winston's actual brother","A surveillance technology company"], ans:1, expl:"Big Brother is the figurehead of the totalitarian Party — always watching, possibly fictional." },
  { q:"What is 'Newspeak' in 1984?", opts:["A new radio technology","The Party's official language designed to reduce thought","A newspaper published by the Party","A code used by the resistance"], ans:1, expl:"Newspeak eliminates words to make thoughtcrime literally impossible." },
  { q:"What is 'doublethink'?", opts:["The ability to think in two languages","Holding two contradictory beliefs simultaneously","A method of encryption","Thinking twice before speaking"], ans:1, expl:"Doublethink: holding two contradictory beliefs and accepting both as true — a tool of Party control." },
  { q:"What are the Party's three slogans in 1984?", opts:["Peace is War, Slavery is Freedom, Strength is Ignorance","War is Peace, Freedom is Slavery, Ignorance is Strength","Truth is Lies, Love is Hate, Life is Death","Work is Play, Rest is Death, Pleasure is Pain"], ans:1, expl:"The three slogans appear on the Ministry of Truth building and represent the Party's doublethink." },
  { q:"What is Room 101 in 1984?", opts:["The Party's headquarters","A torture room containing each prisoner's worst fear","The Ministry of Love's meeting room","A secret resistance hideout"], ans:1, expl:"Room 101 contains each prisoner's personal worst fear — for Winston it is rats." },
  { q:"Who is O'Brien in 1984?", opts:["A member of the Brotherhood resistance","A senior Party member who poses as a sympathiser then tortures Winston","Winston's superior at work","A prole poet"], ans:1, expl:"O'Brien appears to be an ally but reveals himself as a dedicated torturer and Party loyalist." },
  { q:"What is Animal Farm an allegory of?", opts:["World War II","The Spanish Civil War","The Russian Revolution and Stalin's rule","The French Revolution"], ans:2, expl:"Each character represents a real figure: Napoleon=Stalin, Snowball=Trotsky, Old Major=Marx/Lenin." },
  { q:"What does the phrase 'All animals are equal, but some animals are more equal than others' mean?", opts:["It is a logical paradox with no meaning","The pigs have become as oppressive as the humans they replaced","Animals are naturally hierarchical","Napoleon is the best animal"], ans:1, expl:"The phrase shows how the pigs have corrupted the original revolutionary ideals to justify their own privilege." },
  { q:"Which country does Orwell represent as 'Manor Farm' in Animal Farm?", opts:["Britain","Germany","Russia/Soviet Union","France"], ans:2, expl:"Manor Farm represents Russia/the Soviet Union under Communist rule." },
  { q:"What is the Thought Police in 1984?", opts:["The Ministry of Peace","The secret police who detect and punish thoughtcrime","A division of the Ministry of Truth","The internal affairs department"], ans:1, expl:"The Thought Police monitor citizens for thoughtcrime using telescreens and informers." },
  { q:"What does 'telescreen' mean in 1984?", opts:["A large cinema screen","A two-way television that broadcasts and surveys simultaneously","A mobile communication device","A projector used in schools"], ans:1, expl:"Telescreens are everywhere — they broadcast Party propaganda and surveil citizens simultaneously." },
  { q:"What are the proles in 1984?", opts:["The inner Party elite","The thought police agents","The working-class majority largely ignored by the Party","The outer party members"], ans:2, expl:"The proles (proletariat) make up 85% of Oceania's population and are left largely free because the Party considers them no threat." },
  { q:"Why did Orwell invert the last two digits of '1948' to get '1984'?", opts:["It was a random choice","To create a sense of imminent future","To reference a historical date","He actually wrote it in 1984"], ans:1, expl:"By inverting 48 to 84, Orwell created a near-future that felt frighteningly close to the present." },
  { q:"What is Winston's job at the Ministry of Truth?", opts:["Writing propaganda posters","Rewriting historical records to match the Party's current version","Monitoring telescreens","Translating documents into Newspeak"], ans:1, expl:"Winston rewrites old newspaper articles and deletes 'unpersons' from history — a daily act of falsification." },
  { q:"What is Julia's attitude to the Party in 1984?", opts:["She is a fervent supporter","She wants to join the Brotherhood","She rebels pragmatically through personal pleasure, not political ideology","She plans to escape to another country"], ans:2, expl:"Julia's rebellion is personal and physical — she enjoys breaking the rules but is not interested in abstract politics." },
  { q:"What does 2+2=5 represent in 1984?", opts:["A Newspeak mathematical formula","The Party's power to override objective reality and truth","A code used by the Brotherhood","Winston's maths mistake"], ans:1, expl:"The Party insists that 2+2=5 if it says so — ultimate power means controlling not just behaviour but reality itself." },
  { q:"What is Orwell's political position?", opts:["Communist","Fascist","Conservative","Democratic socialist"], ans:3, expl:"Orwell was a committed democratic socialist who opposed both Stalinism and capitalism." },
  { q:"What is the significance of Winston's diary in 1984?", opts:["It contains Brotherhood secrets","It is his act of thoughtcrime — writing 'DOWN WITH BIG BROTHER' is already a crime","It is a love letter to Julia","It is government-issued"], ans:1, expl:"The diary is Winston's private act of resistance — the moment he begins writing it, he is already a thoughtcriminal." },
  { q:"Which ministry controls war in 1984?", opts:["The Ministry of Truth","The Ministry of Plenty","The Ministry of Peace","The Ministry of Love"], ans:2, expl:"The Ministry of Peace (Minipax) is responsible for waging continuous war — ironic Newspeak naming." },
  { q:"What happens to Winston at the end of 1984?", opts:["He escapes to another country","He joins the Brotherhood","He is broken, loves Big Brother and is destroyed as a free thinker","He leads a successful revolution"], ans:2, expl:"After torture in Room 101, Winston is fully broken — his final thought is that he loves Big Brother." },
  { q:"What is the 'unperson' in 1984?", opts:["A prole with no identity card","Someone erased from all records as if they never existed","A robot used by the Ministry","A prisoner in Room 101"], ans:1, expl:"When someone is vaporized by the Party, all records of their existence are erased — they become an 'unperson'." },
  { q:"Who is Emmanuel Goldstein in 1984?", opts:["Winston's father","The alleged enemy of the Party used in the Two Minutes Hate","The leader of the Brotherhood","An outer Party official"], ans:1, expl:"Goldstein is supposedly the enemy of the Party — his book is used to identify dissidents. He may be entirely fictional." }
];

/* ══ MARY SHELLEY ══ */
window.QUIZ_DATA.shelley = [
  { q:"What is the full title of Mary Shelley's 1818 novel?", opts:["Frankenstein","Frankenstein; or, The Modern Prometheus","The Modern Monster","Creature of Science"], ans:1, expl:"The subtitle 'The Modern Prometheus' refers to the Greek myth of the Titan who stole fire and was punished." },
  { q:"Where was the idea for Frankenstein conceived?", opts:["London","Edinburgh","Villa Diodati, Lake Geneva","Paris"], ans:2, expl:"During the ghost story contest at Villa Diodati in 1816, Mary Shelley conceived the idea." },
  { q:"What was the 'Year Without a Summer' and why is it relevant to Frankenstein?", opts:["A metaphor in the novel","1816 — caused by the Tambora eruption, creating the dark conditions inspiring Shelley's story","A character's period of depression","The year Victor Frankenstein spends alone"], ans:1, expl:"The eruption of Mount Tambora caused crop failures and dark weather across Europe in 1816." },
  { q:"Who is Victor Frankenstein?", opts:["A Swiss scientist obsessed with creating life","An English doctor working in London","A philosopher who theorises about life","A politician who bans scientific experiments"], ans:0, expl:"Victor Frankenstein is a young Swiss scientist who becomes obsessed with the secret of life and creates the Creature." },
  { q:"What does the Prometheus myth represent in relation to Frankenstein?", opts:["The creation of fire","The hubris of creating life beyond human limits, with punishment following","The theft of technology","The need for scientific progress"], ans:1, expl:"Like Prometheus who stole fire and was eternally punished, Victor steals the power of creation and suffers for it." },
  { q:"What is the narrative structure of Frankenstein?", opts:["First person narrative by Victor","Linear third-person omniscient","Nested narratives: Walton → Victor → the Creature","Alternating perspectives between Victor and the Creature"], ans:2, expl:"Walton's letters frame Victor's story which frames the Creature's own narrative — a 'Chinese box' structure." },
  { q:"Who are Mary Shelley's famous parents?", opts:["Lord Byron and Jane Austen","William Godwin and Mary Wollstonecraft","Percy Shelley and Charlotte Brontë","Charles Lamb and Dorothy Wordsworth"], ans:1, expl:"William Godwin (anarchist philosopher) and Mary Wollstonecraft (feminist, A Vindication of the Rights of Woman)." },
  { q:"What is the Frankenstein Syndrome?", opts:["A fear of lightning","The tendency of creators to be destroyed by their own creations","A medical condition named after the novel","Victor's mental illness"], ans:1, expl:"The Frankenstein Syndrome describes technology or science that exceeds human control and turns against its creator." },
  { q:"What does the Creature demand from Victor?", opts:["Freedom","A name","A female companion","An explanation of how he was created"], ans:2, expl:"The Creature asks Victor to create a female companion — Victor's refusal leads to the Creature's revenge." },
  { q:"Why is Frankenstein considered the first science fiction novel?", opts:["It was published in 1818","It features scientific principles as central plot elements and explores ethical consequences","It was written by a woman","It takes place in a laboratory"], ans:1, expl:"Frankenstein uses actual scientific debates (galvanism, reanimation) and explores their ethical implications — unprecedented." },
  { q:"What is the role of the Arctic in Frankenstein?", opts:["A place of refuge for Victor","The setting of the prologue and epilogue — symbolising extreme ambition at the limits of the world","The Creature's hiding place","The location of Victor's university"], ans:1, expl:"Captain Walton's Arctic expedition frames the novel — both men are driven to the extremes of ambition." },
  { q:"How is the Creature portrayed in the novel (not film versions)?", opts:["As a mindless monster","As a green-faced zombie","As eloquent and educated, made monstrous by society's rejection","As a servant who rebels"], ans:2, expl:"The Creature reads Milton, Goethe and Plutarch — he becomes violent only after repeated rejection." },
  { q:"What is the significance of Mary Shelley's age when writing Frankenstein?", opts:["She was 60, with vast experience","She was 18–19 years old, making the achievement extraordinary","She was 30 and had just lost a child","She wrote it at 40 as her masterwork"], ans:1, expl:"Mary Shelley began the story at 18 during the Villa Diodati summer and published it at 20." },
  { q:"Who else was present at Villa Diodati during the ghost story contest?", opts:["Jane Austen and Charlotte Brontë","Percy Shelley, Lord Byron and John Polidori","Charles Dickens and William Thackeray","Samuel Taylor Coleridge and William Wordsworth"], ans:1, expl:"The group included Percy Shelley, Lord Byron, John Polidori (who wrote The Vampyre) and Mary Shelley." },
  { q:"What aspect of the Industrial Revolution does Frankenstein reflect?", opts:["The benefits of factory production","Anxiety about machines and technology exceeding human control","Praise for scientific progress","The growth of capitalism"], ans:1, expl:"The novel reflects Romantic anxiety about the Industrial Revolution creating powerful forces beyond human governance." }
];

/* ══ OSCAR WILDE ══ */
window.QUIZ_DATA.wilde = [
  { q:"What is Oscar Wilde's most famous novel?", opts:["The Importance of Being Earnest","Salomé","The Picture of Dorian Gray","An Ideal Husband"], ans:2, expl:"The Picture of Dorian Gray (1890) is Wilde's only novel — exploring beauty, corruption and moral decay." },
  { q:"What is the Faustian bargain in Dorian Gray?", opts:["Dorian sells his soul for money","Dorian's portrait ages and shows his sins while he remains beautiful","Dorian trades places with Lord Henry","Dorian becomes a painter"], ans:1, expl:"The portrait absorbs Dorian's moral corruption while he remains young — the portrait becomes his soul." },
  { q:"What is Wilde's aesthetic philosophy?", opts:["Art must teach moral lessons","Art for art's sake — beauty is its own justification","Art should serve the working class","Art must reflect reality accurately"], ans:1, expl:"'Art for art's sake' (l'art pour l'art) — art has no moral purpose, beauty is sufficient justification." },
  { q:"What happened to Wilde in 1895?", opts:["He published his greatest play","He won the Nobel Prize","He was convicted of 'gross indecency' (homosexuality) and imprisoned","He moved to Paris permanently"], ans:2, expl:"Wilde was sentenced to two years' hard labour under the Criminal Law Amendment Act 1885, Section 11." },
  { q:"What is the Dandy figure in Wilde's work?", opts:["A working-class hero","An aristocratic aesthete who values wit and style over substance","A tragic romantic hero","A corrupt politician"], ans:1, expl:"The dandy lives for elegance, wit and pleasure — indifferent to conventional morality." },
  { q:"Who are the three main characters of The Picture of Dorian Gray?", opts:["Dorian, Sybil, James","Dorian, Lord Henry, Basil Hallward","Dorian, Ernest, Algernon","Dorian, Gwendolen, Lady Bracknell"], ans:1, expl:"Lord Henry (hedonistic philosopher), Basil (devoted artist), Dorian (the corrupted beauty)." },
  { q:"What is the main theme of The Importance of Being Earnest?", opts:["The tragedy of star-crossed lovers","The satire of Victorian social hypocrisy through absurd double identities","The dangers of aestheticism","A defence of marriage"], ans:1, expl:"Both Jack and Algernon have invented fictional identities (Ernest/Bunbury) to escape social obligations." },
  { q:"What does 'Bunburying' mean in Earnest?", opts:["A form of Victorian dance","Inventing a fictional sick friend to escape social obligations — a metaphor for living a double life","A method of gardening","A type of social club membership"], ans:1, expl:"Algernon invented 'Bunbury' — a fictional invalid friend he visits whenever he wants to escape." },
  { q:"What did Wilde write while imprisoned?", opts:["The Importance of Being Earnest","De Profundis — a long letter to Lord Alfred Douglas","A Treatise on Aesthetics","The Ballad of Reading Gaol"], ans:1, expl:"De Profundis (1905, posthumous) is Wilde's prison letter to 'Bosie' — passionate and self-analytical." },
  { q:"What is Wilde's connection to Walter Pater?", opts:["Pater was Wilde's publisher","Pater's philosophy of 'burning with a hard gem-like flame' inspired Wilde's aestheticism","They were rivals","Pater wrote the preface to Dorian Gray"], ans:1, expl:"Pater's Conclusion to Studies in the History of the Renaissance was Wilde's aesthetic bible." },
  { q:"What is the ending of The Picture of Dorian Gray?", opts:["Dorian escapes abroad","Dorian reforms and destroys the portrait peacefully","Dorian stabs the portrait; his body is found old and hideous","Basil destroys the portrait and saves Dorian"], ans:2, expl:"By stabbing the portrait Dorian destroys it and himself — his body shows all the years and corruption the portrait had hidden." },
  { q:"What is Wilde's nationality?", opts:["English","Scottish","Irish","Welsh"], ans:2, expl:"Oscar Wilde was Irish, born in Dublin in 1854 — his outsider status informed his satire of the English establishment." },
  { q:"What movement does Wilde represent in English literature?", opts:["Naturalism","Modernism","Aestheticism and Decadentism","Romanticism"], ans:2, expl:"Wilde is the leading English representative of Aestheticism/Decadentism — the cult of beauty over morality." },
  { q:"What is the yellow book that corrupts Dorian in Dorian Gray?", opts:["The Bible","À Rebours by Huysmans, given by Lord Henry","A book by Walter Pater","An art history textbook"], ans:1, expl:"The yellow book is widely interpreted as Huysmans's À Rebours — the 'bible' of Decadentism." },
  { q:"What does Wilde say about art and morality in the preface to Dorian Gray?", opts:["Art should always be moral","There is no such thing as a moral or immoral book — only well or badly written ones","Artists must set a good example","Morality is the highest form of art"], ans:1, expl:"\"There is no such thing as a moral or an immoral book. Books are well written, or badly written. That is all.\"" }
];

/* ══ VIRGINIA WOOLF ══ */
window.QUIZ_DATA.woolf = [
  { q:"What is Virginia Woolf's most famous technique?", opts:["Epic narrative","Stream of consciousness","Magical realism","Epistolary narration"], ans:1, expl:"Stream of consciousness presents the continuous flow of a character's thoughts and perceptions." },
  { q:"What happens on the single day of Mrs Dalloway?", opts:["Clarissa plans her escape from London","Clarissa prepares a party while Septimus Warren Smith moves towards suicide","Clarissa visits her dead mother","Clarissa falls in love with Peter Walsh"], ans:1, expl:"June 1923 — two parallel stories that never quite meet, connected by Clarissa's reaction to Septimus's death." },
  { q:"What does 'A Room of One's Own' (1929) argue?", opts:["Women should not write","A woman needs money and a private space to create fiction","All literature is masculine","Women should write only poetry"], ans:1, expl:"Woolf argues that women have been excluded from literary history because they lacked economic independence and physical space." },
  { q:"What is the Bloomsbury Group?", opts:["A type of tea party","A Victorian women's club","An intellectual and artistic circle including Woolf, Forster and Keynes","A publishing house in London"], ans:2, expl:"The Bloomsbury Group met in the Bloomsbury district of London — progressive, anti-Victorian intellectuals." },
  { q:"Who is Septimus Warren Smith in Mrs Dalloway?", opts:["Clarissa's husband","A shell-shocked WWI veteran whose suicide parallels Clarissa's life","A doctor","Clarissa's former lover"], ans:1, expl:"Septimus represents trauma, madness and the failure of society to care for WWI veterans — Clarissa's dark double." },
  { q:"What is the key difference between clock time and psychological time in Woolf?", opts:["Clock time is modern, psychological time is ancient","Clock time is external and linear; psychological time is subjective and non-linear","They are the same","Psychological time is faster than clock time"], ans:1, expl:"Big Ben chimes mark clock time while characters' minds range freely across decades of memory." },
  { q:"What is the role of Lily Briscoe in To the Lighthouse?", opts:["She is Mrs Ramsay's daughter","She is a painter who struggles to complete her painting — a figure of the woman artist","She is the lighthouse keeper","She is Mrs Ramsay's sister"], ans:1, expl:"Lily's painting represents Woolf's own artistic project — finding a form that captures truth beyond surface appearance." },
  { q:"What is Woolf's concept of 'moments of being'?", opts:["Transcendent spiritual experiences","Sudden revelations that break through the everyday 'cotton wool' of non-being","Moments of historical significance","The opening moments of each novel"], ans:1, expl:"'Moments of being' are sudden illuminations of reality beneath surface experience — Woolf's version of Joyce's epiphany." },
  { q:"How did Virginia Woolf die?", opts:["She was killed in the Blitz","She drowned herself in the River Ouse in 1941","She died of pneumonia","She was killed in an accident"], ans:1, expl:"Fearing another mental breakdown during WWII, Woolf filled her coat with stones and walked into the River Ouse." },
  { q:"What is Orlando (1928) about?", opts:["A Victorian biography","A character who lives 400 years and changes sex — a fantastical satire of gender and literary history","A WWI war story","A feminist essay"], ans:1, expl:"Orlando is dedicated to Vita Sackville-West and explores gender, time and the nature of the literary self." },
  { q:"What does Woolf mean by 'the luminous halo' in her essay 'Modern Fiction'?", opts:["A new lighting technique","Life is a luminous halo, not a series of gig lamps symmetrically arranged — fiction must capture this","A metaphor for fame","A description of Mrs Ramsay's personality"], ans:1, expl:"Woolf argues that traditional novels' neat plots falsify experience — consciousness is fluid, not organised." },
  { q:"How does Woolf's stream of consciousness differ from Joyce's?", opts:["Woolf uses no punctuation; Joyce uses full punctuation","Woolf is more lyrical and poetic; Joyce is more fragmented and experimental","Woolf writes about men; Joyce writes about women","They are identical techniques"], ans:1, expl:"Woolf's style is more controlled and lyrical; Joyce (especially Molly's soliloquy) is more radical and unpunctuated." },
  { q:"What is the significance of WWI in Woolf's novels?", opts:["She ignores it completely","She depicts it directly through battle scenes","It appears indirectly through traumatised characters like Septimus — the gap between experience and language","She celebrates it as necessary"], ans:2, expl:"Woolf explores the war's psychological aftermath rather than its events directly — trauma as the true subject." },
  { q:"What does the lighthouse represent in To the Lighthouse?", opts:["Death and danger","The unattainable goal and the gap between desire and reality","Political freedom","Scientific progress"], ans:1, expl:"The lighthouse represents aspiration and the gap between wish and fulfilment — the trip planned but repeatedly postponed." }
];

/* ══ MOVEMENTS ══ */
window.QUIZ_DATA.romanticism = [
  { q:"When did English Romanticism begin?", opts:["1750","1789","1798","1820"], ans:2, expl:"1798 — the publication of Wordsworth and Coleridge's Lyrical Ballads is the founding moment of English Romanticism." },
  { q:"What is the Romantic concept of the 'Sublime'?", opts:["Perfect physical beauty","An overwhelming aesthetic experience of nature's power inspiring awe and terror","A type of 18th-century poetry","The elegance of aristocratic art"], ans:1, expl:"The Sublime: standing before a vast mountain, storm or ocean — overwhelmed by nature's power, connecting to something infinite." },
  { q:"What is the key Romantic attitude to Nature?", opts:["Nature is dangerous and must be controlled","Nature is a spiritual force connecting humanity to the divine and the imagination","Nature is irrelevant to human experience","Nature is merely background for human drama"], ans:1, expl:"For the Romantics, Nature is not just scenery but a living spiritual force — opposed to the Enlightenment's mechanistic view." },
  { q:"Who are the first-generation Romantic poets?", opts:["Byron, Shelley, Keats","Blake, Wordsworth, Coleridge","Shakespeare, Milton, Donne","Pope, Dryden, Johnson"], ans:1, expl:"Blake (1757–1827), Wordsworth (1770–1850) and Coleridge (1772–1834) form the first generation." },
  { q:"What historical events influenced Romanticism?", opts:["The Renaissance and Reformation","The French Revolution, American Revolution and Industrial Revolution","The Napoleonic Wars and colonialism","The Black Death and the Wars of the Roses"], ans:1, expl:"All three disrupted traditional society and inspired Romantic ideals of individual liberty and revolt against authority." },
  { q:"What is 'negative capability' (Keats)?", opts:["The ability to write negative poetry","Remaining in uncertainty and doubt without irritably reaching after fact and reason","A technique of writing without punctuation","The capacity to write about pain"], ans:1, expl:"Keats's concept: the great poet can hold contradictions and mysteries without needing to resolve them." },
  { q:"What is Lyrical Ballads (1798)?", opts:["A Victorian anthology","The manifesto and founding text of English Romanticism — by Wordsworth and Coleridge","A collection of Shakespearean songs","A Georgian poetry anthology"], ans:1, expl:"Wordsworth and Coleridge's collaborative collection — Wordsworth described it as poetry about 'common life' in 'real language'." },
  { q:"What is the Romantic hero?", opts:["A noble medieval knight","An isolated individual who defies society, driven by passion and idealism","A humble common man","A rational philosopher"], ans:1, expl:"The Romantic hero is rebellious, passionate, often in conflict with society — see the Byronic hero." },
  { q:"How does Romanticism react against the Enlightenment?", opts:["It accepts Enlightenment reason and extends it","It rejects pure reason in favour of imagination, emotion and subjective experience","It ignores the Enlightenment entirely","It agrees with all Enlightenment principles"], ans:1, expl:"The Romantics saw the Enlightenment's rational, scientific worldview as impoverishing the human spirit." },
  { q:"What is the second generation of Romantic poets known for?", opts:["Greater conservatism and traditionalism","Greater political radicalism, personal rebellion and Mediterranean travel","Focus on nature rather than politics","Religious mysticism"], ans:1, expl:"Byron, Shelley and Keats — more politically radical, personally rebellious and often exiled." }
];

window.QUIZ_DATA.modernism = [
  { q:"What is stream of consciousness in Modernist fiction?", opts:["A description of a flowing river","A narrative technique presenting the continuous flow of thoughts and perceptions","A type of nature writing","A 19th-century novelistic convention"], ans:1, expl:"Stream of consciousness presents characters' inner experience directly — non-linear, associative, immediate." },
  { q:"When did Modernism flourish?", opts:["1780–1830","1870–1900","1900–1940","1950–1980"], ans:2, expl:"Modernism flourished roughly 1900–1940, with its peak in the 1920s following WWI's devastation." },
  { q:"What event most shaped Modernist literature?", opts:["The French Revolution","The Industrial Revolution","World War One","The Russian Revolution"], ans:2, expl:"WWI destroyed faith in progress, tradition and human reason — Modernism reflects this shattered worldview." },
  { q:"What is Ezra Pound's Modernist slogan?", opts:["'Art for art's sake'","'Make it new'","'Less is more'","'Back to basics'"], ans:1, expl:"'Make it new' — Pound's injunction to break completely with artistic traditions and find radically new forms." },
  { q:"What does the 'unreliable narrator' mean?", opts:["A narrator who speaks unreliably fast","A narrator whose account cannot be fully trusted due to bias, limitation or distortion","A narrator who changes the story every chapter","A narrator who speaks in dialect"], ans:1, expl:"The unreliable narrator forces readers to question what is presented as truth — a key Modernist strategy." },
  { q:"How does Modernism treat time differently from earlier fiction?", opts:["Time is always chronological","Time is more precise with exact dates","Subjective psychological time is more important than linear chronological time","Modernism ignores time entirely"], ans:2, expl:"Memory, flashback and non-linear narration reflect how consciousness actually experiences time." },
  { q:"What is the connection between Modernism and Freudian psychoanalysis?", opts:["Freud proved Modernism was a mental illness","Freud's theories of the unconscious influenced the Modernist turn inward — exploring hidden psychological depths","Modernists rejected Freud entirely","Freud was a Modernist novelist"], ans:1, expl:"Freud's discovery of the unconscious made the inner life newly interesting — Modernists dramatised it." },
  { q:"What is the Modernist view of the individual?", opts:["The individual is unified, stable and knowable","The individual is isolated, fragmented and unable to find stable meaning","The individual is naturally social and connected","The individual is subordinate to society"], ans:1, expl:"The Modernist self is multiple, unstable and socially alienated — the old certainties of identity have dissolved." },
  { q:"Who are the key Modernist novelists in English?", opts:["Dickens, Hardy, Trollope","Woolf, Joyce, Conrad, Lawrence","Austen, Brontë, Eliot","Scott, Thackeray, Gaskell"], ans:1, expl:"Virginia Woolf, James Joyce, Joseph Conrad and D.H. Lawrence are the central figures of English Modernist fiction." },
  { q:"What is the Modernist attitude to literary tradition?", opts:["Deep reverence and imitation","Complete rejection and destruction of the past","Complex engagement — drawing on tradition to subvert it","Indifference to the past"], ans:1, expl:"Modernists were deeply aware of tradition — they alluded to it in order to contrast it with the fragmented present." }
];

window.QUIZ_DATA.victorianism = [
  { q:"When was the Victorian Age?", opts:["1714–1789","1789–1837","1837–1901","1901–1945"], ans:2, expl:"The Victorian Age corresponds to the reign of Queen Victoria (1837–1901)." },
  { q:"What is the Victorian novel's main social function?", opts:["Entertainment only","A vehicle for moral and social critique, reflecting and shaping public opinion","Pure aesthetic pleasure","Political propaganda"], ans:1, expl:"Victorian novelists used fiction to examine social conditions — poverty, class, gender, industrialisation." },
  { q:"What is serialised fiction?", opts:["Publishing novels in installments in magazines or newspapers","A type of Victorian dramatic performance","Publishing novels with illustrations","A genre of historical fiction"], ans:0, expl:"Dickens, Hardy and many others published in monthly or weekly installments — making fiction accessible and creating suspense." },
  { q:"What is the main critique in Victorian social realism?", opts:["Praise for British imperialism","Critique of industrialisation, poverty, class inequality and the treatment of women and children","Support for laissez-faire capitalism","Religious orthodoxy"], ans:1, expl:"Victorian novelists like Dickens exposed the human cost of industrial capitalism and demanded social reform." },
  { q:"What characterises the Victorian attitude to respectability?", opts:["Total freedom of behaviour","A rigid code of public morality often concealing private vice — the double standard","Complete indifference to social norms","Romantic rebellion against convention"], ans:1, expl:"Victorian 'respectability' demanded outward conformity while often hiding private transgression — Wilde satirised this." },
  { q:"What major social legislation was passed in the Victorian Age?", opts:["The Reform Act (1832) and Education Acts","The Magna Carta and Bill of Rights","The Industrial Revolution Charter","The Victorian Welfare State Act"], ans:0, expl:"The 1832 Reform Act extended voting rights; later Education Acts made primary education compulsory." },
  { q:"What is the 'condition of England' novel?", opts:["A novel set in England","A genre of Victorian novel examining social problems: industrialisation, poverty and class conflict","A patriotic celebration of English identity","A historical novel about medieval England"], ans:1, expl:"Novels like Dickens's Hard Times, Gaskell's North and South address the social problems created by industrialisation." },
  { q:"What is the role of women in Victorian society as reflected in literature?", opts:["Full equality with men","The 'Angel in the House' — domestic, subservient, morally pure — a stereotype that female writers challenged","Active political participation","Professional and economic independence"], ans:1, expl:"The ideal Victorian woman was the 'Angel in the House' — a domestic figure. Women writers like Brontë and Eliot challenged this." },
  { q:"What does Darwin's The Origin of Species (1859) represent for Victorian culture?", opts:["A religious text","A scientific theory that challenged religious certainty and the idea of a fixed human nature","A work of Victorian fiction","A text on agricultural improvement"], ans:1, expl:"Darwin's theory of evolution undermined the Biblical account of creation — a major source of Victorian anxiety." },
  { q:"What is aestheticism's reaction to Victorian moral literature?", opts:["Full agreement with Victorian morality","Rejection of the idea that art has moral purpose — 'art for art's sake'","Support for religious values in art","A call for more social realism"], ans:1, expl:"Aestheticism (Wilde, Pater) rejected Victorian didacticism — art exists for beauty, not moral instruction." }
];

window.QUIZ_DATA.dystopia = [
  { q:"What defines a dystopian society?", opts:["A perfect utopia achieved by technology","An imagined society with extremely bad conditions — typically totalitarian oppression","A society without government","A medieval feudal system"], ans:1, expl:"Dystopia (from Greek 'bad place') describes a society where totalitarianism, surveillance or environmental collapse has destroyed freedom." },
  { q:"What is the main difference between Orwell's 1984 and Huxley's Brave New World?", opts:["1984 is set in Britain, Brave New World in America","1984 uses pain and fear for control; Brave New World uses pleasure and conditioning","1984 is optimistic, Brave New World is pessimistic","1984 is set in the future, Brave New World in the past"], ans:1, expl:"Orwell: you will be made to suffer. Huxley: you will be made to enjoy. Both are visions of unfreedom." },
  { q:"What drug is used for social control in Brave New World?", opts:["Newspeak","Doublethink","Soma","The Victory Gin"], ans:2, expl:"Soma is a happiness drug that makes citizens passive and uncritical — control through pleasure not pain." },
  { q:"What political regimes inspired the dystopian genre?", opts:["Liberal democracies","Anarchist movements","Totalitarian regimes: Stalinism and Nazism","Constitutional monarchies"], ans:2, expl:"Both Orwell and Huxley wrote in direct response to the rise of Stalinist and fascist totalitarianism." },
  { q:"What is the role of surveillance in dystopian fiction?", opts:["A positive tool for safety","A symbol of the loss of privacy and autonomous thought — total observation means total control","An irrelevant detail","A technological entertainment"], ans:1, expl:"From telescreens to CCTV, surveillance represents the destruction of private space and inner freedom." },
  { q:"What are modern examples of dystopian fiction?", opts:["Pride and Prejudice, Jane Eyre, Wuthering Heights","The Handmaid's Tale, The Hunger Games, Never Let Me Go","Lord of the Flies, To Kill a Mockingbird, The Great Gatsby","Ulysses, Mrs Dalloway, To the Lighthouse"], ans:1, expl:"Atwood, Collins and Ishiguro are major contemporary dystopian writers following Orwell and Huxley." },
  { q:"What does Newspeak attempt to do in 1984?", opts:["Improve communication efficiency","Eliminate words needed to express dissent, making thoughtcrime literally impossible","Create a universal language","Replace all existing languages"], ans:1, expl:"If you cannot express a dissident thought in language, you cannot think it — linguistic control is thought control." },
  { q:"What is the Handmaid's Tale (1985) by Margaret Atwood about?", opts:["A dystopian future Canada ruled by a theocratic patriarchy where women are enslaved as breeders","A love story in Victorian England","A science fiction adventure in space","A satire of American politics"], ans:0, expl:"Set in the Republic of Gilead — a theocratic totalitarian state in what was once the USA, where fertile women serve as 'Handmaids'." },
  { q:"What is the protagonist's role in dystopian fiction?", opts:["To support the system","To be a typical, compliant citizen","To see through the system's lies and attempt resistance — usually failing","To lead a successful revolution"], ans:2, expl:"The protagonist's failure often shows that individual resistance is not enough — institutional change is needed." },
  { q:"How does dystopian fiction relate to present-day concerns?", opts:["It has no relevance to the present","Surveillance, fake news, data collection, authoritarianism — many dystopian elements are now real concerns","It is purely historical","It only applies to communist societies"], ans:1, expl:"NSA surveillance, social media manipulation, rising authoritarianism — 1984 feels increasingly relevant." }
];

window.QUIZ_DATA.gothicnovel = [
  { q:"What are the key elements of the Gothic novel?", opts:["Bright sunlight, rational heroes and social comedy","Darkness, mystery, the supernatural, ruined castles, terror and the uncanny","Realistic social settings and working-class heroes","Urban realism and satire"], ans:1, expl:"Gothic elements: mysterious settings, supernatural events, terror, psychological instability, the uncanny." },
  { q:"What is considered the first Gothic novel?", opts:["Frankenstein","The Mysteries of Udolpho","The Castle of Otranto (1764) by Horace Walpole","Dracula"], ans:2, expl:"Horace Walpole's The Castle of Otranto (1764) is the founding text of the Gothic genre." },
  { q:"What is 'the uncanny' (Freud)?", opts:["Something completely unknown and alien","Something familiar that has become strange and disturbing — the home-like turned threatening","A type of Gothic castle","A Victorian ghost story tradition"], ans:1, expl:"Freud's 'unheimlich' (uncanny): familiar things made strange — the home (heim) that is not homely (un-heimlich)." },
  { q:"How does Frankenstein relate to the Gothic tradition?", opts:["It rejects Gothic elements entirely","It is a purely realist novel","It uses Gothic elements: the sublime, the uncanny, the creator-creature duality, darkness and terror","It is a parody of Gothic fiction"], ans:2, expl:"Frankenstein is Gothic in its sublime Alpine settings, the Creature's uncanniness and the horror of creation." },
  { q:"What is Bram Stoker's Dracula (1897) about?", opts:["A Victorian vampire who threatens modern England — Gothic fears about sexuality, foreignness and infection","A romantic love story","A detective story","A social realist novel about poverty"], ans:0, expl:"Dracula articulates late-Victorian anxieties: about sexuality, foreign invasion, women's independence and modern science vs superstition." }
];

/* ══ J.R.R. TOLKIEN ══ */
window.QUIZ_DATA.tolkien = [
  { type:'mc', q:"When was The Lord of the Rings (Vol. 1) first published?", opts:["1937","1945","1954","1965"], ans:2, expl:"The Fellowship of the Ring was published on 29 July 1954, followed by The Two Towers and The Return of the King in 1955." },
  { type:'mc', q:"What is Tolkien's term for the 'sudden joyful turn' at the end of a fairy tale?", opts:["Catharsis","Eucatastrophe","Epiphany","Dénouement"], ans:1, expl:"Tolkien coined 'eucatastrophe' in On Fairy-Stories (1947) — the sudden joyful turn that does not deny the existence of sorrow and failure." },
  { type:'mc', q:"Which battle did Tolkien fight in during WWI?", opts:["Battle of Verdun","Battle of Passchendaele","Battle of the Somme","Battle of Gallipoli"], ans:2, expl:"Tolkien served as a signals officer in the Battle of the Somme (1916), one of WWI's bloodiest battles, where he lost close friends." },
  { type:'mc', q:"What does the One Ring represent as a symbol?", opts:["Divine protection","Absolute power that corrupts all who wield it","Immortality for its bearer","The strength of friendship"], ans:1, expl:"The One Ring represents the corrupting nature of absolute power — even Gandalf and Galadriel refuse to wield it, knowing it would corrupt them." },
  { type:'mc', q:"What is the name of the literary group Tolkien belonged to at Oxford?", opts:["The Bloomsbury Group","The Pre-Raphaelites","The Inklings","The Fabian Society"], ans:2, expl:"The Inklings were a literary discussion group at Oxford including Tolkien, C.S. Lewis and Charles Williams, who shared and critiqued their works." },
  { type:'mc', q:"What concept describes Tolkien's view of the author as a 'secondary creator'?", opts:["Intertextuality","Sub-creation","Mimesis","Defamiliarisation"], ans:1, expl:"Tolkien argued in On Fairy-Stories that humans, made in God's image, reflect divine creativity through 'sub-creation' — building coherent secondary worlds." },
  { type:'mc', q:"What is Quenya?", opts:["A fictional kingdom in Middle-earth","One of Tolkien's invented Elvish languages","The language of the Orcs","The ancient name for the Shire"], ans:1, expl:"Quenya is one of the two main Elvish languages Tolkien constructed, modelled partly on Finnish. The other major Elvish language is Sindarin." },
  { type:'tf', q:"Tolkien served in WWI, an experience that deeply influenced his writing.", opts:["True","False"], ans:0, expl:"True. Tolkien fought in the Battle of the Somme in 1916. The devastation of war, the importance of ordinary soldiers and the loss of close friends shaped The Lord of the Rings." },
  { type:'tf', q:"Tolkien approved of readers interpreting The Lord of the Rings as a direct allegory for WWII.", opts:["True","False"], ans:1, expl:"False. Tolkien explicitly rejected allegory in his Foreword, preferring 'applicability' — the reader's freedom to find meaning — over the author's controlled allegory." },
  { type:'mc', q:"Which character carries the One Ring to Mount Doom?", opts:["Gandalf","Aragorn","Frodo Baggins","Samwise Gamgee"], ans:2, expl:"Frodo Baggins, a hobbit from the Shire, is chosen as Ring-bearer and carries the One Ring to Mount Doom in Mordor, accompanied by his friend Sam." },
  { type:'mc', q:"What does Mordor symbolise in The Lord of the Rings?", opts:["Ancient Rome","Industrial wastelands and the destruction of nature","The Soviet Union","Medieval feudalism"], ans:1, expl:"Mordor, with its volcanic fires and industrial machinery, represents the destruction of nature by industry — shaped by Tolkien's WWI experience." },
  { type:'mc', q:"What is the 'Gift of Men' in Tolkien's mythology?", opts:["The ability to use magic","Immortality","Mortality — the freedom to leave the world","Great physical strength"], ans:2, expl:"Mortality is called the 'Gift of Men' (Gift of Ilúvatar). Unlike the Elves bound to the world, Men can leave it at death — reflecting Tolkien's Catholic view of death as passage." },
  { type:'mc', q:"When was The Hobbit published?", opts:["1927","1933","1937","1945"], ans:2, expl:"The Hobbit was published in 1937. It introduced Bilbo Baggins, Gandalf, the dwarves and Gollum, and established the world later developed in The Lord of the Rings." },
  { type:'open', q:"Explain Tolkien's concept of the 'eucatastrophe' and give an example from The Lord of the Rings.", modelAnswer:"Tolkien coined 'eucatastrophe' in On Fairy-Stories to describe the sudden joyful turn in a fairy tale that does not deny sorrow but pierces through it. An example is the destruction of the Ring at Mount Doom — at the last moment, when all hope is lost, Gollum bites off Frodo's finger and falls into the fire, unintentionally completing the quest. Tolkien connected this to the Christian concept of the Resurrection as the ultimate eucatastrophe.", keywords:["eucatastrophe","On Fairy-Stories","Mount Doom","Gollum","joy","sorrow","fairy tale"] },
  { type:'open', q:"How does Tolkien use the contrast between the Shire and Mordor to comment on industrialisation?", modelAnswer:"The Shire represents pre-industrial rural England — green, peaceful, communal — while Mordor is a landscape of volcanic devastation, machinery and slavery. Saruman's destruction of the Shire represents industry invading even the last safe haven. Tolkien, shaped by WWI devastation and nostalgia for rural England, uses this contrast to critique the dehumanising effects of unchecked industrial progress.", keywords:["Shire","Mordor","industry","nature","Saruman","WWI","rural England","contrast"] }
];

/* ══ WILLIAM BLAKE ══ */
window.QUIZ_DATA.blake = [];

/* ══ WILLIAM WORDSWORTH ══ */
window.QUIZ_DATA.wordsworth = [];

/* ══ LORD BYRON ══ */
window.QUIZ_DATA.byron = [];

/* ══ WILLIAM SHAKESPEARE ══ */
window.QUIZ_DATA.shakespeare = [];

/* ══ CHARLES DICKENS ══ */
window.QUIZ_DATA.dickens = [];

/* ══ JAMES JOYCE ══ */
window.QUIZ_DATA.joyce = [];

/* ══ T.S. ELIOT ══ */
window.QUIZ_DATA.eliot = [];

/* ══ SAMUEL BECKETT ══ */
window.QUIZ_DATA.beckett = [];
